### ISSUE TITLE
更易理解的 chunkFilename 配置

### ISSUE THREAD

**Issue by miaojiuchen** [sorrycc/roadhog#100]

**Comment by sorrycc** [comment]
为啥要配？

**Comment by sorrycc** [comment]
如果指 hash 的话可以关注 https://github.com/sorrycc/roadhog/issues/69 ，下个版本实现。

**Comment by miaojiuchen** [comment]
chunk file名字是默认的 类似于1.1.js， 很丑啊，可以改掉吗？

**Comment by miaojiuchen** [comment]
ensure第三个参数传了的话会生成比如 1.xxx.js这种，就是想自定义格式

**Comment by sorrycc** [comment]
是配这个吗？http://webpack.github.io/docs/configuration.html#output-chunkfilename

**Comment by miaojiuchen** [comment]
对的

**Comment by miaojiuchen** [comment]
有个workaround，node_modules文件夹里roadhog源码的config/webpack.config.[env].js里面直接加chunkfile配置

![image](https://cloud.githubusercontent.com/assets/9482138/22850726/ca3e32d4-f049-11e6-8946-9ae57a37ee42.png)

**Comment by mdluo** [comment]
https://github.com/sorrycc/roadhog/issues/69#issuecomment-298928686
