### ISSUE TITLE
roadhog 多页面配置

### ISSUE THREAD

**Issue by shaozj** [sorrycc/roadhog#105]
roadhog中配置多页面，`"entry": "src/pages/**/index.js"`，无法实现多页面编译。

![image](https://cloud.githubusercontent.com/assets/7326406/22194402/209579c0-e17d-11e6-8858-d1b87e19c993.png)

![image](https://cloud.githubusercontent.com/assets/7326406/22194414/34690048-e17d-11e6-8102-4f7ffb20fa5b.png)

询问后得到反馈是roadhog是使用文件名 作为key，每个入口的文件名都要不同。

建议：和webpack中入口所能支持的配置一致，用entry的路径作为key，只要路径不同即可，而不需要文件名不同。

**Comment by sorrycc** [comment]
改进：工具层需要在获取到多个同名入口文件给予提示。

**Comment by shaozj** [comment]
@sorrycc ，不能支持文件名相同，但路径不同的多页面构建吗？

**Comment by sorrycc** [comment]
路径作为 key 感觉太难看了，src_pages_index_index.js ?

**Comment by shaozj** [comment]
@sorrycc  ，多页面能不能构建成这样？

dist/index/index.js
dist/list/index.js

![image](https://cloud.githubusercontent.com/assets/7326406/22194693/ec0425ec-e17e-11e6-8907-55e08a2a968a.png)

因为webpack构建出来就是这样的

**Comment by sorrycc** [comment]
建议 pages 仅放各个页面的入口文件。

```bash
+ pages
    - index.js
    - program-list.js
```

然后 entry 配 `src/pages/*.js`。

**Comment by shaozj** [comment]
我之前用这种方式，但是修改 index.js 中的代码时不能 hot reload，所以加了 app.js

**Comment by sorrycc** [comment]
非 router 和 model 文件就是不能 hot reload 的，app.js 应该也不能，和路径无关。

**Comment by shaozj** [comment]
我直接用的react＋webpack，没有用其它的前端框架，我的app.js是可以hot reload 的。我记得我查到的资料是，代码必须是 export 出的一个模块，才能hot reload。

**Comment by sorrycc** [comment]
好吧，你没有用 dva ？

**Comment by shaozj** [comment]
没用

**Comment by shaozj** [comment]
我觉得roadhog应该是完全独立的，不和某个框架存在耦合，所以对entry的设置，如果能和webpack的限制保持一致，我觉得比较好

**Comment by shaozj** [comment]
这样的话，如果用户之前是直接用的webpack，那么他迁移到roadhog上就不会因为entry的配置而需要修改代码了

**Comment by sorrycc** [comment]
多页建议按[这种](https://github.com/sorrycc/roadhog/issues/105#issuecomment-274416762)方式来，我觉得这种方式已经足够了。换成加路径的方式会存在一定的约定，比如为啥路径是 `preview/index.js` 而不是 `src/pages/preview/index`? 

如果需要支持路径输出可以通过 [`webpack.config.js`](https://github.com/sorrycc/roadhog#配置) 覆写 webpack 的 entry 配置。

**Comment by valleykid** [comment]
@shaozj 按照[这种方式](https://github.com/sorrycc/roadhog/issues/105#issuecomment-274416762)hot reload失效估计是个bug，我找下深层次原因。

另外 我的想法是，这个地方可以设置文件夹路径，检测到是文件夹时，遍历其文件目录。如果是文件则key=文件名，如果是文件夹则key=文件夹名进行处理。如：
```
+ pages
     + service
          - index.js
          - index.css
          - ...
     - app.js
```
会打包成：
```
dist/service.js
dist/app.js
```
这样既满足特殊情况下入口文件逻辑复杂时需要文件夹组织的情况，又满足大部分简单场景，两位觉得如何？

**Comment by sorrycc** [comment]
感觉这种黑盒约定太强了，很难和用户解释清楚。

**Comment by shaozj** [comment]
@valleykid ，我觉得打包成
`
dist/service/index.js
dist/app.js
`
这样比较好

**Comment by codering** [comment]
@sorrycc 对于单页面，要想对react,antd等三方库单独打包，该如何配置？

**Comment by spiroo** [comment]
@shaozj 请问多页面开发，需要在public目录下建立多个html文件吗？然后每个html引入不用的入口文件？是这样做么？
好像官方没有多页面开发的demo吧！

**Comment by sorrycc** [comment]
@spiroo 是这样。
