### ISSUE TITLE
建议提供构建时间和构建文件大小信息，便于分析构建性能

### ISSUE THREAD

**Issue by shaozj** [sorrycc/roadhog#108]
建议提供编译时间和构建文件大小信息，便于分析构建性能
包括开发时的编译时间，修改代码重编译时间，构建后文件大小
build时的编译时间

**Comment by valleykid** [comment]
近期会做上，请耐心等待

**Comment by sorrycc** [comment]
> 构建后文件大小

`roadhog build --analyze`

> build 时的编译时间

`time roadhog build`

> 包括开发时的编译时间，修改代码重编译时间，

这两个提供了意义并不大。

**Comment by shaozj** [comment]
@sorrycc , 我觉得开发时的编译时间和重编译时间是我比较关心的，我们写代码时大部分时间用到的是这个指标。构建时的时间只在代码要发布时才构建一次，那个时间倒是没太大关系

**Comment by sorrycc** [comment]
我说的意义不大原因是知道了也并不能做什么来改进。

**Comment by shaozj** [comment]
别人可以自己写webpack.config.js 来优化时间啊

**Comment by shaozj** [comment]
至少让用户知道编译花了多少时间，心里有底，对这个工具的性能等参数心里有数，这样不更靠谱点吗

**Comment by sorrycc** [comment]
使用 roadhog 不推荐写 webpack.config.js。

**Comment by caoxingao** [comment]
roadhog buid 打包包含proxy的项目无法正常代理请求
