### ISSUE TITLE
为什么less中使用tint方法会出现这样的错误呢

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [sorrycc/roadhog#110]
Module build failed: error evaluating function `tint`: color2.toHSL is

**Comment by liuhuapiaoyuan** [comment]
![1111111](https://cloud.githubusercontent.com/assets/8020726/22241844/19c6801e-e25c-11e6-8007-ffe13032da6a.jpg)

**Comment by sorrycc** [comment]
skin.less 里写了 tint?

**Comment by liuhuapiaoyuan** [comment]
额。不好意思。。。原来是txt-color这个字段有问题~~~
