### ISSUE TITLE
使用 npm run build -- --outputPath='../../dist/'命令编译，public拷贝的目的地错误 

### ISSUE THREAD

**Issue by lnlfps** [sorrycc/roadhog#111]
查看webpack.config.prod的配置，appPublic是拷贝到paths.appBuild下（项目目录下固定的dist目录），而项目编译后的真实输出目录是通过命令参数传入的'../../dist/'。

**Comment by valleykid** [comment]
是不是没拷贝到--outputPath设置的目录？这个地方你的用法是错的：npm run build --outputPath，npm命令才能获取到outputPath参数，在执行roadhog build时已经丢失参数了。
你应该直接执行 `roadhog build --outputPath='../../dist'` 
或者改写 package.json中的 build为 `roadhog build --outputPath='../../dist'`

**Comment by lnlfps** [comment]
不好意思，是我没说清楚，我条命令是我本地package.json命令，加两个“--”符号是可以把参数传递到roadhog的，执行完成后，roadhog也正确的把打包好的js输入到指定目录，但public目录中的文件没有拷贝到指定目录，依然输入到默认的dist目录下。我看了roadhog的webpack.config.prod.js文件，拷贝public的配置可能有问题（webpack打包输出和public拷贝输出，两个取来来之不同变量），请核查

**Comment by valleykid** [comment]
ok，我看下。

**Comment by yvanwangl** [comment]
按照代码修改，仍然是把public下的文件copy到了dist下
