### ISSUE TITLE
mock特性 内置bodyParser

### ISSUE THREAD

**Issue by DickyT** [sorrycc/roadhog#112]
在最新`0.5.x`的`roadhog`里面, 支持了mock服务器, 并支持直接传入函数来操作`express`的response handler, 但是`req.body`是`undefined`的, 看起来并没有内置bodyParser, 请问下中远期有支持这个功能的打算吗? 谢谢做出这么好用的framework
```
export default {
  // 支持自定义函数，API 参考 express@4
  'POST /api/users/create': (req, res) => { res.end('OK'); },
};
```

**Comment by sorrycc** [comment]
请在 #86 里跟进。
