### ISSUE TITLE
线上调试功能打通

### ISSUE THREAD

**Issue by valleykid** [sorrycc/roadhog#115]
webpack-dev-server 的 proxy内部如何实现的，好像不支持线上调试

**Comment by zhangshihuann** [comment]
请问用build完成后放到生产环境的程序可以用断点调试吗？代码已经被压缩的看不清楚了  但是我想看看程序走了一条什么分支 @sorrycc

**Comment by zhangshihuann** [comment]
网上有说打包的时候加上source map，请问这个用roadhog打包的话可以怎么配置

**Comment by acwong00** [comment]
@zhangshihuann 请问最后怎么解决？

**Comment by remotesc2** [comment]
@zhangshihuann
请问这个，怎么解决的？
