### ISSUE TITLE
antd 主题字体本地化问题

### ISSUE THREAD

**Issue by xutou12** [sorrycc/roadhog#117]
我用 `dva` 搭建基于 `antd` 的项目，`dva` 又是使用 `roadhog` 来开发构建的，我字体本地化出现个问题，不知道是不是可以再这里提这个问题。

之前用 `dora + atool-build` 方式编译，项目字体配置是这样

```js
   {'icon-url': `"${path.relative( './~/antd/lib/style/*', './src/fonts/iconfont' )}"`}
```

`相对地址` 可以正常使用，用了新版本后就不行了只能用 `绝对地址`。

> 由于我的项目不是在web根目录的所以 `绝对地址` 行不通。

在 webpack 中 debug
`less-loader` 参数设置是这个地址：`'../../../../../src/fonts/iconfont'`
最终生成的却是这个地址：`'../src/fonts/iconfont'`

build 最终错误信息是：
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/fonts/iconfont.eot in /Users/rainx/Documents/code/test-project/node_modules/antd/lib/style

> 我对 webpack 了解还很浅薄，花了两天调试最终还是一头雾水，不知道是新版本 webpack bug 还是 roadhog 配置问题

**Comment by xutou12** [comment]
**找到问题所在了**

主要是 `style-loader` 的原因，它在把 `loader` 的  `request` 从 `绝对地址` 转成 `相对地址` 时，把 `?` 后面的参数一同传给了 `path.relative` 函数，`path.relative` 把参数中的地址一并转成了 `相对地址`

然后 `webpack` 在查找依赖时就会报错了

**Comment by hellheaven** [comment]
@xutou12 麻烦问下是在哪里改的？我现在外部css里设置背景图片有类似的问题。

**Comment by xutou12** [comment]
@hellheaven `loader-utils` 包已经更新了，字体本地化可以正常使用了。
