### ISSUE TITLE
mock文件出错

### ISSUE THREAD

**Issue by hellheaven** [sorrycc/roadhog#118]
roadhog 0.5.3
.roadhogrc.mock.js如下：
export default {
  // 支持值为 Object 和 Array
  'GET /api/users': { users: [1,2] },

  // GET POST 可省略
  '/api/users/1': { id: 1 },

  // 支持自定义函数，API 参考 express@4
  'POST /api/users/create': (req, res) => { res.end('OK'); },
};

编译时提示

Failed to parse mock config.

Error in Cannot read property 'getOwnPropertySymbols' of undefined (While processing preset
TypeError: "C:\\workspace\\one\\node_modules\\roadhog\\node_modules\\babel-preset-es2015\\lib\\index.js")

**Comment by valleykid** [comment]
请提供下node版本 npm版本，还有系统信息，我本地看能否复现下。从出错信息上看像是 依赖包问题，要不你删除掉node_modules文件夹重装下试试？

**Comment by hellheaven** [comment]
感谢你的回复，我的环境是：
node 6.9.4
win10 64位

**Comment by hellheaven** [comment]
升级NPM后并重装后，问题解决。谢谢

**Comment by baixiaosh** [comment]
很奇怪的一个类似这样的问题：
linux（Ubuntu16）下直接输入命令 BROWSER=none PORT=8080 HOST=127.0.0.1 roadhog server会有这个错：Failed to parse mock config. Error in maximum call stack size exceeded
但是配置在package.json里然后输入npm run dev又不会报错
