### ISSUE TITLE
请问webpack的resolve.alias配置有计划加上吗？

### ISSUE THREAD

**Issue by miaojiuchen** [sorrycc/roadhog#121]
项目中很深处的文件经常要去根目录拿一些配置、公共组件，没有alias要写很多的 "../"，
或者有什么替代方案吗？

**Comment by longzb** [comment]
这个要强烈支持。我是达到了六个../

**Comment by sorrycc** [comment]
六个 `../`。。会不会目录结构不太合理?

**Comment by ly710** [comment]
这个竟然没有。。。很重要啊！

**Comment by liuhuapiaoyuan** [comment]
推荐大家可以先用：》
 "babel-plugin-module-alias": "^1.6.0" 这个插件解决

```
"extraBabelPlugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    ["import", { "libraryName": "antd", "style": true }],
    ["module-alias", [
      { "src": "./src", "expose": "src" },
    ]]
  ],
```

**Comment by mdluo** [comment]
更推荐用 `babel-plugin-module-resolver`

```
["module-resolver", {
  "root": ["./src"],
  "alias": {
    "test": "./test",
    "underscore": "lodash"
  }
}]
```

根路径（类似于 webpack 的 `resolve.root`）和指定 alias 都有了

https://github.com/tleunen/babel-plugin-module-resolver

**Comment by sorrycc** [comment]
推荐用 @mdluo 的方法进行配置。

**Comment by sm0king** [comment]
@sorrycc   虽然推荐的有插件，但webpack原生支持的为什么还要再用一个插件，所以建议最好还是可以把webpack更开放一些，如果能做到.roadhogrc配置文件里能支持webpage的配置，真的不能更好。真的。

**Comment by oluckyman** [comment]
I’m using `module-resolved` as recommended:
```
  "extraBabelPlugins": [
    ...,
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "~": "./src"
      }
    }]
  ],
```
It allows to import files like this from anywhere:
```
import schema from '~/models/schema'
```
It works great in browser. But it does not work when I run tests.
When I’m trying to test `src/models/user.js` which has that line:
```
import { saveOne, fetchOne } from '~/services/schemas';
```
it throw the error:
```
Error: Cannot find module '~/services/schemas'
```

**Comment by oluckyman** [comment]
Made an issue #266

**Comment by VanquisherMe** [comment]
babel-plugin-module-resolver
安装后
js如上方式可以设置alias 但是 less 里面好像没法用到，是否缺少了什么配置？
![vg 0pih 6 wv3g2y7jh 1](https://user-images.githubusercontent.com/4927398/29419023-956f618c-83a0-11e7-93aa-218f111dab78.png)
![vw qo og1t y56t8nb7jx2g](https://user-images.githubusercontent.com/4927398/29419024-957522ca-83a0-11e7-8722-880af4327129.png)
![a i ya fyhjt_h_1p1 5 g](https://user-images.githubusercontent.com/4927398/29419025-95aa486a-83a0-11e7-9aee-5c70fe8d89cc.png)

**Comment by sorrycc** [comment]
`./src/themes` 吧，相对于项目根目录的。

**Comment by VanquisherMe** [comment]
尝试了下未有效果
![h8v_ lf j v3030s5 h x8](https://user-images.githubusercontent.com/4927398/29442276-21848744-8403-11e7-821d-038969e6006d.png)
![h 60g x 8vz43g ub c](https://user-images.githubusercontent.com/4927398/29442277-21aef010-8403-11e7-88fc-436ac267ec50.png)

**Comment by pigcan** [comment]
less 是不支持的  同样你使用 webpack 的 alias 想要在 less 文件中使用 alias 也是不能实现的。

**Comment by pigcan** [comment]
可以使用 less 的 plugin -》 less-plugin-rewrite-import

但是使用这个插件后会有一些需要联合配合的点：需要关闭 less-loader 的 resolve 逻辑，该逻辑在升级了 webpack@3 和 最新的 less-loader.

**Comment by Runtu4378** [comment]
# 亲测的解决方法

1. 在项目根目录创建 `webpack.config.js` 文件
2. 内容如下：

```javascript
// webpack.config.js
const webpack = require('webpack')
const path = require('path')

module.exports = function wp(webpackConfig, env) {
  webpackConfig.resolve.extensions.push('.less')
  webpackConfig.resolve.alias = {
    less: path.join(__dirname, 'src/styles'),
  }

  return webpackConfig
}
```

3. 需要使用 alias 引入公用变量文件的 .less 文件的内容是：

```less
// user.less
@import '~less/vars.less';

.lab {
  width: 200px;
  border-left-style: solid;
  border-left-color: @border-color-base;
  border-left-width: 1px;
}
```

4. 顺利引入 `src/styles/vars.less` 里面定义的变量

**Comment by Gavinchen92** [comment]
大家的eslint报错提示怎么解决的, 我根据官方文档配置.eslintrc好像不起作用
`
 "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  }
`

**Comment by 940941188** [comment]
@Gavinchen92 新建个 .babelrc，
```json
{
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "abc": "./abc"
      }
    }]
  ]
}
```
[代码中的注释](https://github.com/tleunen/eslint-import-resolver-babel-module/blob/9fb9c623e32d82730b4ff8da0c50263cc457e254/src/index.js#L84)

**Comment by HeliumLau** [comment]
我装了module-resolver，如下配置的，为什么npm start的时候报错“Uncaught TypeError: _g2.default.track is not a function”？
```
// node_module
"babel-plugin-module-resolver": "^3.0.0"
```
![tim 20171214094519](https://user-images.githubusercontent.com/24445005/33971472-86051da2-e0b3-11e7-90f2-252278b0f4ce.png)

**Comment by lsdiao** [comment]
@HeliumLau `src/g2.js` 文件的里的 `import G2 from 'g2'` 改为
`import G2 from '../node_modules/g2'`
原因是你配置了别名后g2不能被正常找到

**Comment by shengbeiniao** [comment]
居然不支持webpack的context和resolve root
