### ISSUE TITLE
关于BUILD后index.js文件大小的问题

### ISSUE THREAD

**Issue by sd632367** [sorrycc/roadhog#123]
File sizes after gzip:

  371.98 KB  dist\index.js
build后提示的文件大小
但是实际文件是
index.js 1.3M
已经按照教程上指导的按需加载了
请问为什么2个文件的大小不一致
是不是index.js这个文件会越来越大
刚接触dva很多不明白的地方，请指教

**Comment by codering** [comment]
它说的是gzip后的大小是300多K, 这只是一个参考，因为现在静态服务器都开启了gzip压缩。

**Comment by sd632367** [comment]
好的～谢谢～
