### ISSUE TITLE
import xxx.css 在build命令后不会被打包，而在调试时会被打包

### ISSUE THREAD

**Issue by miaojiuchen** [sorrycc/roadhog#124]
![image](https://cloud.githubusercontent.com/assets/9482138/22822474/a2c4c568-efba-11e6-9c0a-eb9e52097ffa.png)
类似这种写法

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/22822554/e0d7c698-efba-11e6-9993-813e74d2db29.png)
这是调试时候的bundle

而build出来的包里面丢失这部分css的module

**Comment by sorrycc** [comment]
`import "~nprogress/nprogress.css"` 记得在 css 里 import 依赖是要加 `~` 前缀的。

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/22870281/c3be806a-f1e0-11e6-98e3-c42a4b4f1799.png)
这样吗？报错哎 

Module not found: '~nprogress/nprogress.css'


我是在js里引入这个css的

**Comment by valleykid** [comment]
调试阶段，样式文件会被js动态插入页面中，这样做为了样式更新hmr时不刷新页面；而build时，样式文件会打包成独立的css文件，也不会被打包后的js引用，需要在页面中用<link>标签引入

**Comment by miaojiuchen** [comment]
@valleykid 你好，build 出来的文件里没有这个css呢

**Comment by valleykid** [comment]
build出来没有css文件很奇怪，有没有报错？如果调试阶段正常，build就不行，我觉得roadhog配置错了吧，能否贴一下配置文件内容？

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/23706139/f605b8c6-0447-11e7-90f5-c1b235094f55.png)
@valleykid  你好这是我的配置内容，这两天一直在写后端所以这个issue没有再查下去，再帮忙看一下

**Comment by angus1105** [comment]
同样遇到这样的问题。。。

**Comment by YuriTu** [comment]
same

打包之后antd的所有样式都没有了，只有自己import的有

**Comment by karrynew** [comment]
> ![image](https://cloud.githubusercontent.com/assets/9482138/23706139/f605b8c6-0447-11e7-90f5-c1b235094f55.png)
> @valleykid 你好这是我的配置内容，这两天一直在写后端所以这个issue没有再查下去，再帮忙看一下

最后怎么解决的？ 我这边也遇到了
