### ISSUE TITLE
npm或者yarn, 如何安装webpack2版本?

### ISSUE THREAD

**Issue by lincenying** [sorrycc/roadhog#126]
npm或者yarn, 如何安装webpack2版本?

**Comment by codering** [comment]
npm i webpack@2.x

随便说下，这种问题不该在这里问。问google就好了

**Comment by lincenying** [comment]
@codering  webpack的安装我当然知道, 我问的是roadhog的webpack2版本, 在版本里有webpack2分支
https://github.com/sorrycc/roadhog/tree/webpack2

**Comment by lincenying** [comment]
还没发布...
