### ISSUE TITLE
测试报错，找不到 '_mocha'

### ISSUE THREAD

**Issue by xutou12** [sorrycc/roadhog#128]
依赖全新安装后 `mocha` 的路径有点问题

`package.json` 文件添加 `"script": { "test": "roadhog test --coverage" }`

```bash
$ npm run test

> @ test /Users/rainx/Documents/code/Git/PromiseSPA
> roadhog test --coverage

Unable to resolve file [/Users/rainx/Documents/code/Git/PromiseSPA/node_modules/roadhog/node_modules/.bin/_mocha]
Try "istanbul help" for usage
```

是否考虑加个路劲参数？

**Comment by sorrycc** [comment]
感觉路径应该是这个吧，正确的路径应该是啥?

**Comment by xutou12** [comment]
@sorrycc  我全新安装了之后 ` roadhog/node_modules` 没有这个目录，`_mocha` 应该在 `~/.bin/_mocha` 吧，不是 `roadhog` 下吧

**Comment by xutou12** [comment]
抱歉回复的晚了，正好有事情一直在忙
