### ISSUE TITLE
为什么代码文件必须放在src目录下，这么做的理由是什么？

### ISSUE THREAD

**Issue by pixcai** [sorrycc/roadhog#129]
有个问题不明白，webpack只会打包代码中依赖到的文件，也就是说，我在`src/index.js`中引入了什么，才会打包什么，那为什么在源码中的webpack配置中，对一些资源文件的编译都设置了`include: paths.appSrc`呢？感觉没必要啊，请问下最初开发roadhog的时候这么做的原因是什么呢？

**Comment by valleykid** [comment]
babel-loader编译限定在源文件夹中，不然的话，对node_modules中的文件进行AST(抽象语法树)解析 性能会显著下降。其他loader可以不设定。

**Comment by pixcai** [comment]
用`exclude: /(node_modules|bower_components)/`，这样不是更好？

**Comment by fsiaonma** [comment]
可否把 appSrc 目录开放配置？ 有这样规划吗？
