### ISSUE TITLE
关于pxtorem 无效问题

### ISSUE THREAD

**Issue by iceshu** [sorrycc/roadhog#134]
环境 win10
npm 3.10.9
node 6.92
"roadhog": "^0.5.2"
dva new出来之后新增一个.roadhogrc.js  内容为
`extraPostCSSPlugins: [
  pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }),
],`
用了antmobile 但是我写央视是用px 并没有转换成rem  高清的内嵌脚本已经加了 还要配置些什么么？

**Comment by iceshu** [comment]
@sorrycc

**Comment by jozhi** [comment]
我也同样遇到这个问题。

**Comment by iceshu** [comment]
@jozhi 我昨天解决了 我直接修改的roadhog文件夹下lib 里面的config 文件夹里面的webpack配置文件：先定义pxtorem
`var pxtorem = require('postcss-pxtorem');
var pxtorem2 = _interopRequireDefault(pxtorem).default;`

然后再postcss方法里面直接把
`pxtorem2({
          rootValue: 100,
          propWhiteList: [],
        })]`
加到数组里了、最终是这样
`    postcss: function postcss() {
      return [(0, _autoprefixer2.default)(config.autoprefixer || {
          browsers: ['>1%', 'last 4 versions', 'Firefox ESR', 'not ie < 9']
        }),
        pxtorem2({
          rootValue: 100,
          propWhiteList: [],
        })].concat(config.extraPostCSSPlugins ? config.extraPostCSSPlugins : []);
    },`

**Comment by jozhi** [comment]
@iceshu  大爱，给出的最终代码很赞，duang 一下改好了。。 一言不和就改源码这种风格真的是很霸气， dva+ant-mobile 现在还没开始写已经处处开始改源码了，好爽。。

**Comment by valleykid** [comment]
这个应该是roadhog的bug，我看下修复下

**Comment by uames** [comment]
我同事找到了解决的办法，`.roadhogrc.js` 文件配置：
`const pxtorem = require('postcss-pxtorem');
const pxtorem2 = _interopRequireDefault(pxtorem).default;
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
export default {
	entry: "src/index.js",
	"env": {
	  "development": {
	    "extraBabelPlugins": [
	      "dva-hmr",
	      "transform-runtime",
	      ["import", { "style": "css", "libraryName": "antd-mobile" ,"libraryDirectory": "lib"}]
	    ],
	    extraPostCSSPlugins: [
	      pxtorem2({ rootValue: 100, propWhiteList: [], })
	    ]
	  },
	  "production": {
	    "extraBabelPlugins": [
	      "transform-runtime",
	      ["import", { "style": "css", "libraryName": "antd-mobile" ,"libraryDirectory": "lib"}]
	    ],
	    extraPostCSSPlugins: [
	      pxtorem2({ rootValue: 100, propWhiteList: [], })
	    ]
	  }
	}
}
`

**Comment by sorrycc** [comment]
是 roadhog 的 bug 吗? 欢迎 PR 啊。

**Comment by paranoidjk** [comment]
实测在`.roadhogrc.js`类似如下配置没问题：
```js
import pxtorem from 'postcss-pxtorem';

export default {
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100,
          propWhiteList: [],
        }),
      ],
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100,
          propWhiteList: [],
        }),
      ],
    }
  }
}

```

@iceshu @jozhi  注意check不要`.roadhogrc`和`.roadhogrc.js`两个文件同时存在，前者优先级更高会覆盖后者，要把`.roadhogrc`删掉！！

**Comment by paranoidjk** [comment]
@sorrycc roadhog 这个repo 给我加个权限？可以帮忙处理一些来自 antd 用户的问题 ：）

**Comment by sorrycc** [comment]
@paranoidjk  好的，👍 。

**Comment by NicholasNC** [comment]
@sorrycc 

请问，pxtorem，可以限定只转化业务代码的值吗？

现在引入了ant design mobile，不希望把第三方UI框架的css都转换

**Comment by Richar-Dada** [comment]
@NicholasNC Ni 问题解决了吗  我遇到这个问题
