### ISSUE TITLE
请问通过roadhogrc-theme配置的antd主题，在antd-mobile项目上不生效

### ISSUE THREAD

**Issue by felixzxk** [sorrycc/roadhog#136]
请问我要如何配置antd-mobile主题？我看antd-mobile的className都有个‘am-’前缀，这个前缀在配置theme时是否可用？希望大神指点~
roadhogrc
{
 "theme": "src/theme.js",
}

theme.js
/*eslint-disable*/
module.exports = () => {
    return {
        "@font-family": "Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif",
        "@primary-color": "#1DA57A",
        "@link-color": "#1DA57A",
        "@border-radius-base": "2px",
        "@font-size-base": "14px",
        "@line-height-base": "1.2"
    };
};

**Comment by caigehui** [comment]
我也遇到了这个问题

**Comment by paranoidjk** [comment]
稍后我会在官方Demo里加一个roadhog使用的demo

请关注这里 https://github.com/ant-design/antd-mobile-samples

**Comment by paranoidjk** [comment]
官方Demo已增加与Roadhog配合使用的demo

https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog

包括：
- svg 配置
- rem 配置
- theme 配置

**Comment by kangning1206** [comment]
地址：https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog 

访问 404！

**Comment by paranoidjk** [comment]
@kangning1206 https://github.com/ant-design/antd-mobile-samples/tree/master/web-roadhog

**Comment by Lie8466** [comment]
之前工程里面没有用less，为了改主题引入了太多的包
