### ISSUE TITLE
如何在roadhogrc配置文件中添加新的babel-loader？比如svg-sprite-loader

### ISSUE THREAD

**Issue by felixzxk** [sorrycc/roadhog#137]
antd-mobile1.0.0以后中需要使用svg-sprite-loader，之前在node_modules/roadhod/conf目录里修改开发、生产环境的配置，工程上的icon可以用了，但是这中修改方式太笨了，能不能通过roadhogrc在目标目录绑定新的loader？望指点！

**Comment by paranoidjk** [comment]
I will create a PR for this
