### ISSUE TITLE
publicPath设置后在build时无效

### ISSUE THREAD

**Issue by hellheaven** [sorrycc/roadhog#139]
.roadhogrc中设置publicPath='/test/'
甚至我直接在node_module里的roadhog里的config里直接改webpack.config.prod.js
里的publicPath都没用。build后依然是/

**Comment by mimimi1227** [comment]
@hellheaven  你之后 怎么解决的呢

**Comment by xiaofengqqcom123** [comment]
@hellheaven @mimimile 然后呢？你们是怎么解决的？
