### ISSUE TITLE
less或css中设置背景图片时不能使用相对路径

### ISSUE THREAD

**Issue by hellheaven** [sorrycc/roadhog#140]
类似这样
background: transparent url("/images/bg_mobile_head.jpg") no-repeat 0 0;
是ok的。
但使用以下格式
background: transparent url("images/bg_mobile_head.jpg") no-repeat 0 0;
则会出现

Failed to compile.

Error in ./src/routes/menu/Menudetail.less
Module not found: 'images/bg_mobile_head.jpg' in C:\workspace\src\routes\MenuDetail

 @ ./~/.0.26.1@css-loader?importLoaders=1&modules&localIdentName=[local]___[hash:base64:5]!./~/.1.2.2@postcss-loader!./~/.2.2.3@less-loader?{"modifyVars":{}}!./src/routes/Menuschema/Menudetail.less 6:163-199

**Comment by hellheaven** [comment]
~""、less变量这些方法试了，都不行

**Comment by hellheaven** [comment]
临时解决办法是用alias指定images目录。 
@sorrycc 有更好的解决办法吗？

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva-example-user-dashboard/blob/a59c5b9/src/routes/IndexPage.css#L16 我发现这么引没有问题啊。

**Comment by SynChron1zed** [comment]
@sorrycc  问下 为啥<img/> src 的图片路径本地环境没有问题  路霸打包之后就找不到图片路径了 如果是css bgurl 我还可以修改打包后的css 但是img src引用的根本改不了 有遇到这种问题么

**Comment by hellheaven** [comment]
是因为我的图片放在public目录下的，所以会出错。assets下不会出错。
如我的图片路径为
public/images/yay.jpg
在css中写 /images/yay.jpg可行。
但./images/yay.jpg则不行

**Comment by SynChron1zed** [comment]
@hellheaven  我的问题和你不一样 。 你的这个问题参考例子就可以解决 。 我的图片现在是写在 img标签里面  src引用依赖  开发环境没有任何问题 打包之后 先上图片就显示不了了  css bgurl 的路径应该是 /static/image/xx.jpg 而img 标签的src 会变成static/image/xx.jpg

**Comment by SynChron1zed** [comment]
@sorrycc  云兄

**Comment by SynChron1zed** [comment]
搞定了 。，，，

**Comment by hellheaven** [comment]
@sorrycc 还是我理解错了public目录的作用，用到的图片还是应该放在assets里，只有html里引用的图片才放在public里？

**Comment by sunplum123** [comment]
@SynChron1zed 兄弟，怎么搞定的

**Comment by SynChron1zed** [comment]
应该是在.roadhogrc 设置 "publicPath": "xxx" 去年的事了
