### ISSUE TITLE
打包后字体图片能不能一起下载打包

### ISSUE THREAD

**Issue by liysw** [sorrycc/roadhog#143]
用dva-cli创建的项目，打包后的文件是放到内部局域网使用的，但是里面引用的ant组件的字体图片等都是外链，内网无法访问外网。请问要怎么解决呢

**Comment by sorrycc** [comment]
参考 #117

**Comment by liysw** [comment]
按照#117的样子，我用ant默认主题的话，用到默认字体时就只能去node_modules里改ant的css文件了吗？改成"${path.relative(.....)}"吗？
