### ISSUE TITLE
如何支持除development和production外的其他环境变量配置

### ISSUE THREAD

**Issue by sosilence** [sorrycc/roadhog#145]
roadhog的build和start脚本分别对应了env/development和production，但实践中存在第三种开发环境（可能是预发或集成测试），配置和前两种也都不一样，但现在似乎没办法支持这种情况。

**Comment by codering** [comment]
觉得可以用`.roadhogrc.js` 来配置，在这个js里可以做些动态配置

**Comment by sorrycc** [comment]
对于源码来说就两种吧，配 production 主要是为了去除一些框架库里的冗余调试代码。预发和集成测试要做什么特殊处理? 特殊处理的话可以通过额外的环境变量来配，不一定要用 `NODE_ENV`。

**Comment by anhuiliujun** [comment]
@sorrycc 
设想这样一种场景，我的预上线环境和生产环境，会调用不同的服务器api，比如预上线环境会调用 `http://staging.xxx.com`而生产环境会调用`http://production.xxx.com`，之前使用webpack的话，我会用definePlugin，在webpack.staging.js与webpack.production.js里设置不同的env，然后代码中直接判断env，选择不同的host即可，不知对于这种情况roadhog要怎么处理呢？我看了下rodhog提供了define配置，但是问题是roadhog build不接受不同的配置文件啊？

烦请赐教！

**Comment by sorrycc** [comment]
可以定义 [define](https://github.com/sorrycc/roadhog#define) 的。

**Comment by sorrycc** [comment]
API 域名不能在 html 里输出吗?

**Comment by anhuiliujun** [comment]
@sorrycc 感谢回复，茅塞顿开，确实可以判断当前的域名选择不同的api，但是这样就意味着我需要在代码里写逻辑判断，假设出现迁移域名的情况，我可能还需要改动代码，如果能在不同的环境下直接将配置注入进去，这样是不是好些呢？这样的话我维护的是配置，是不是也可以呢？

**Comment by sorrycc** [comment]
我们公司内是这么做的，域名配置会在渲染 html 时输出。

**Comment by acmeid** [comment]
我觉得 @anhuiliujun 说的有道理，允许增加额外的环境，对于区分运行环境会更加方便并容易维护

**Comment by WangZi1997** [comment]
嗯 等你加个 额外的自定义环境

**Comment by loocer** [comment]
其实博主已经说了用额外的环境变量来区分，只是你们没听懂，来来来，上代码给你们看看https://www.cnblogs.com/zhangzhaowei/p/9639359.html
