### ISSUE TITLE
.roadhogrc.js 疑问

### ISSUE THREAD

**Issue by xoptimal** [sorrycc/roadhog#148]
我配置了 .roadhogrc.js , 配置该如何指向这个文件  ?

**Comment by xoptimal** [comment]
.roadhogrc 
```
{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "style": "css", "libraryName": "antd-mobile" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  }
}
```

.roadhogrc.js
```
const path = require('path');
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
  path.resolve(__dirname, 'src/public/svg'),  // 业务代码本地私有 svg 存放目录
];

export default {
  svgSpriteLoaderDirs: svgSpriteDirs,
  extraPostCSSPlugins: [
    pxtorem({
      rootValue    : 100 * (1080 /750),
      propWhiteList: []
    })
  ]
}
```

npm start 后 , 发觉 .roadhogrc.js 并不起效 ~

**Comment by iceshu** [comment]
#134 里有解决方案 那个凑合用吧

**Comment by sorrycc** [comment]
`.roadhogrc` 和 `.roadhogrc.js` 只能用一个。。

**Comment by xoptimal** [comment]
我删除了 .roadhogrc后 , npm start 会报找不到 .roadhogrc错误 ~

**Comment by xoptimal** [comment]
输出: Failed to parse .roadhogrc config.   正因为这个问题, 所以我才提出怎么指向 .roadhogrc.js 而不是 .roadhogrc

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/tree/master/test/fixtures/build/svgSpriteLoaderDirs
参考这个例子，用例是能过的。

**Comment by xoptimal** [comment]
>
```
// npm i antd-mobile -S
const path = require('path');
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
  path.resolve(__dirname, 'src/my-project-svg-foler'),  // 业务代码本地私有 svg 存放目录
];

export default {
  // ...
  svgSpriteLoaderDirs: svgSpriteDirs,
  //...
}
```

并且,  已经安装 npm install svg-sprite-loader -D    , 然而 Icon 仍未显示出来 ~

当前配置: 
```
import pxtorem from 'postcss-pxtorem';
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // 依赖包 a 内置svg
];

export default {
  svgSpriteLoaderDirs: svgSpriteDirs,
  entry: "src/index.js",
  "env": {
    "development": {...}
    "production": {...}
  }
}
```

**Comment by xoptimal** [comment]
已解决, 版本问题 !

**Comment by caigehui** [comment]
@xoptimal 请问如何解决

**Comment by xoptimal** [comment]
不是说了版本问题了吗?  更新版本即可解决噢 !   @caigehui

**Comment by Aibokalv** [comment]
@xoptimal  我也遇到了一样的问题了 更新了本地的antd-mobile和  roadhog依然无效
这是package.json的相关版本
`"antd-mobile": "^1.0.1",
"roadhog": "^0.6.0-beta1",
"svg-sprite-loader": "^0.3.0"
`
可是依然无法显示

**Comment by paranoidjk** [comment]
@Aibokalv 

你给的信息没什么可以帮你的，尝试自己定位问题，比如` rm -rf node_modules && npm i `重装依赖确保版本最新，比如打印出你自己的webpack配置，看看svg-sprite-loader配置是否正确

如果还有问题，新开issue我来处理

**Comment by Aibokalv** [comment]
@paranoidjk  感谢解答  我贴一下我的.roadhogrc.js  不知道这样是否足够
`// npm i antd-mobile -S
const path = require('path');
import pxtorem from 'postcss-pxtorem';
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
  path.resolve(__dirname, './src/asserts/svg'), // 业务代码本地私有 svg 存放目录
];
console.log(svgSpriteDirs)
export default {
  "svgSpriteLoaderDirs": svgSpriteDirs,
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "theme": "./src/theme.js",
  "autoprefixer": null,
  "extraBabelPlugins": [
    "transform-runtime", ["import", { "libraryName": "antd-mobile", "style": true }]
  ],
 "proxy": {
  "/api": {
    "target": "http://meeting.clzg.cn",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "/znhw/Api/" }
  }
},
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100 * (1080 / 750),
          propWhiteList: [],
        }),
      ],
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100 * (1080 / 750),
          propWhiteList: [],
        }),
      ],
    }
  }
}
`

**Comment by Aibokalv** [comment]
@paranoidjk 感谢解答 我贴一下我的.roadhogrc.js 不知道这样是否足够
```javascript
// npm i antd-mobile -S
const path = require('path');
import pxtorem from 'postcss-pxtorem';
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
  path.resolve(__dirname, './src/asserts/svg'), // 业务代码本地私有 svg 存放目录
];
console.log(svgSpriteDirs)
export default {
  "svgSpriteLoaderDirs": svgSpriteDirs,
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "theme": "./src/theme.js",
  "autoprefixer": null,
  "extraBabelPlugins": [
    "transform-runtime", ["import", { "libraryName": "antd-mobile", "style": true }]
  ],
 "proxy": {
  "/api": {
    "target": "http://meeting.clzg.cn",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "/znhw/Api/" }
  }
},
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100 * (1080 / 750),
          propWhiteList: [],
        }),
      ],
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 100 * (1080 / 750),
          propWhiteList: [],
        }),
      ],
    }
  }
}

```

**Comment by paranoidjk** [comment]
@Aibokalv 配置文件看起来没问题

**Comment by Aibokalv** [comment]
@paranoidjk  我尝试运行了
```
rm -rf node_modules && cnpm i 
```
会不会是cnpm的原因呢  太奇怪了

**Comment by Aibokalv** [comment]
@paranoidjk   我又尝试运行了npm i roadhog@0.6.0-beta1 -g  然后可以了

**Comment by GreenAppleOne** [comment]
@xoptimal 
 Failed to parse .roadhogrc config.

Unexpected token export

这个错误怎么解决的呢？我把所有的依赖（包括全局的）都删除了，重新安装都不行。
更换 roadhog版本也不行
用dva新建一个项目 只要有.roadhogrc.js 就报这个错误，用.roadhogrc 是没问题的。真是奇怪了

**Comment by GreenAppleOne** [comment]
@sorrycc   这个错误跟什么有关系呢？
