### ISSUE TITLE
dva g model 生成文件的缓存问题

### ISSUE THREAD

**Issue by adam1985** [sorrycc/roadhog#149]
使用dva g model 生成文件，后来对model重命名，服务重启之后报错，提示之前文件没找到，能通过什么方式删除缓存吗？

Failed to compile.

Error in ./src/index.js
Module not found: ./models/users 

 @ ./src/index.js 24:10-35 66:42-67 67:4-74:6 70:18-43 92:44-69 93:4-100:6 96:18-43 118:44-69 119:4-126:6 122:18-43

**Comment by Kaijun** [comment]
在 ./src/index.js 里把 model 改为同样的名字。。
