### ISSUE TITLE
关于配置outputPath后开发和生产环节差异

### ISSUE THREAD

**Issue by programmer-yang** [sorrycc/roadhog#151]
云谦大哥好，我在使用dva的时候遇到了按需加载的模块js无法加载的问题，然后我修改了我的配置。
```javascript
{
  "entry": "src/index.js",
  "publicPath": "modules/",
  "extraBabelPlugins": [
    "transform-runtime",
    ["import", { "libraryName": "antd", "style": "css" }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ],
      "outputPath": "./dist/modules/"
    },
    "production": {
      "outputPath": "./dist/modules/"
    }
  }
}
```
然后我修改了`public/index.html`里的`<link rel="stylesheet" href="modules/index.css" />` `<script src="modules/index.js"></script>`
这个配置下`npm run build`后我的代码都能正常运行。但`outputPath`配置在开发环境下无效，`index.js index.css`都只能从根目录上加载，这种情况下就是我每次编译上线都得修改一次index.html,然后开发的时候又的修改一次～
请问这种情况下我应该如何修改我的配置？

**Comment by sorrycc** [comment]
publicPath 也要配的。

**Comment by programmer-yang** [comment]
@sorrycc 
`publicPath `我已经配置了，我上边儿的配置里第三行。
配置`publicPath `是为了让我index.js里加载其它js的时候带上路径，但打包的时候并不会按`publicPath `的路径打包，所以我加了`outputPath `配置，但这个`outputPath `配置会导致我所有的js都打包进去，这样我的`index.html`里用`index.js index.css`的时候就加上`outputPath`配置的路径，但这样又会导致我`npm start`开发的时候无法正常获取`index.js index.css`。这是我目前的问题

**Comment by Dirmond** [comment]
我也存在同样的问题，请问作者该怎么解决这个问题

**Comment by sorrycc** [comment]
试着理解下 outputPath 和 publicPath 的用途，就不会有路径上的问题了。

**Comment by programmer-yang** [comment]
谢谢云谦大哥，我去仔细看看文档去

**Comment by zywcode** [comment]
@programmer-yang 问题解决了吗？同样的问题。求解决办法。

**Comment by programmer-yang** [comment]
@zywcode 
> sorrycc： 试着理解下 outputPath 和 publicPath 的用途，就不会有路径上的问题了。

最新版本配置`publicPath `，然后编译，`index.html`里的引用应该都是全路径了吧，还有路径问题吗？
