### ISSUE TITLE
文件后缀jsx 的问题

### ISSUE THREAD

**Issue by alexsunxl** [sorrycc/roadhog#152]
在使用默认配置的情况下

我在.roadhogrc文件中把入口文件改为 index.jsx 这样是无效的
```
{
  entry: "src/index.jsx"
  ...
}
```

但是我把其他文件，比如router， 后缀改成jsx，这样是有效的。
现在我是像把所有文件后缀都改成jsx 应该怎么设置？

**Comment by sorrycc** [comment]
`./src/index.jsx`

**Comment by alexsunxl** [comment]
可是我写 `src/index.js` 是支持的
