### ISSUE TITLE
开启自动 eslint 功能

### ISSUE THREAD

**Issue by Kaijun** [sorrycc/roadhog#155]
目前跑 lint 只能手动 `npm run lint`, 无法做到每次编译是跑。
希望可以加在默认配置的 loader 里

**Comment by paranoidjk** [comment]
一般最佳实践不是每次编译都跑，而是这样

- pre-commit 的时候跑lint, 参考 https://github.com/react-component/slider/blob/master/package.json#L64
- ci 跑lint， 参考 https://github.com/react-component/slider/blob/master/.travis.yml#L31

**Comment by paranoidjk** [comment]
btw, pre-commit时候跑lint可能比较影响开发体验，我们的实践中切换到了 `stage-lint`, 参考https://github.com/ant-design/ant-design/pull/5014

**Comment by Kaijun** [comment]
@paranoidjk 感谢解答。这个`lint-staged`好棒！
