### ISSUE TITLE
roadhog build 后 proxy没作用了

### ISSUE THREAD

**Issue by liyanru1** [sorrycc/roadhog#157]
@sorrycc 
roadhog build 后 proxy 不见了 这个要怎么处理

"proxy": {
    "/api": {
      "target": "http://testboss.op.my7v.com/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    },
  },
api请求没有用代理
http://127.0.0.1:8080/api/upgrade/deviceTypeController/getAllDeviceType

**Comment by paranoidjk** [comment]
build 是打 js/css 的bundle用于发布

proxy只是在开发阶段对dev server生效

请自己了解下webpack 和 webpack-dev-server的基本知识

**Comment by internet5** [comment]
那应该怎么做才能打包后用到代理

**Comment by LeezQ** [comment]
@internet5 在nginx那边做代理。

**Comment by DiroKate** [comment]
@LeezQ 有没有相关的配置说明呢？

**Comment by x1nGoo** [comment]
@liyanru1 你好，请问后来怎么解决？
