### ISSUE TITLE
dva react-router去除url中的_k参数，既然没生效

### ISSUE THREAD

**Issue by adam1985** [sorrycc/roadhog#158]
import React from 'react';
import { browserHistory, useRouterHistory, hashHistory, Router, Route, IndexRoute, Link } from 'dva/router';
import { createHashHistory } from 'dva/node_modules/history'
import { connect } from 'dva';
import App from './routes/App';
import IndexPage from './routes/IndexPage';

const history = useRouterHistory(createHashHistory)({ queryKey: false })

function RouterConfig() {
  return (
    <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={IndexPage} />
        </Route>
    </Router>
  );
}

export default RouterConfig

**Comment by sorrycc** [comment]
hash 路由的方式不要去 `_k`，会有各种奇怪的问题的。

**Comment by adam1985** [comment]
browserHistory路由的方式，怎么去掉？

**Comment by sorrycc** [comment]
browserHistory 没有 _k 参数的。

**Comment by adam1985** [comment]
页面第一次进入或刷新会有_k参数，http://localhost:2579/list#/?_k=ddf6xg

**Comment by sorrycc** [comment]
这是 hashHistory

**Comment by adam1985** [comment]
不是，已经开启了browserHistory
![20170306172149](https://cloud.githubusercontent.com/assets/2756802/23603778/6e20672e-0291-11e7-96e9-695515205c84.jpg)

**Comment by ShaneKing** [comment]
@adam1985 https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md
import { browserHistory } from 'dva/router';
const app = dva({
  history: browserHistory,
});
