### ISSUE TITLE
打包后文件太大怎么办

### ISSUE THREAD

**Issue by liuxingling** [sorrycc/roadhog#159]
![image](https://cloud.githubusercontent.com/assets/26077947/23595214/1ce5e874-025b-11e7-9b26-05a7d2da0023.png)
这是我的roadhog文件，打包出来后的文件平均八百多kb，太大了啊，求指教

![image](https://cloud.githubusercontent.com/assets/26077947/23595224/3338f4a4-025b-11e7-8dda-388ba7ade5fb.png)

**Comment by mayacger** [comment]
同求，我也正在寻找怎么解决这个问题？

**Comment by yyyyy210** [comment]
+1

**Comment by chenfengyanyu** [comment]
＋1

**Comment by yeelone** [comment]
对啊，编译时终端显示 文件只有300多K ，我心想可以接受 。但实际查看文件大小时却发现是1M多，这是怎么回事？请问你解决了吗？

**Comment by codering** [comment]
用roadhog build --analyze 看下每个模块都依赖哪些，然后再做调整。

**Comment by codering** [comment]
@yeelone  #405

**Comment by varrant** [comment]
me, too .how to solve？

**Comment by abattle** [comment]
同求
