### ISSUE TITLE
roadhog 多页面实现

### ISSUE THREAD

**Issue by iceshu** [sorrycc/roadhog#161]
有没有一些demo，因为我配置了多页
`  entry: 'src/pages/*.js',`
`multipage: true,`
然后npm start 之后默认打开8000的端口不知道怎么访问我写的页面
@paranoidjk 
有demo么

**Comment by paranoidjk** [comment]
multipage 跟你访问没关系的把，只是打包抽离common而已，你怎么访问是看你的 output 配置

**Comment by iceshu** [comment]
是这样的 在src跟目录会有个index.js文件嘛,默认npm statr 之后访问的就是可以访问的有内容 但是我配置了entry为src/pages/*.js 之后 那我npm start 打开8000端口什么东西都没有 我想访问我src/pages/index.js 所展示的内容怎么弄？

**Comment by paranoidjk** [comment]
要访问引用了这个src/pages/index.js 的html文件所在路径

建议学习下webpack基础知识，或者找个demo理解一下

**Comment by iceshu** [comment]
问题解决了 还是要说下的 配置好的entery要跟跟实体文件配对好 然后新建几个html文件在public 下引用的脚本直接是当pages 下的 就好了

**Comment by ShadowRambler** [comment]
@iceshu 求个路径截图，半天不知道怎么对上那些html文件

**Comment by iceshu** [comment]
![wechatimg6](https://cloud.githubusercontent.com/assets/6309056/24736531/1a4edd96-1abb-11e7-8a6f-66e132ff3f7b.jpeg)

你看看先 @ShadowRambler

**Comment by LarchLiu** [comment]
@iceshu  能说的再详细点吗？我配置了index,和about，但是只能访问domain.com不能访问domain.com/about

**Comment by ShadowRambler** [comment]
@iceshu 我是这么写的，打包可用，但是开发模式下并没有把html作为入口的模版页
