### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by fanerge** [sorrycc/roadhog#162]
怎么实现在src中某些东西，不打包？我们需要借助iframe（本地src）对地图进行操作。

**Comment by sorrycc** [comment]
把不需要打包的放到外面的 [public](https://github.com/sorrycc/roadhog#使用-public-目录) 目录下。

**Comment by fanerge** [comment]
重dva官网上查到了，已解决。谢谢

**Comment by SynChron1zed** [comment]
@sorrycc 放在public 目录下的json  本地请求为什么获取不到
