### ISSUE TITLE
关于multipage公共文件

### ISSUE THREAD

**Issue by programmer-yang** [sorrycc/roadhog#164]
抱歉又来提问了。
请问当我`multipage`配置为`true`后如何指定需要提取出来的公共文件。

我原来自己写配置的时候`entry`里可以传递对象并通过定义数组来指定那些模块抽取到公共文件中。

**Comment by sorrycc** [comment]
抱歉，不能定制，目前是写死的。

**Comment by programmer-yang** [comment]
@sorrycc 谢谢云哥，我知道怎么处理了

**Comment by JoneXiong** [comment]
@programmer-yang 怎么处理的？
