### ISSUE TITLE
roadhogrc.mock最佳实践

### ISSUE THREAD

**Issue by 102010cncger** [sorrycc/roadhog#167]
在做一个有30多个页面的demo,模拟数据比较多,能否给一个多文件mock数据的roadhogrc.mock的最佳实践,谢谢了!

另外内容单独放在roadhogrc.mock.js中是有效的,一旦通过类似require('./mock/users')的方式引用后就没有效果了.是不是不是这么用的,谢谢!

**Comment by xiandongw** [comment]
遇到同样问题 mock只能放在roadhogrc.mock.js.

**Comment by sorrycc** [comment]
`roadhogrc.mock.js` 不能 require 其他文件吗?

**Comment by xiandongw** [comment]
没有sample可以follow。 照着dva的sample（antd-admin 不是用roadhog）看起来不行

**Comment by forever4313** [comment]
有没有帮忙写一个demo之类的，新手，想从dva原先使用的mockjs 转到现在roadhog来，原先的报错信息实在是不忍直视。

**Comment by 305758409** [comment]
@xiandongw antd-admin的4.1dev分支已经在用roadhog了，可以参考，不过好像roadhog@0.6.0-beta.3还是没有解决这个问题 #86 ，持续关注

**Comment by zuiidea** [comment]
@102010cncger  https://github.com/zuiidea/antd-admin

**Comment by sorrycc** [comment]
参考： https://github.com/zuiidea/antd-admin/blob/master/.roadhogrc.mock.js

**Comment by atonesapple** [comment]
roadhogrc.mock.js文件主要是用来做什么的，有大神解释一下么，谢谢！！！
