### ISSUE TITLE
为什么无法覆盖ant组件的样式 

### ISSUE THREAD

**Issue by changyijie** [sorrycc/roadhog#176]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
这是配置，样式的优先级在哪配置
```
{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "less":"true",
  "theme": {
    "@primary-color": "#108EE9",
    "@link-color": "#108EE9",
    "@border-radius-base": "2px",
    "@font-size-base": "14px",
    "@line-height-base": "1.2"
  },
  "autoprefixer": null,
  "extraBabelPlugins": [
    "transform-runtime",
    ["import", { "libraryName": "antd", "style": true }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  }
}

```

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
配的是 less 变量，不需要优先级吧。

**Comment by yejintao** [comment]
我也遇到了这个问题，我在部分less文件修改了某组建的样式，发现最终还是被antd的样式覆盖。

貌似antd的样式放在最后？

**Comment by wxa1048989080** [comment]
同问

**Comment by acwong00** [comment]
同样遇到这问题，打包之后没有覆盖ant组件的样式

**Comment by wanghaooo** [comment]
同遇到这个问题，覆盖不了antd样式，在节点上添加类也改不动

**Comment by wanghaooo** [comment]
问题解决了，大家可以试下将  "disableCSSModules"设置为true
