### ISSUE TITLE
可以做到js文件热更新吗

### ISSUE THREAD

**Issue by MinJieLiu** [sorrycc/roadhog#182]
> 配上 babel-plugin-dva-hmr 即可实现 routes 和 components 以及相关 CSS 修改的热更新，其他修改会自动刷新页面。

我想问一下，可以做到修改相关路由的 js 文件实现热替换吗，或者有没有做此类热替换的打算？

抱歉，我是个强迫症😅

**Comment by sorrycc** [comment]
路由，components, model, service, css 都可以热更新的。

**Comment by qq98424ccxy** [comment]
请问现在有解决了嘛，刚交接的一个dva项目也遇到了同样的问题，

**Comment by qq98424ccxy** [comment]
![image](https://user-images.githubusercontent.com/45843228/116073242-b9712b80-a6c2-11eb-9b04-bf94ea07a3e2.png)
