### ISSUE TITLE
roadhog build动态路由项目， 上线有路径错误， 比如打包到dist目录， 上线后就放domain下面的dist, 应用跑不起来。 如果放domain根目录， 则能跑起来。

### ISSUE THREAD

**Issue by walkerqiao** [sorrycc/roadhog#187]
#### Environment(required) | 环境（必填）

- roadhog version（0.5.2）
- Nodejs and Npm version（Nodejs 6.9.1 和 Npm 3.10.8）
- Operating environment (e.g. OS name) and its version（macbook dev, centos production）:

代码位于： https://github.com/walkerqiao/dva-antd-demos

**Comment by zhangjx** [comment]
.roadhogrc 里的publicPath 配置去掉， 再试一试？

**Comment by walkerqiao** [comment]
@zhangjx 情况是这样的， 例如我开发几个不同的项目app1, app2, 希望上线后，分别访问://domain.com/app1, ://domain.com/app2等来访问。 部署上线后， 配置publicPath, 并正确修改入口index.html中资源位置， 貌似可以了。 但存在一个问题， 访问/app1, /app2都没有问题， 但是两个应用中的子路由会发生冲突： app1路由有/, /about-me, /test, app2中有/, /about-me, /test2, 那么两个应用都部署后， 就出现/app1, /app2, /about-me, /test, /test2这几个访问路径。

**Comment by walkerqiao** [comment]
这个不是什么bug, 属于router配置问题， 我还在研究，暂时没有找到很好的解决方案， 貌似新版的react-router提供的BrowserRouter有个basename的属性，貌似可解决，暂未尝试https://reacttraining.com/react-router/web/api/BrowserRouter

**Comment by zhangjx** [comment]
最近我也遇到类似的问题，目前是通过 react-router 提供的basename 解决的，但是由于 dva 里依赖的 react-router 版本是 `^2.8.1` 无法使用最新版的 API，现在解决方案如下：

1. 安装 history，保持和 react-router@2.8.1 依赖的版本一致

```bash
$ npm install history@2.1.2
```

2. 修改 入口文件 `src/index.js`，自定义含有basename 的 history

```js
import dva from 'dva';
import { useRouterHistory } from 'dva/router';
import createBrowserHistory from 'history/lib/createBrowserHistory';

const history = useRouterHistory(createBrowserHistory)({ basename: '/admin' });

// 1. Initialize
const app = dva({ history });
```

3. 静态的入口文件 `public/index.html` 里的静态资源引用地址 保持不变

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin</title>
  <link rel="stylesheet" href="index.css" />
  <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
</head>
<body>

<div id="root"></div>

<script src="index.js"></script>

</body>
</html>
```
4. router 配置保持不变，不需要加入 `/admin` 相关的路径配置

5. `.roadhogrc` 指定 publicPath

```
{
  "entry": "src/index.js",
  "publicPath": "/admin/",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    }
  }
}
```

6. nginx 配置

```
server {
    listen 80;
    server_name hostname;
    root /path/to/project/dist;
    index index.html index.htm;

   location ^~ /admin {
      alias /path/to/project/dist;
      try_files $uri ./$uri /index.html;
    }
}
```

7. 访问测试，浏览器打开 http://hostname/admin 就是你的应用了

ps: 以上是基于 browerHistory 的解决方案，如果是 hashHistory 配置就简单太多了

**Comment by walkerqiao** [comment]
@zhangjx 非常感谢zhangjx, 感谢这么及时的答疑解惑， 非常期待和你们一起学习探讨。

**Comment by varrant** [comment]
index.js 文件中 把browerHistory 改成 hashHistory即可解决打包问题

```javascript
import dva from 'dva';
import { hashHistory } from 'dva/router';
import createLoading from 'dva-loading';
import { message } from 'antd';
import './index.html';


const ERROR_MSG_DURATION = 3; // 3 秒

// 1. Initialize
const app = dva({
  history: hashHistory,
  onError(e) {
    message.error(e.message, ERROR_MSG_DURATION);
  },
});

// 2. Plugins
app.use(createLoading());

// 3. Model
// Moved to router.js
// app.model(require('./models/loanee'));

// 4. Router
app.router(require('./router'));

// 5. Start
app.start('#root');
```

**Comment by wuyunjiang** [comment]
@zhangjx 您好，如果

> 静态的入口文件 public/index.html 里的静态资源引用地址 保持不变

请问如果有多级路由，比如`://domain.com/app1/router1/router1_1`，此时刷新页面，请求的`index.js`和`index.css`就是
`://domain.com/app1/router1/index.js`
`://domain.com/app1/router1/index.css`
这样肯定是不对的，请问这种是怎么解决的，非常感谢
