### ISSUE TITLE
请问Stylus要如何配置?

### ISSUE THREAD

**Issue by ronankim** [sorrycc/roadhog#188]
需要我再创建一个webpack.config.js指定一下*.styl的loader吗

**Comment by sorrycc** [comment]
是的。

**Comment by laughing-pic-zhu** [comment]
![default](https://user-images.githubusercontent.com/11971232/28010018-18e89d1e-6590-11e7-9bc7-02f73b4ae1a4.png)
hi,我在这写了之后，业务代码引入无效果。
![default](https://user-images.githubusercontent.com/11971232/28010071-4341f60a-6590-11e7-98ab-99428a16857c.png)

**Comment by WangYang-Rex** [comment]
同问
