### ISSUE TITLE
whether roadhog build can support auto increment of build version number

### ISSUE THREAD

**Issue by llqgit** [sorrycc/roadhog#194]
We have a requirement. That when we build a new version. And put it online. The user want to know whether the project is upgrade.

Now, before build. We update the version number manually. If there is A feature support will be better.

And I checked the issues a lot. And not found something I need.

**Comment by sorrycc** [comment]
with hash affix?

**Comment by llqgit** [comment]
Not hash, just build version Natural number increment. Like 1,2,...,99,100
When I run build. It will auto increment the build number. And write the number in some place that the project can read.
And then we can set the project website **Title** or something like:
>XX Management System v.**123456**

we can see the build times and website whether upgraded.

**Comment by sorrycc** [comment]
Try to specify outputPath in `.roadhogrc`:

```
{
  "outputPath": "./dist/$npm_package_version"
}
```

Then after run `roadhog build`, you will get a versioned directory, copy all files in the `dist` directory to cdn.

**Comment by llqgit** [comment]
Thx a lot. I tried but not what I want. orz

**Comment by mdluo** [comment]
@llqgit 
Related Workaround: https://github.com/sorrycc/roadhog/issues/69#issuecomment-298928686
