### ISSUE TITLE
roadhog build时JavaScript heap out of memory

### ISSUE THREAD

**Issue by riverslob** [sorrycc/roadhog#197]
当模块过多时，用 roadhog build执行时会提示js内存溢出错误。加上--max_old_space_size=4096参数也无法生效。roadhog有提供参数传递给node的功能吗？
下面是内存溢出错误：
<--- Last few GCs --->

[12863:0x102801c00]  1946581 ms: Mark-sweep 1438.7 (1646.8) -> 1438.7 (1646.8) MB, 1300.5 / 0.0 ms  (+ 1.3 ms in 3 steps since start of marking, biggest step 1.3 ms) allocation failure GC in old space requested
[12863:0x102801c00]  1947959 ms: Mark-sweep 1438.7 (1646.8) -> 1438.7 (1645.8) MB, 1250.1 / 0.0 ms  (+ 0.9 ms in 3 steps since start of marking, biggest step 0.8 ms) last resort gc 
[12863:0x102801c00]  1949221 ms: Mark-sweep 1438.7 (1645.8) -> 1438.6 (1645.8) MB, 1261.6 / 0.0 ms  last resort gc 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1d2aad9c0d39 <JS Object>
    2: optimize [0x1d2aad904311 <undefined>:5387] [pc=0x3954d055537c](this=0x1decdee5d189 <an AST_Binary with map 0x2d3872c83e49>,compressor=0xc5a16eb1f99 <a Compressor with map 0x2987fd735639>)
    3: before [0x1d2aad904311 <undefined>:5370] [pc=0x3954d177be56](this=0xc5a16eb1f99 <a Compressor with map 0x2987fd735639>,node=0x1decdee5d189 <an AST_Binary with map 0x2d3872c83e49>,descend=0x3aeff4...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/Cellar/node/7.3.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/Cellar/node/7.3.0/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/Cellar/node/7.3.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/Cellar/node/7.3.0/bin/node]
 5: v8::internal::Factory::NewCodeRaw(int, bool) [/usr/local/Cellar/node/7.3.0/bin/node]
 6: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [/usr/local/Cellar/node/7.3.0/bin/node]
 7: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/7.3.0/bin/node]
 8: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/7.3.0/bin/node]
 9: v8::internal::(anonymous namespace)::GenerateUnoptimizedCode(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/7.3.0/bin/node]
10: v8::internal::(anonymous namespace)::CompileUnoptimizedCode(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/7.3.0/bin/node]
11: v8::internal::(anonymous namespace)::GetUnoptimizedCode(v8::internal::CompilationInfo*) [/usr/local/Cellar/node/7.3.0/bin/node]
12: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/local/Cellar/node/7.3.0/bin/node]
13: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/Cellar/node/7.3.0/bin/node]

**Comment by riverslob** [comment]
目前以这种方式暂时解决问题：
node --max_old_space_size=4096 node_modules/roadhog/lib/build.js

**Comment by sorrycc** [comment]
换 node@6.x 试试。

**Comment by riverslob** [comment]
node 7.8.0也是有这个问题

**Comment by sorrycc** [comment]
试试 node@6.x，不是 7.x

**Comment by zachshelter** [comment]
同样也有这个问题， 我从6.X转到7.x之后好了几天，今天又不行了。。

**Comment by riverslob** [comment]
node@6.x也是这个问题，觉得解决办法还是调整内存。

**Comment by MelonYii** [comment]
node v6.9.4 同样碰到这个问题了

**Comment by LDD123** [comment]
@MelonYii 你怎么解决的

**Comment by XuXiang1** [comment]
@sorrycc 大哥，npm start 内存溢出，怎么解，我的组件比较多

**Comment by linlinNB** [comment]
@sorrycc 大佬，我这边也出现了类似的问题，已经分配了8G内存，还是不行，有没有什么根治的办法呢？很影响每次的进度

**Comment by sorrycc** [comment]
少打包点东西，比如用用 webpack 的 externals 功能。

**Comment by LDD123** [comment]
可以直接修改roadhog的配置文件，E:\BZCWJR\frontEnd\node_modules\_roadhog@0.5.4@roadhog\src\config\webpack.config.prod.js
将sourceMap改为false,这样打包时候就不会生成树进行比较了，就能省下一大笔空间，8g绝对够用了

![image](https://user-images.githubusercontent.com/11335860/37141945-9a301c98-22f1-11e8-8420-59c2766c5ce5.png)

**Comment by linlinNB** [comment]
@sorrycc @LDD123 谢谢大佬的帮助，确实可以解决问题，感谢

**Comment by XuXiang1** [comment]
感谢感谢

**Comment by syaivin** [comment]
@XuXiang1  请教，您 npm start 内存溢出的问题是怎么解决的？

**Comment by sbyps** [comment]
本地npm start没有报错，npm run build内存溢出了，现在用--max_old_space_size=4096能够build出来，还能有别的方法么

**Comment by syaivin** [comment]
@sbyps --max_old_space_size=4096 你回那个地方啊？我加的没有用，我用的是上面的 将sourceMap改为false 这个解决打包内存溢出问题的，现在就是编译的时候内存溢出了；折腾好久了~

**Comment by sbyps** [comment]
@syaivin 现在roadhog中生产环境prod.js里面没有sourceMap啊，我npm start是正常的，就是打包时候溢出了

**Comment by Renderz** [comment]
同出现问题, 删了node_models用yarn重新安装依赖后解决...
只在win7下出现了这个问题, win10和mac都没有出现

**Comment by tudou330121** [comment]
遇到了同样的问题，按照上面说的方法没有解决啊
