### ISSUE TITLE
win8系统下cmd安装roadhog时报warn错误,然后start项目出现err错误,无法启动

### ISSUE THREAD

**Issue by Achei** [sorrycc/roadhog#199]
![qq 20170331111325](https://cloud.githubusercontent.com/assets/13568342/24534937/900bb124-1603-11e7-8884-498839e646eb.png)
我是win8系统,在cmd npm i roadhog -g时,报错下面错误:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ro
adhog\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

然后在npm start时 出现了上面图片的问题 有哪位大神帮忙看下 解决下?

**Comment by Kate605690919** [comment]
我想问问你是怎么解决这个的
