### ISSUE TITLE
考虑集成 dll 功能用以提升调试效率

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#2]

**Comment by sorrycc** [comment]
例子：https://github.com/mxstbr/react-boilerplate

**Comment by sorrycc** [comment]
以 dva-example-user-dashboard 为例，用上 dll 之后能快 2-3 秒。

- 用 dll 之前，10s
- 用 dll 之后，7-8s

**Comment by sorrycc** [comment]
参考：

- https://gist.github.com/robertknight/058a194f45e77ff95fcd
- https://robertknight.github.io/posts/webpack-dll-plugins/
- http://engineering.invisionapp.com/post/optimizing-webpack/
- https://www.zhihu.com/question/31352596

**Comment by sorrycc** [comment]
感觉 antd 由于引入了 babel-plugin-import，所以 dll 无效，待排查。

**Comment by sorrycc** [comment]
试了下一个内部的复杂项目，启动时间从 44s -> 29s 。

**Comment by sorrycc** [comment]
roadhog 的 dllPlugin 实现：

1. 默认关闭
2. 通过 `.roadhogrc` 的 `dllPlugin` 配置开启，可以配 `exclude` 和 `include` 的包
3. 提供 `roadhog buildDll` 命令手动打 dll bundle
4. 开启 dllPlugin 后，`roadhog server` 时检到没有 `manifest.json`，提醒执行 `roadhog buildDll`
5. 然后用户还需手动在调试的 html 里引入 `vendor.dll.js` (后面可以考虑用 [HtmlWebpackPlugin](https://github.com/jantimon/html-webpack-plugin) 生成

**Comment by liuhuapiaoyuan** [comment]
考虑什么时候更新到npm呢

**Comment by liuhuapiaoyuan** [comment]
一直在关注这事~~就是最近项目太赶了，好像提pr

**Comment by sorrycc** [comment]
下周吧，这周后面没时间搞这个了。

**Comment by sorrycc** [comment]
<img width="484" alt="screen shot 2017-05-05 at 2 57 23 pm" src="https://cloud.githubusercontent.com/assets/35128/25737437/6b8ca52a-31aa-11e7-9885-11494374415b.png">
<img width="465" alt="screen shot 2017-05-05 at 2 59 49 pm" src="https://cloud.githubusercontent.com/assets/35128/25737439/6ba03d10-31aa-11e7-85b9-1ea3b7c346aa.png">

以 https://github.com/dvajs/dva-example-user-dashboard 为例，devtool 为 sourcemap 的情况下。未启用 dll 时启动时间 13.2s，修改代码后热编译 2.5s；启用 dll 之后，启动时间 8s，修改代码后热编译 0.7s 。

**Comment by weishijun14** [comment]
求解 `exclude` 与 `include` 的作用。。。
