### ISSUE TITLE
我没使用.roadhogrc.js，是用的.roadhogrc，如何配置antd-mobile 里面对svgSpriteLoaderDirs图标的支持呢？

### ISSUE THREAD

**Issue by liangxp** [sorrycc/roadhog#202]
我没使用.roadhogrc.js，是用的.roadhogrc，如何配置antd-mobile 里面对svgSpriteLoaderDirs图标的支持呢？搜索所有的issues都是说用.roadhogrc.js，是否可以在.roadhogrc里面配置呢？应该是如何配置？是否有实例？求解答，谢谢

**Comment by paranoidjk** [comment]
提问题或者需求请说明你的背景。
有什么特殊原因一定要用 `.roadhogrc` 而不是 `.roadhogrc.js` ? 前者里面并不能写 js 代码，你只能吧路径数据写成字符串。

https://github.com/ant-design/antd-mobile-samples/blob/master/antm-roadhog/.roadhogrc.js#L11

**Comment by junmaqiang** [comment]
官方文档里记得有说明, 要配置svg必须用.roadhogrc.js

**Comment by zyx4986** [comment]
官方有个demo，现成的代码
