### ISSUE TITLE
roadhog build打包后svg无法正常显示

### ISSUE THREAD

**Issue by ufohjl** [sorrycc/roadhog#203]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）^0.6.0-beta1
- Nodejs and Npm version（Nodejs 和 Npm 版本）v7.5.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: OS X Yosemite 10.10.5

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
roadhog build

#### What do you expected?（预期的正常效果）
希望svg正常显示

#### What happen?（发生了何种非正常现象）
开发模式下svg正常显示, 打包后放在nginx下访问不显示

**Comment by ufohjl** [comment]
http://127.0.0.1:8081/static/index2-mizi.8c6b9ec1.svg 单独访问路径可以

**Comment by ufohjl** [comment]
<img width="613" alt="jiepin1" src="https://cloud.githubusercontent.com/assets/3119672/24707538/8f424fc2-1a46-11e7-8edf-b6981a4acdeb.png">

**Comment by ufohjl** [comment]
<img width="434" alt="jienpin2" src="https://cloud.githubusercontent.com/assets/3119672/24707591/d088afd0-1a46-11e7-97b4-40014912b904.png">

**Comment by ufohjl** [comment]
以上是chrome查看DOM 以及 打包后的目录截图

**Comment by ufohjl** [comment]
```
import path from 'path';
const pxtorem = require('postcss-pxtorem');

const svgSpriteDirs = [
    require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
    path.resolve(__dirname, 'src/assets/svg'),  // 业务代码本地私有 svg 存放目录
];

export default {
    svgSpriteLoaderDirs: svgSpriteDirs,
    entry: "src/index.js",
    publicPath: "/",
    theme: "./theme.config.js",
    env: {
        development: {
            extraBabelPlugins: [
                'transform-runtime',
                ['import', { 'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true }]
            ],
            extraPostCSSPlugins: [
                pxtorem({
                    rootValue: 100,
                    propWhiteList: [],
                }),
            ],
        },
        production: {
            extraBabelPlugins: [
                'transform-runtime',
                ['import', { 'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true }]
            ],
            extraPostCSSPlugins: [
                pxtorem({
                    rootValue: 100,
                    propWhiteList: [],
                }),
            ],
        }
    }

}
```
roadhog配置

**Comment by ufohjl** [comment]
和想象的不一样，按我的理解svg sprite不应该是打成一个大的sprite然后通过#去访问吗？不知道我理解的对不对

**Comment by paranoidjk** [comment]
> 和想象的不一样，按我的理解svg sprite不应该是打成一个大的sprite然后通过#去访问吗？不知道我理解的对不对。 

你理解的对。

> roadhog server正常，roadhog build就GG了。

报告bug请描述清楚，我没理解你说的 build 之后到底有什么问题。

**Comment by ufohjl** [comment]
@paranoidjk 就是SVG不显示

**Comment by paranoidjk** [comment]
官方demo 跑下有没有问题？

https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog

**Comment by ufohjl** [comment]
<img width="1000" alt="2017-04-06 10 52 22" src="https://cloud.githubusercontent.com/assets/3119672/24735796/3682cd14-1ab7-11e7-869e-f2b09cd909af.png">

**Comment by ufohjl** [comment]
好了，因为我之前本地全局装的roadhog版本还是老的，打包的时候是用的roadhog build所以就导致了svg sprite没有打进去，改用npm run build就好了。我的锅~~~
```
xuedingedemao:IdeaProjects hjl$ roadhog -v
0.5.3
```
