### ISSUE TITLE
【question】roadhog如何配置build后的css和js名字规则

### ISSUE THREAD

**Issue by ufohjl** [sorrycc/roadhog#204]
css和js都要放到cdn上去想打包为 name.hash.js 以及name.hash.css，请问下用roadhog应该如何配置

**Comment by valleykid** [comment]
配置项中暂不支持配置名字规则，如果需求较常用，可在新版本中支持

**Comment by ufohjl** [comment]
@valleykid 感谢。 这种在生产环境还是很有必要的~

**Comment by mdluo** [comment]
https://github.com/sorrycc/roadhog/issues/69#issuecomment-298928686

**Comment by yaderick** [comment]
目前依然不支持嘛？
