### ISSUE TITLE
放在assets里面的本地json，为什么请求不到！

### ISSUE THREAD

**Issue by SynChron1zed** [sorrycc/roadhog#205]
#### Environment(required) | 环境（必填）
antd chrome 
- roadhog version（roadhog版本）^0.5.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:
mac
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/24748045/07cca4c4-1af1-11e7-86bf-89fa91ef0c70.png)

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/24748911/d0cd9fc0-1af3-11e7-9e7b-7fc5abd1f549.png)

**Comment by SynChron1zed** [comment]
看了文档说可以放在public下 但是我npm start的时候还是请求不到

**Comment by SynChron1zed** [comment]
没人了么？

**Comment by valleykid** [comment]
放在public下，你访问的url是什么？路径里不用带public的

**Comment by SynChron1zed** [comment]
@valleykid  我换了个方式 已经解决了

**Comment by yqwoe** [comment]
@SynChron1zed  怎么解决的，求指教

**Comment by SynChron1zed** [comment]
@yqwoe  看楼上的答案
