### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#21]

**Comment by chengs** [comment]
这个现在有么

**Comment by sorrycc** [comment]
没有，放 0.5.0 里做吧，欢迎 PR 。

**Comment by sorrycc** [comment]
优先级不高，往后面放。

**Comment by pvtyuan** [comment]
能在0.6中实现吗？antd和dva都支持typescript了，有这个就更方便了。我尝试改了下webpack配置，但没成功

**Comment by mrxlc02** [comment]
配置以后似乎无效。
test.tsx文件中：
export const num = 123;
index.js中
import { num } from './test.tsx';
num是空值

**Comment by sandwich99** [comment]
版本 0.6-beta2 引入入口文件 index.ts 报错， 代码：
```javascript
import dva from 'dva';

const app = dva();

app.start('#root');
```
![image](https://cloud.githubusercontent.com/assets/1179783/24782600/ccea0c1e-1b79-11e7-98ea-08fbebef7b4c.png)

**Comment by JimmyLv** [comment]
竟然不支持 TypeScript！
