### ISSUE TITLE
How to add json file loader

### ISSUE THREAD

**Issue by dyf102** [sorrycc/roadhog#210]
I did not see any document about how to add the loader module. Can anyone give suggestion? 
Thanks

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/blob/master/README_en-us.md#configuration

> Support configure with webpack.config.js (support ES6), but it's not recommended, since roadhog's major or minor upgrade will cause compatibility problem. View detail on #36

```js
export default function(webpackConfig, env) {
  // do something with webpackConfig
  return webpackConfig;
}
```
