### ISSUE TITLE
自定义环境变量无效？

### ISSUE THREAD

**Issue by liurongqing** [sorrycc/roadhog#213]
REACT_APP_SECRET_CODE=abcdef npm start

在项目中process.env.REACT_APP_SECRET_CODE读不到

是我哪设置不对吗

**Comment by zbobyuan** [comment]
顶，同需要在代码中读取自定义环境变量。

**Comment by yangbin1994** [comment]
需要用配置项define来定义，但是我同样没有读到

**Comment by trexguo** [comment]
define: {
    'process.env': {
      NODE_ENV: process.env.NODE_ENV,
      API_ROOT: xxxxx,
      .....
    },

**Comment by shenggen1987** [comment]
package.json 文件代码如下：
"scripts": {
    "start": "roadhog server",
    "mock": "cross-env NODE_ENV=mock roadhog server",
}
文件  .roadhogrc.js 的写法如下  
const mock = process.env.NODE_ENV || '';

**Comment by sosout** [comment]
我们公司项目使用docker、Jenkins一键打包构建项目，其中测试库，预发库、生产库唯一不同的是接口的url，由于环境变量无法自定义，导致我们无法区分是哪个环境，该使用哪个接口。强烈建议打包环境可以自定义。

**Comment by hezhijun** [comment]
同样需要，现在env只有development和produciton两种，起码要有dev,test,prod三种吧

**Comment by CareyToboo** [comment]
@sosout 相同问题，不同环境接口地址不一样，那里可以配置一下？ 你解决了么？

**Comment by sorrycc** [comment]
在配置文件里读取环境变量，然后用 define 传给代码。

**Comment by flyforfreedom** [comment]
cross-env NODE_ENV=development roadhog build，这样写，到代码里边取process.env.NODE_ENV永远都是“production”。

**Comment by sorrycc** [comment]
NODE_ENV 不能改，是写死的，build 时就是 production。

**Comment by SanPy** [comment]
define中的配置在编译后的代码中是如何获得的啊？
