### ISSUE TITLE
如何关闭热更新

### ISSUE THREAD

**Issue by wssgcg1213** [sorrycc/roadhog#214]
RT, 我在本地希望在另一个 server 里调试，比如是 localhost:3000  

dva 应用会尝试连接 sockjs 并不断刷新页面重连，如何关闭HMR，我已经在 extraBabelPlugin 里把 hmr 去掉了  
![image](https://cloud.githubusercontent.com/assets/3922719/25070532/b9f1eb20-22d3-11e7-979c-cdda621c3846.png)

**Comment by sorrycc** [comment]
抱歉，写死了，关不了。

**Comment by wuzhuzhu** [comment]
这个情况我也遇见了 ，给开发调试带来了很大困难

**Comment by EthianWong** [comment]
+1

**Comment by EthianWong** [comment]
已使用 nginx 反向代理变通解决

**Comment by mengli404** [comment]
@EthianWong 使用 nginx 反向代理变通解决,是如何解决的呀？

**Comment by mengli404** [comment]
SOCKET_SERVER=none 加这个环境变量就可以去除热更新了

**Comment by zhuanglong** [comment]
还不能关闭热加载？

**Comment by Sir0xb** [comment]
页面开发到一半自动更新界面，开发阶段页面内存泄漏非常严重，随随便便上G了。。。

**Comment by rexyanglucky** [comment]
挖坟，老项目碰到这个问题，使用微前端框架，作为子项目加载时，一直尝试连接websocket，不停刷新页面。热更新是在af-webpack中提供的功能，查看源码，有配置来控制热更新 `process.env.SOCKET_SERVER`。
设置为`none`关闭热更新，也可以设置为其它值，默认使用当前页面的 protocol + hostname + pathname。
![image](https://user-images.githubusercontent.com/16067172/144163292-0180999e-0e72-4730-a9cf-8223ddc6c66c.png)
