### ISSUE TITLE
roadhog是否有支持eslint的计划吗

### ISSUE THREAD

**Issue by jindada** [sorrycc/roadhog#215]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by dicklwm** [comment]
已经有支持的了

**Comment by jindada** [comment]
在哪里可以看到相关文档那？ @dicklwm

**Comment by dicklwm** [comment]
用dva-cli创建出来的项目都是有.eslintrc文件的，在.eslintrc里面配置你的eslint就可以了

**Comment by junmaqiang** [comment]
@dicklwm 和楼主同问, roadhog 如何支持 eslint ?
就是不晓得在roadhog下如何配置 eslint 

```
  "scripts": {
    "start": "BROWSER=none roadhog server",
    "build": "roadhog build",
    "esl": "npm run lint -- --fix && npm run roadhog server",
    "lint": "eslint .",
    "test": "mocha ./src/**/*-test.js"
  }
```

上面是我个人的配置,但是好像没有起到作用哈, 我只是照葫芦画瓢 参考你 egg的配置!

**Comment by sorrycc** [comment]
roadhog 没有内置 eslint，在项目目录直接用 eslint 做校验吧。
