### ISSUE TITLE
roadhog也正确的把打包好的js输入到指定目录，但public目录中的文件没有拷贝到指定目录，依然输入到默认的dist目录下

### ISSUE THREAD

**Issue by yiranlee** [sorrycc/roadhog#219]
看了之前的，但是没有给出解决方案呀，我有一堆不需要通过build文件，但是他始终输出在dist目录下，不能到达我在roadhogrc 中配置的路径，改怎么解决呢？

**Comment by zhangjx** [comment]
是不是指定了 outputPath ? 
问题描述如 #111 一致，这是一个 Bug，最新的 0.6.0 Beta 版本修正了这个错误，你可以看看 Bug 如何修复的，在本地 做相应的修改。

**Comment by gafish** [comment]
我也遇到同样的问题，期待官方修复

**Comment by sorrycc** [comment]
0.6.0 已修复。
