### ISSUE TITLE
关于 extraBabelIncludes 的使用问题 

### ISSUE THREAD

**Issue by mimimi1227** [sorrycc/roadhog#220]
- roadhog version 0.7.8
- Nodejs and Npm version node v7.8.0 npm 4.5.0

.roadhogrc 的代码
{
  "entry": "src/index.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ],
      "extraBabelIncludes": [
        {
          "test": "/\.(js|jsx)$/",
          "include": "./",
          "loader": "babel",
        }
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": "css" }]
      ]
    }
  },
  "proxy": {
    "/course": {
      "target": "http://172.24.0.2/",
      "changeOrigin": true
    }
  }
}
然后 出现报错 
Error in ./roadhogrc
Syntax error: Unexpected token '.' , (26:22)

          "test": "/\.(js|jsx)$/",

问下 extraBabelIncludes 使用的 正确姿势 是什么呢 有示例代码吗

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/tree/master/test/fixtures/build/extraBabelIncludes

**Comment by mimimi1227** [comment]
@sorrycc  谢谢！

**Comment by 946629031** [comment]
> https://github.com/sorrycc/roadhog/tree/master/test/fixtures/build/extraBabelIncludes

链接 404了，能复制以下 答案到这里来吗？
