### ISSUE TITLE
roadhog build 如何启用sourcemap？

### ISSUE THREAD

**Issue by skyblue** [sorrycc/roadhog#222]
development下是有的

**Comment by zhangshihuann** [comment]
顶一下 同问

**Comment by skyblue** [comment]
抱歉，默认是有的， 是我配置的问题。关闭

**Comment by zhangshihuann** [comment]
`build`命令默认会生成`sourcemap`吗？ 我`build`的时候并没有看到`sourcemap`生成  请问是哪里的配置？ @skyblue

**Comment by naivehhr** [comment]
@zhangshihuann 我也遇到了同样的问题，请问您解决了吗？
