### ISSUE TITLE
roadhog 如何支持 historyApiFallback？

### ISSUE THREAD

**Issue by mayacger** [sorrycc/roadhog#228]
主要目的是本地开发单页应用时非常有用，它依赖于HTML5 history API，如果设置为true，所有的跳转将指向index.html

**Comment by sorrycc** [comment]
现在就支持的，https://github.com/sorrycc/roadhog/blob/4b492db/src/runServer.js#L129

**Comment by FourLeafClover** [comment]
@sorrycc 有demo可以跑吗？还是不知道怎么用呢。
