### ISSUE TITLE
现在支持不支持Sass?

### ISSUE THREAD

**Issue by weishijun14** [sorrycc/roadhog#229]
现在要使用一个css库，是用sass写的，不知道现在roadhog支不支持sass？
如果支持，怎么写roadhogrc? 谢谢！

**Comment by DiroKate** [comment]
所以这么问题没有结论吗？

**Comment by weishijun14** [comment]
@DiroKate 结论是自己建立一个webpackconfig文件，然后手动在里面添加sass - loader.......

**Comment by DiroKate** [comment]
@weishijun14 能和roadhogrc共用吗？有没有相关的例子？

**Comment by weishijun14** [comment]
@DiroKate https://github.com/sorrycc/roadhog/issues/36#issuecomment-301122893

**Comment by smancang** [comment]
我使用的是0.6.0版本，通过webpack.config.js并不能解决问题，我想问下，你们的问题真解决了么？还是说我的版本有问题？
