### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by kevin0137** [sorrycc/roadhog#232]
似乎是一个BUG 有空看看这个[问题](https://github.com/ant-design/antd-mobile-samples/issues/5)吗?

**Comment by afc163** [comment]
+1

**Comment by sorrycc** [comment]
好像和这个有关：

- https://github.com/webpack/webpack-dev-server/issues/882
- https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3

**Comment by sorrycc** [comment]
+ roadhog@0.6.0-beta.5
+ roadhog@0.5.4
