### ISSUE TITLE
Invalid Host Header

### ISSUE THREAD

**Issue by caigehui** [sorrycc/roadhog#234]
npm update 后 webpack-dev-server升级到1.6.5

之后通过局域网地址访问本地调试服务器会出现Invalid Host Header
[webpack/webpack-dev-server#882](https://github.com/webpack/webpack-dev-server/issues/882)

需要在webpack配置中将disableHostCheck设置为true

How to fix the problem through roadhog?

Edit:
因为roadhog不推荐配置webpack.config.js，所以要手动回滚webpack-dev-server到1.6.3以下

**Comment by sorrycc** [comment]
roadhog@0.5.4 已修复。

**Comment by JavaBird** [comment]
怎么配置呢？

**Comment by sorrycc** [comment]
无需配置，内部解决的。

**Comment by JavaBird** [comment]
@sorrycc 我的项目通过 http://localhost:8000/#/home 和 http://127.0.0.1:8000/#/home 都可以正常访问，但是通过ip访问就不行了，eg: http://192.168.2.129:8000/#/home 就报 Invalid Host header
也就是说，局域网内无法访问到。
我的roadhog 版本是 0.6.0-beta1。
