### ISSUE TITLE
经测试roadhog server的node进程占用cpu很高达到120%

### ISSUE THREAD

**Issue by MedusaLeee** [sorrycc/roadhog#237]
经测试roadhog server的node进程占用cpu很高，达到120%.

系统： mac sierra 10.12.4
node版本： v7.9.0
dva版本：1.2.1
dva中roadhog的版本：0.5.3

在node v7.7.1上cpu占用正常

**Comment by sorrycc** [comment]
用 6.9 呢?

**Comment by MedusaLeee** [comment]
@sorrycc 我测试一下

**Comment by sorrycc** [comment]
roadhog 没做啥特殊处理，背后基于 webpack 的，如果占用高，那么 webpack 也有同样问题。

**Comment by MedusaLeee** [comment]
@sorrycc 我在继续测试一下，有问题再反馈。

**Comment by huanghaiyang** [comment]
同样情况

**Comment by zero1five** [comment]
同样的问题， 占用率非常高
