### ISSUE TITLE
roadhog打包后随便进一个路由刷新报404错误

### ISSUE THREAD

**Issue by internet5** [sorrycc/roadhog#239]
roadhog打包发布后随便进一个路由刷新报404错误，但是直接点链接是没问题的，刷新就404，初始路由"/"刷新不会报错，不打包发布本地是不会出错的

**Comment by varrant** [comment]
@sorrycc 遇到相同问题，求解答 。

**Comment by varrant** [comment]
有木有人帮忙解答这个问题呢。急哦~

**Comment by varrant** [comment]
index.js 文件中 把browerHistory 改成 hashHistory即可解决打包问题

`import dva from 'dva';
import { hashHistory } from 'dva/router';
import createLoading from 'dva-loading';
import { message } from 'antd';
import './index.html';


const ERROR_MSG_DURATION = 3; // 3 秒

// 1. Initialize
const app = dva({
  history: hashHistory,
  onError(e) {
    message.error(e.message, ERROR_MSG_DURATION);
  },
});

// 2. Plugins
app.use(createLoading());

// 3. Model
// Moved to router.js
// app.model(require('./models/loanee'));

// 4. Router
app.router(require('./router'));

// 5. Start
app.start('#root');
`

**Comment by internet5** [comment]
@varrant 有效，谢谢啊，在哪找到的答案呢

**Comment by varrant** [comment]
@internet5 自己看源码，按照格式写的。
