### ISSUE TITLE
关于roadhog的版本号

### ISSUE THREAD

**Issue by zuiidea** [sorrycc/roadhog#240]
- `package.json`中`"roadhog": "^0.6.0-beta.6"`，直接`npm i`安装的版本将是`0.6.0-beta2`

![image](https://cloud.githubusercontent.com/assets/16070518/25655745/9bc8f30c-3028-11e7-95bb-29120ac3c5cd.png)

问题猜测：是不是版本号发错了，`req.body`问题有点严重，是不是应该发大版本， `0.6.0-beta.6` =>`0.6.0-beta6`

**Comment by sorrycc** [comment]
确实，我尽快发下正式版，先写死 `0.6.0-beta.6` 吧。

**Comment by zuiidea** [comment]
@sorrycc 嗯，现在写死的
