### ISSUE TITLE
How can I use the bypass option in webpack-dev-server proxy ?

### ISSUE THREAD

**Issue by ly710** [sorrycc/roadhog#244]
I've tried this in webpack.config.js, but didn't work.

    module.export = function(webpackConfig) {
        webpackConfig.devServer = {
            proxy:  {
                '/api': {
                    ....
                    bypass:  function() {
                        ...
                    }
                }
            }
        }
        return webpackConfig;
    }

**Comment by sorrycc** [comment]
Try [#proxy](https://github.com/sorrycc/roadhog#proxy) config in `.roadhogrc.js`.

**Comment by tyc920120** [comment]
直接配置bypass，会显示语法错误，具体应该怎么做。
Syntax error: Unexpected token 'f' , (14:21)
          "bypass": function(req, res, proxyOptions) {

**Comment by sorrycc** [comment]
Try #proxy config in `.roadhogrc.js`, not `.roadhogrc`.
