### ISSUE TITLE
【Question】roadhog如何多渠道打包，区分开发环境，测试环境和生产环境

### ISSUE THREAD

**Issue by ufohjl** [sorrycc/roadhog#250]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）latest

#### What do you expected?（预期的正常效果）
```
if (ENV === 'dev') {
  API_GATEWAY = 'https://dev.domain.com'
} else if (ENV === 'test') {
  API_GATEWAY = 'https://test.domain.com'
} else if (ENV === 'prod') {
  API_GATEWAY = 'https://prod.domain.com'
}

```
业务通过环境参数控制，build后不同的环境使用不同的参数或者业务逻辑分支，请问使用roadhog如何实现该需求

**Comment by pmg1989** [comment]
同问，好像是没有发现可以配置的地方，而且实际开发过程中也确实有此类需求，不知道 @sorrycc 有没有好的解决方案呢，谢谢

**Comment by sorrycc** [comment]
API_GATEWAY 的配置为啥不放在 html 里，然后由后台判断输出？

**Comment by sorrycc** [comment]
在 #271 统一考虑。

**Comment by ufohjl** [comment]
@sorrycc thanks。后台渲染也是一种思路，但毕竟要多一次计算。生产环境目前我们更倾向于用静态化部署方案如nginx+CDN，index.html用nginx解析，js和css文件名加hash后传到CDN上
