### ISSUE TITLE
关于0.6.x的chunkFilename的配置问题

### ISSUE THREAD

**Issue by codering** [sorrycc/roadhog#251]
由于0.6.x里新增了'chunkFilename'配置， `chunkFilename: '[id].async.js'`.

假设有这样一段代码

```js
   require.ensure('xxx/demo', function(){
       // do something
   }, 'demo')

```

升级0.6.x前，生成的chunk名字为 `1.demo.js`, 如果没有给require.ensure设置第3个参数，则为`1.abcdfsf.js`。

升级0.6.x后，生成的chunk名字为 `1.async.js`, 如果没有给require.ensure设置第3个参数，也是`1.async.js`.  

0.6发布说明里说可读行更好了，但个人感觉实际上更差了, 希望能再改进一下， 比如 
```js
  ...
  chunkFilename: '[id].[name].async.js'
  ...

```
就是name不要丢掉。

相关issue: 
https://github.com/sorrycc/roadhog/issues/100
https://github.com/sorrycc/roadhog/issues/212
https://github.com/sorrycc/roadhog/issues/217
https://github.com/sorrycc/roadhog/issues/247

#

**Comment by paranoidjk** [comment]
这种应该保留webpack的option就好了吧，不要自定义规则

**Comment by codering** [comment]
@paranoidjk  关键roadhog里已经自定义规则了。

**Comment by sorrycc** [comment]
改成 `[name].async.js` 吧，name 不存在时会自动用 id 代替，之前不清楚 `require.ensure` 可以指定名字。

- http://webpack.github.io/docs/configuration.html#output-chunkfilename

**Comment by AlaiNiGuests** [comment]
chunkFilename 在哪里进行配置…我找不到发布说明…
