### ISSUE TITLE
是否考虑升级到webpack2了呢？

### ISSUE THREAD

**Issue by skyblue** [sorrycc/roadhog#257]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
是的，感觉大势所趋啊，下个版本。
