### ISSUE TITLE
新增dll后，npm安装会报错

### ISSUE THREAD

**Issue by whwnow** [sorrycc/roadhog#258]
报错如下：
`extraneous error: ENOENT: no such file or directory, open 'E:\Git\boxcai-web\node_modules\roadhog-dlls\package.json`

希望可以把dll存储在非node_modules目录下，排除报错。而且有时候回去dll文件定位一下问题，在modules文件夹下文件太多不是很好找（我设置编辑器会排除modules）。

**Comment by sorrycc** [comment]
`E:\Git\boxcai-web\node_modules\roadhog-dlls\package.json` 这个文件不存在吗? 要运行 `roadhog buildDll` 生成一次的。

**Comment by whwnow** [comment]
就是运行`roadhog buildDll`之后再执行`npm install`的时候啊。运行前没roadhog-dlls这个目录，也不会报错呀

**Comment by sorrycc** [comment]
你手动 import 了 `roadhog-dlls`?

**Comment by whwnow** [comment]
没有import啊，感觉像是npm自动检查modules目录时发现没有package.json报的错。我的版本是。`node 7.10.0 npm 4.2.0`

**Comment by ziben** [comment]
我这边是有一条警告信息，但是不影响其他的

**Comment by ziben** [comment]
同样希望dll的位置能自定义，不要放在node_modules下面了

**Comment by sorrycc** [comment]
警告信息贴出来看下。

**Comment by whwnow** [comment]
就是我发那个警告信息，可能我开始说得不清楚，是个警告信息不影响运行的。
