### ISSUE TITLE
使用dllPlugins，还是需要在调试的 html 里引入roadhog.dll.js吗

### ISSUE THREAD

**Issue by not3** [sorrycc/roadhog#260]
#### Environment development

- roadhog 0.6.0

如题

**Comment by sorrycc** [comment]
目前是需要的。

**Comment by wangfengcool** [comment]
我使用了 提示 Uncaught ReferenceError: roadhog is not defined。
是那里没有配置吗

**Comment by grunmin** [comment]
@wangfengcool 说明你没有引入roadhog.dll.js或者没有引入成功
