### ISSUE TITLE
如果0.6.0版本的转发在window下有问题可以考虑修改下面的代码

### ISSUE THREAD

**Issue by ranchoX** [sorrycc/roadhog#262]
[https://github.com/sorrycc/roadhog/blob/master/src/utils/mock.js#L62](https://github.com/sorrycc/roadhog/blob/master/src/utils/mock.js#L62)
改为如下
`return join((url.parse(target).path), matchPath).replace('\\','/')`

**Comment by sorrycc** [comment]
感谢反馈！

**Comment by cfZeng** [comment]
https://github.com/sorrycc/roadhog/blob/master/src/utils/mock.js#L56
Windows下还是有问题，需要改为:
return winPath(join(url.parse(target).path, matchPath));

**Comment by cfZeng** [comment]
@sorrycc

**Comment by sorrycc** [comment]
改了，下个版本修复。
