### ISSUE TITLE
开发使用roadhog server的时候，可以自动生成sourcemap，方便我们debug吗？

### ISSUE THREAD

**Issue by not3** [sorrycc/roadhog#264]

**Comment by sorrycc** [comment]
server 时是有生成 sourcemap 的，https://github.com/sorrycc/roadhog/blob/be2d1ee/src/config/webpack.config.dev.js#L34

**Comment by not3** [comment]
请问一下， 我使用JetBrains IDE Support，监听端口怎么设置呢，我用默认的63342端口，在代码里debug，没监听到

**Comment by sorrycc** [comment]
下面的 webpack:// 就是 sourcemap 。

**Comment by not3** [comment]
下了断点 debug不到

![debug](https://cloud.githubusercontent.com/assets/211266/26390760/7c379866-4092-11e7-8f56-66be688c32ae.jpg)

**Comment by not3** [comment]
又试了，0.6.0debug进不去，0.5.4可以正常debug
