### ISSUE TITLE
BROWSER=none参数在windows7不起作用，roadhog server仍然启动浏览器

### ISSUE THREAD

**Issue by 804e** [sorrycc/roadhog#265]
> node -v
v6.9.4
> roadhog -v
0.6.0
> npm -v
3.10.10

在windows 7下执行```set BROWSER=none&&roadhog server```，仍然会自动打开浏览器，参数无效

**Comment by sorrycc** [comment]
没 windows 环境，帮忙定位下原因？相关代码在 roadhog/node_modules/react-dev-utils/openBrowser.js 里。

**Comment by 804e** [comment]
应该怎么定位？一脸萌逼，我是做antd的demo[《12 步 30 分钟，完成用户管理的 CURD 应用 (react+dva+antd)》](https://github.com/sorrycc/blog/issues/18)时遇到这个问题的

**Comment by 804e** [comment]
发现两个问题
* dva初始化的脚手架，react-dev-utils的版本还是0.4.2，并不支持BROWSER参数
* 使用react-dev-utils0.5.2版本调试，发现命令行执行set BROWSER=none并不能再process.env中加入BROWSER变量，手动设置在用户环境变量中，倒是能看到这个key，但是所有值都是undefined，`Line 30, Column 1

SourcesContent scriptsSnippets
(core modules)
file://
C:/Users/wangweifeng/AppData/Roaming/npm/node_modules/node-inspector
E:/ws_front
ant-design-demo/user-dashboard
node_modules
openBrowserDebug.js

Pause On Caught Exceptions






Watch Expressions
process.env: Object
ALLUSERSPROFILE: undefined
ANDROID_SDK_HOME: undefined
ANT_HOME: undefined
APPDATA: undefined
ATOM_NODE_URL: undefined
BROWSER: undefined
CLASSPATH: undefined
COMPUTERNAME: undefined
ComSpec: undefined
CommonProgramFiles: undefined
CommonProgramFiles(x86): undefined
CommonProgramW6432: undefined
FP_NO_HOST_CHECK: undefined
HADOOP_HOME: undefined
HADOOP_USER_NAME: undefined
HOMEDRIVE: undefined
HOMEPATH: undefined
JAVA_HOME: undefined
LOCALAPPDATA: undefined
LOGONSERVER: undefined
MOZ_PLUGIN_PATH: undefined
NUMBER_OF_PROCESSORS: undefined
OS: undefined
PATHEXT: undefined
PROCESSOR_ARCHITECTURE: undefined
PROCESSOR_IDENTIFIER: undefined
PROCESSOR_LEVEL: undefined
PROCESSOR_REVISION: undefined
PSModulePath: undefined
PUBLIC: undefined
Path: undefined
ProgramData: undefined
ProgramFiles: undefined
ProgramFiles(x86): undefined
ProgramW6432: undefined
SESSIONNAME: undefined
SystemDrive: undefined
SystemRoot: undefined
TEMP: undefined
TESSDATA_PREFIX: undefined
TMP: undefined
USERDOMAIN: undefined
USERNAME: undefined
USERPROFILE: undefined
windir: undefined
windows_tracing_flags: undefined
windows_tracing_logfile: undefined`

调试环境用的是inspector，调试代码`const openBrowser = require("react-dev-utils/openBrowser");

function init() {
	openBrowser('https://www.baidu.com');
}

init();`

**Comment by sorrycc** [comment]
把 roadhog 依赖更新到 0.6.0 吧。

**Comment by 804e** [comment]
package.json里面配置的是"roadhog": "^0.6.0"啊

**Comment by 804e** [comment]
我在[antd-admin](https://github.com/zuiidea/antd-admin)看到的配置是```"roadhog": "0.6.0-beta.6"```，这个项目启动的时候使用```"dev": "set BROWSER=none&&set HOST=0.0.0.0&&roadhog server"```就不会打开浏览器
