### ISSUE TITLE
Use roadhogrc to compile the code when running tests

### ISSUE THREAD

**Issue by oluckyman** [sorrycc/roadhog#266]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）0.6.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）7.4.0, 4.0.5
- Operating environment (e.g. OS name) and its version（操作系统版本）: OSX 10.11.6

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

I’ve used `babel-module-resolver` plugin to use absolute paths in imports:
```
import x from '~/path/x';
```
Then I run `npm run test`
#### What do you expected?（预期的正常效果）

Tests should respect `.roadhogrc` configs and use plugins to compile tested code.

#### What happen?（发生了何种非正常现象）

It works well when I run the server but when I run tests it fails with errors like this:
```
Error: Cannot find module '~/services/schemas'
```

#### Re-producible online demo (可复现的在线demo)

config in `.roadhogrc.js`
```
  "extraBabelPlugins": [
    ...,
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "~": "./src"
      }
    }]
  ],
```

`/test/schema.model-test.js`
```
import expect from 'expect';
import { reducers } from '../src/models/schema'; // `~` does not work here

describe('schema model', () => {
  it('should work', () => {
    expect(reducers.save({}, { payload: 'hi' })).toBe('hi');
  });
});
```
`/src/models/schema.js`
```
import { saveOne, fetchOne } from '~/services/schemas';
...
```

when run `npm run test` it throws:
```
Error: Cannot find module '~/services/schemas'
```

***

It works when I hardcode plugin in `node_modules/roadhog/lib/test/compiler.js`:
```
  ...
  plugins: [
    require.resolve('babel-plugin-add-module-exports'),
    [require.resolve('babel-plugin-module-resolver'), { // ← here
      "root": ["./src"],
      "alias": {
        "~": "./src"
      }
    }] 
  ]
  ...
```

**Comment by oluckyman** [comment]
Just updated roadhog to 1.0.0-beta.1 to test that fix.
Running `npm run test` and getting the error:  
```

/.../test/schema.model-test.js:1
(function (exports, require, module, __filename, __dirname) { import expect from 'expect';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by oluckyman** [comment]
https://github.com/sorrycc/roadhog/blob/4649d06213786160407c3cdd8809b40f23831aa9/src/test/compiler.js#L3
```
const config = getConfig('test', process.cwd());
```
should I make a separate config for test? can you please provide an example?

**Comment by oluckyman** [comment]
I see. it’s because in roadhogrc in config `extraBabelPlugins` is json description:
```
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "~": "./src"
      }
    }]
```
But in compiler.js it should be plugin instances: 
```
    [require.resolve('babel-plugin-module-resolver'), {
      "root": ["./src"],
      "alias": {
        "~": "./src"
      }
    }] 
```

**Comment by chillyistkult** [comment]
Is there any solution for this problem yet? Can someone summarize?
