### ISSUE TITLE
打包部署后static下的图片为什么请求不到了！

### ISSUE THREAD

**Issue by SynChron1zed** [sorrycc/roadhog#267]
http://120.76.194.221/testdemo/#/?_k=1f8725

#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） "roadhog": "^0.5.2"
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:
mac
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/26342846/3cdd38ea-3fcc-11e7-96c6-013e041dc664.png)

**Comment by SynChron1zed** [comment]
请求的时候 会少了根目录名  这个是官网的案例

**Comment by sorrycc** [comment]
要配 [publicPath](https://github.com/sorrycc/roadhog#publicpath) 的。

**Comment by SynChron1zed** [comment]
@sorrycc  不是默认 ／  以前都没有问题啊

**Comment by sorrycc** [comment]
总之和 publicPath 有关，你根据生产的图片路径和真实请求的路径做下对比吧。

参考：

- http://webpack.github.io/docs/configuration.html#output-publicpath

**Comment by SynChron1zed** [comment]
@sorrycc  配了也没用  生成环境的应该配成什么

**Comment by sorrycc** [comment]
你理解下 publicPath 是什么吧。

**Comment by SynChron1zed** [comment]
问题解决了 publicPath 的输出为你的根目录名 就可以  借鉴吧
