### ISSUE TITLE
Post body 大小限制问题

### ISSUE THREAD

**Issue by hszcg** [sorrycc/roadhog#268]
Hi，

如 https://github.com/sorrycc/roadhog/blob/dddd78b08584a8cd0aea994e3d7902fe36315f46/src/utils/mock.js#L100 

目前的mock server 默认的post size limit是默认值200KB，对于一些图片类调试不太合适，建议改成更大的默认值并提供配置选项，类似于

```
  devServer.use(bodyParser.json({limit: '5mb'}));
  devServer.use(bodyParser.urlencoded({
    extended: true,
    limit: '5mb',
  }));
```

**Comment by hszcg** [comment]
谢谢，麻烦问一下，新的版本预计什么时候可以发布呢？ @sorrycc

**Comment by sorrycc** [comment]
+ roadhog@1.0.0-beta.1
