### ISSUE TITLE
externals配置项似乎是不起作用

### ISSUE THREAD

**Issue by Aiooioo** [sorrycc/roadhog#272]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）0.5.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）6.9.2
- Operating environment (e.g. OS name) and its version（操作系统版本）: win10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
配置roadhogrc中的externals参数似乎不起作用，仍然会报错找不到module，无论是使用json格式还是js格式都不行，
改为webpack.config.js来配置就没有问题了

#### What do you expected?（预期的正常效果）
在amd模式下能忽略外部的lib

#### What happen?（发生了何种非正常现象）
仍然报错，找不到外部lib

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
可能是 bug

**Comment by pigcan** [comment]
可能和 externals 写法有问题

```
externals: {
  'react': { amd: 'react', root: 'React' },
}
```

这样试试看?

**Comment by sorrycc** [comment]
加了个用例，应该是有效的。
