### ISSUE TITLE
配置mock的时候Random.image这个不能使用

### ISSUE THREAD

**Issue by baixiaosh** [sorrycc/roadhog#277]
在mock配置中使用mock造数据的时候,采用Random.dataImage生成图片,但是编译的时候会报错:module.require is not a function,去掉Random.dataImage就没问题

**Comment by baixiaosh** [comment]
奇怪又好了

**Comment by baixiaosh** [comment]
Random.dataImage 是这个  不是Random.image

**Comment by sorrycc** [comment]
不清楚 `Random.dataImage` 是什么。

**Comment by baixiaosh** [comment]
Mock.Random.dataImage
https://github.com/nuysoft/Mock/wiki/Image#randomdataimage-size-text-

**Comment by sorrycc** [comment]
看起来和 roadhog 无关啊。

**Comment by baixiaosh** [comment]
就是roadhog结合使用Mock的时候，编译会提示这个错误

**Comment by baixiaosh** [comment]
在使用roadhog之前使用的atool-build配置的没有提示这个错误，
