### ISSUE TITLE
测试服务器的node版本是6.2.2。如何向下兼容到6.2.2

### ISSUE THREAD

**Issue by YMJxiaojia** [sorrycc/roadhog#279]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by YMJxiaojia** [comment]
roadhog需要的版本必须是6.5以上。这个可以想办法到6.2.2吗

**Comment by sorrycc** [comment]
抱歉，现在不支持 6.5 以下。
