### ISSUE TITLE
咨询，node源码为啥要用es6的import组织模块化？

### ISSUE THREAD

**Issue by johnnychen** [sorrycc/roadhog#282]
用了import，还必须用babel，每次node运行都要编译一下，不是自己给自己造成不方便吗？

不吝赐教

**Comment by sorrycc** [comment]
对我来说两个原因，1 是 node 支持的特性没有 babel 的多，2 是我需要同时写前端代码和 node 代码，不想花时间去记两者之间的区别。

**Comment by johnnychen** [comment]
那请教下你现在是如何进行代码开发的，我先在是：
1. 每次改了src
2. 手动运行npm run build
3. 然后运行test用例，查看更改的功能是否符合预期

每次改代码都多了中间第二步，有更加简单的方法吗？

**Comment by pigcan** [comment]
第二步可以 `npm run build -- --watch`
第三步不需要建立在第二步基础上，看下 scripts 里 test 的描述。
