### ISSUE TITLE
entry使用webpack复写之后，multipage为true，抽出的common.js错误

### ISSUE THREAD

**Issue by panyifei** [sorrycc/roadhog#285]
开了multipage为true，因为我的页面有多个，并不是src/page/*.js这样的目录结构，于是我用webpack来复写了entry，正常tnpm start开发没有问题。
roadhog build打包出来的时候，抽离的common.js只认了我写在.roadhogrc里面的entry，没有认webpack复写的entry。

后来我改了文件结构，改成了src/page/*.js这样的结构，解决了。

**Comment by sorrycc** [comment]
webpack 复写 entry? 在 `webpack.config.js` 里吗?

**Comment by sorrycc** [comment]
最好给个能重现的例子。

**Comment by panyifei** [comment]
因为我是多页面的，我在.roadhog里面这么写：
`{
  "entry": "src/index/index.js",
  "disableCSSModules": true
}`

我在webpack配置里面写
`export default function (roadHogConfig) {
  const newConfig = roadHogConfig;
   const entry = roadHogConfig.entry;
   const webpackHotClientPath = entry.index[0];
   _.extend(newConfig.entry, {
     sls: [webpackHotClientPath, './src/sls/index.js'],
   });

  return newConfig;
}
`

然后tnpm start正常开发的时候没问题，roadhog build的时候，打包出来的common.js只认了src/index/index.js这一个入口。将src/index/index.js里面的独有的逻辑也打包进了common.js里面，是我配置名字的问题吗？

**Comment by liuchaofeng1230** [comment]
能否支持多entry？
