### ISSUE TITLE
缓存是否分级？怎么清除不同级别的缓存？

### ISSUE THREAD

**Issue by Fairyshi** [sorrycc/roadhog#286]
roadhog版本："1.0.0-beta.3"

场景：
多页面.roadhogrc.js相关配置：
  entry: 'src/page/*.js',
  multipage: true,

以下是多页中的一个页面入口文件src/page/dashboard.js：
```   
import '../index.html'
import 'babel-polyfill'
import dva from 'dva'
import createLoading from 'dva-loading'
import { browserHistory, Router, Route } from 'dva/router'
import { message } from 'antd'
import App from '../routes/layout.js'

const app = dva({
  ...createLoading({
    effects: true,
  }),
  history: browserHistory,
  onError (error) {
    message.error(error.message)
  },
})

const Routers = function ({ history, app }) {
  return (
    <Router history={history}>
      <Route path="/" component={require('../routes/dashboard')} />
    </Router>
  );
};

app.model(require('../models/dashboard'))
app.router(Routers)
app.start('#root')
```

复现步骤：
1、访问http://localhost:8000/dashboard成功后
2、执行rm -rf ./node_modules/.cache
3、将src/index.html中的
  <link rel="stylesheet" href="/dashboard.css" />
  <script src="/dashboard.js"></script>
分别改成
  <link rel="stylesheet" href="/xixi.css" />
  <script src="/xixi.js"></script>
4、强刷页面，引入的仍然是文件
  <link rel="stylesheet" href="/dashboard.css" />
  <script src="/dashboard.js"></script>

问题：
1、涉及到几级缓存
2、不同级别的缓存分别怎么清除
3、浏览器控制台经常报“Uncaught ReferenceError: webpackJsonp is not defined”的问题（多页场景），node编译是通过的，前台报错但是什么报错信息都get不到，求解~

**Comment by sorrycc** [comment]
> 3、浏览器控制台经常报“Uncaught ReferenceError: webpackJsonp is not defined”的问题（多页场景），node编译是通过的，前台报错但是什么报错信息都get不到，求解~

没有引 `common.js`?
