### ISSUE TITLE
dvajs 建的项目，npm install ali-oss后，npm start提示 child_process模块找不到，请帮忙看看@sorrycc

### ISSUE THREAD

**Issue by huangronggod** [sorrycc/roadhog#288]
@sorrycc
Error in ./~/address/lib/address.js
Module not found: 'child_process' in /Volumes/CODE1/react/wxadminnew/WxAdmin/node_modules/address/lib

 @ ./~/address/lib/address.js 5:12-36

那我要在.roadhog里如何配置呢

**Comment by sorrycc** [comment]
是 ali-oss 这个库的问题吧，前端代码怎么会有 child_process 模块的？
