### ISSUE TITLE
是否可以将gzip和混淆分离

### ISSUE THREAD

**Issue by Stan-Wang** [sorrycc/roadhog#289]
RT . 现在build是生产版本的混淆和gzip压缩，添加 --debug则取消混淆和压缩，两种模式是否可以尝试分离？通过命令参数的方式选择只混淆不压缩？压缩可以通过nginx统一配置.

**Comment by paranoidjk** [comment]
@sorrycc gzip 有必要在构建阶段做吗？一般 cdn server 或者 nginx 来做 gzip 吧

**Comment by paranoidjk** [comment]
+1 支持加个参数 `--gzip` 之类。

**Comment by sorrycc** [comment]
build 并没有做 gzip 吧，只是输出日志里的尺寸大小是根据 gzip 后来统计的。

**Comment by Stan-Wang** [comment]
目前在做一个比较复杂的项目，对比build和debug的文件大小，同一个代码版本，一个是95M，一个是124M，但是执行时间差别非常大，debug只需要大概30秒左右，build则需要500秒+

**Comment by sorrycc** [comment]
95**M**?

**Comment by Stan-Wang** [comment]
包含字体和图片，这个占了一多半，目前还没有来得及优化...重点是两个模式的差别，编译时间和内存使用区别有点儿太大了，你们目前有类似的问题么？

**Comment by sorrycc** [comment]
build 500秒+ 应该大部分时间是在压缩。

**Comment by Stan-Wang** [comment]
所以期望能不能分离一下，只混淆不压缩，后期通过nginx或者cdn走压缩流程

**Comment by sorrycc** [comment]
不压缩不是有参数吗? `roadhog build --debug`

**Comment by Oscar19921030** [comment]
![image](https://user-images.githubusercontent.com/20589681/27365771-7a7b750e-5674-11e7-8fe2-75b8de56c1fb.png)
在不是debug的情况build ，gzip是没有启动吗？

**Comment by Oscar19921030** [comment]
如何启用gzip 压缩构建的index.js ？

**Comment by jackple** [comment]
nginx的话搜一下启用gzip，其他不知道
