### ISSUE TITLE
extraBabelIncludes can't surpport jsx

### ISSUE THREAD

**Issue by xiaosansiji** [sorrycc/roadhog#290]
#### Environment(required) | 环境（必填）

- roadhog version: 1.0.0-beta.3
- Nodejs and Npm version: 7.9.0 and 4.2.0
- Operating environment (e.g. OS name) and its version: Win7

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
1、我将项目中公用的组件抽成了 npm 模块发布在了私有 npm 镜像库中，模块中主要是 jsx 语法写的 React 组件函数：
![image](https://cloud.githubusercontent.com/assets/7600149/26820359/29d20186-4ad5-11e7-9b17-937337c5896f.png)
代码未经过编译，还是 ES6

2、在 .roadhogrc 中配置extraBabelIncludes
为了在工程中使用未编译的 npm 模块，我在.roadhogrc 中配置了extraBabelIncludes：
![image](https://cloud.githubusercontent.com/assets/7600149/26820504/a7069afe-4ad5-11e7-8fa5-766282f14619.png)

#### What do you expected?（预期的正常效果）
可以在编译主工程时顺便把 node_modules 对应文件夹下的模块源码也编译进去

#### What happen?（发生了何种非正常现象）
![image](https://cloud.githubusercontent.com/assets/7600149/26820635/117e5b88-4ad6-11e7-966b-d1e1eae1f9bb.png)

我实验了一下，加了 extraBabelIncludes 配置以后，我在 node_modules  对应文件夹中 ES6 语法写的 const/import/export 等是没有问题的，说明 babel 确实编译了代码，但是从上图中的异常来看，貌似没有识别 jsx 语法？我之前直接用 webpack 的时候也是直接用了babel loader 能够识别 jsx ，只不过需要通过 .babelrc 文件做下设置，在 roadhog 这里我应该怎样支持 jsx 语法？

我在 Issues 里找到了[这个](https://github.com/sorrycc/roadhog/issues/35) ，确实是可以只用 npm 发布编译好的代码，但是如果在主工程编译过程中也能编译第三方的代码会更方便一些。

**Comment by sorrycc** [comment]
在 https://github.com/sorrycc/roadhog/tree/master/test/fixtures/build/extraBabelIncludes 这个用例里我加了 jsx 并没有问题，怀疑是 windows 路径的问题。

你找到 `node_modules/roadhog/lib/utils/addExtraBabelIncludes.js` 第 14 行，这样改下试试。

```diff
- include: (0, _path.join)(paths.appDirectory, include),
+ include: (0, _path.join)(paths.appDirectory, include).replace(/\\/g, '/'),
```
