### ISSUE TITLE
build --debug --watch 报错

### ISSUE THREAD

**Issue by iwege** [sorrycc/roadhog#292]
#### Environment(required) | 环境（必填）

- roadhog@0.5.4
- Nodejs 7.10.0
- Npm 4.2.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: MacOS
-  antd  2.10.4

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
无法100%重现
1. roaghog 使用的是`entry:"pages/*"`的配置，其他没有变化
2. 集成了antd，按照说明配置，没有其他添加
3. `roadhog build --debug --watch`

#### What do you expected?（预期的正常效果）

build出来的js能正常运行

#### What happen?（发生了何种非正常现象）

某些情况下无法正常允许，报错
`Uncaught TypeError: Cannot read property 'apply' of undefined`

跟踪代码发现部分 require的代码 注释为`// removed by extract-text-webpack-plugin`，在正常情况下应该没有问题，但是某些情况下会调用。

#### Re-producible online demo (可复现的在线demo)

无

根据检索的情况，初步估计和 https://github.com/ant-tool/atool-build/issues/265 反映的情况类似。

#### 相关Issue
- https://github.com/sorrycc/roadhog/issues/154
- https://github.com/ant-tool/atool-build/issues/265

**Comment by sorrycc** [comment]
我在 watch 模式下把 DedupePlugin 给禁掉吧。

**Comment by sorrycc** [comment]
1.0.0-beta.4

**Comment by iwege** [comment]
@sorrycc 本地可以直接从dva的0.5.4升级上来？dva 0.7.8创建的都是0.5.4的版本
