### ISSUE TITLE
roadhog 怎么配置history-api-fallback

### ISSUE THREAD

**Issue by qingfengmy** [sorrycc/roadhog#299]
比如输入
```
http://localhost:8000/login
```
此时不加载login页面，只是展示'/'对应的页面，其children是null，location.pathname是 '/'

之前webpack的修改是：
```
"start": "webpack-dev-server --inline --content-base . --history-api-fallback"
```
就可以解决该问题，请问 现在处理？

history改成browserHistory 就正确

**Comment by sorrycc** [comment]
history-api-fallback 内置有的，无需配置。
