### ISSUE TITLE
约定 public 目录会被自动 copy 到 dist 下

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#30]
用于存放 favicon.ico, iconfont 等。

**Comment by chocking** [comment]
是我使用方式不对吗  "roadhog": "^0.5.2"  src/public 下的文件没有复制到dist下

**Comment by sorrycc** [comment]
不是 `src/public`，而是 `public`。

**Comment by zuiidea** [comment]
难道是我的锅...
当时因为这个问题 https://github.com/sorrycc/roadhog/issues/341 ，我把public移到了src目录，但是`webpack.config.js`重新做了copy😥

**Comment by Irislm** [comment]
@zuiidea 就是你的锅，ant-admin的public在src下，我就说怎么不对，找了好久才找到这儿
