### ISSUE TITLE
npm run build后dist目录下未生成roadhog.dll.js

### ISSUE THREAD

**Issue by jeffhtli** [sorrycc/roadhog#303]
#### Description
在.roadhogrc中增加dllPlugin配置，npm run build后dist目录下未生成roadhog.dll.js

#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
0.6.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）
node: v7.7.3
npm: 4.1.2
- Operating environment (e.g. OS name) and its version（操作系统版本）:
Ubuntu 17.04 

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
git clone https://github.com/dvajs/dva-example-user-dashboard.git
cd dva-example-user-dashboard
npm i
npm run build

#### What do you expected?（预期的正常效果）
dist目录下有roadhog.dll.js

#### What happen?（发生了何种非正常现象）
dist目录下未生成roadhog.dll.js

**Comment by moocss** [comment]
1.  如果要使用 dllPlugin， 请执行 `npm run buildDll `命令。
2.  roadhog.dll.js 文件的生成目录在 `node_modules`中, 请看源码文件`src/config/paths.js`中配置。
```
dllNodeModule: resolveApp('node_modules/roadhog-dlls'),
dllManifest: resolveApp('node_modules/roadhog-dlls/roadhog.json'),
```

**Comment by jeffhtli** [comment]
@moocss  你好，因为src/config/webpack.config.prod.js中没有使用DllReferencePlugin插件， 所以现在dll功能只能用于dev环境，对不？

**Comment by moocss** [comment]
```npm run buildDll```  执行的是webpack.config.dll.js 配置文件。

**Comment by yangbin1994** [comment]
@jeffhtli 是的

**Comment by alishamarie57** [comment]
1.1 dva 简介

dva 是什么

dva 是阿里前端架构师 sorrycc 带 team 研发的一套轻量级前端框架，其目的是尽量避免前端重复性劳动，简化开发流程。

实际上也确实如此，一个简单的 CRUD 模块只需要1-2个小时即可完成前端作业。

dva 脚手架是什么

前面说到 dva 是一个框架，那么 dva 脚手架就是这个框架的具体表现。

我们习惯于称：创建一个 dva 脚手架，实际上就是创建一个项目目录。

脚手架都包含什么

一个完整的 dva 脚手架应该包含以下内容：

自动创建一个包含 package.json 的项目。
自动创建成体系的目录结构。
自动安装项目需要的基础包。
集成代码检查工具 ESLint。
集成模拟接口工具 Mock。
集成服务启动打包工具 Roadhog。
集成版本控制工具 Git。
可以看到，脚手架帮我们做了很多的事，这就是脚手架带给我们的便利，否则从零开始搭建项目，无疑是一件费时费力又考验技术水平的事情。

当然，上面列举的几条你可能暂时无法明白具体指什么。

不用着急，下面几节会介绍如何创建一个 dva 脚手架，以及详细分析脚手架目录结构来依次解释脚手架包含的内容。

下一节：1.2 创建一个 dva 脚手架工程

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
Code  Issues 1  Pull requests 0  Pulse
book/dva/dva 脚手架目录分析.md

1.3 dva 脚手架目录分析

在上一节中，介绍了如何使用 dva-cli 命令行工具来创建一个 dva 脚手架工程。

这一节来就自动创建的脚手架目录结构来分析一下脚手架都为我们做了哪些事情。

目录结构

脚手架在目录中做了哪些事情

下面就右边列举的 7 条逐条分析目录结构的组成。

这里只会介绍某个文件或文件夹是做什么的，具体涉及到技术层面的参见后面章节对每个技术模块的专讲。

希望看完之后再回过头看目录结构的时候能做到“原来如此”的表情。

分析

1.自动创建一个包含 package.json 的项目

package.json 文件
在很久很久以前，dk 要开发一个前端项目，在计算机的某个旮沓地方建立了一个文件夹叫 dk_project，就称为这是一个“项目”了。

又过了很久，dk 离开了公司，来了位新同事，在接手 dk 工作的时候发现计算机上面的 dk_project 文件夹，因为没有任何明显的标识，
就被当成普通文件夹给 DELETE 掉了。

回到现代，随着 npm 的诞生，人们意识到建立一个项目目录不应该这么草率，于是乎规定，
如果某个文件夹被创建作为一个项目目录，那么它就应该包含一个 package.json 的文件。

package.json 文件里记录项目的描述信息：项目作者、项目描述、项目依赖哪些包、插件配置信息等等数不清的好处。
在 npm 那一讲中将会详细介绍 package.json 文件的组成以及如何去自定义这个文件。
2.自动创建成体系的目录结构

public 文件夹、src 文件夹
一个项目，如果目录结构很混乱，从心理学角度上来说会让你的心情变的 bad，进而容易产生 bug，
在查找 bug 的时候再次由于目录结构的混乱而变得暴怒 ..... 循环下去，项目烂尾是小事，不小心因此变得神经质就不好啦。

良好的目录结构应该是条理清晰，每个文件夹都有具体的事情要做。这样写代码才能像做一件艺术品一样，身心得到满足与慰藉。
在项目目录中：

public 文件夹中存放静态资源，比如图片，静态页面 html 等。

src 文件夹是项目代码存放文件夹，里面又分了几个小目录，每个目录都负责具体的事情，这个需要在实际项目中进行讲解。

3.自动安装项目需要的基础包

node_modules 文件夹（如果你对依赖包的概念不清晰，可以看 npm 章节的介绍）
前面说到 package.json 中会记录项目需要依赖的基础包。

使用 npm install 指令可以安装这些依赖包，安装到项目根目录下的 node_modules 文件夹下。

一个项目中纯代码是很小的，占容量的是 node_modules 目录下的依赖包。普通的项目往往可以达到100-200M，而对应的纯项目代码1-5M。

现在 dk 想将最近开发的一个项目分享给同事 tiger，只需要将项目纯代码拷贝给 tiger 即可。
因为项目依赖的包都记录下 package.json 文件中，而在命令行中使用 npm install 指令就可以自动下载 package.json 记录的依赖包。
4.集成代码检查工具 ESLint

.eslintrc 文件 （如果你对代码检查工具不熟悉，可以看 ESLint 章节的介绍）
代码检查工具制定统一规则，然后项目中所有人都得遵守这一套规则去写代码，这样写出来的代码在客户面前就像是一个人写的一样。

.eslintrc 文件就是记录规则的配置文件。

到这里，你肯定好奇具体规则是什么，这事情 ESLint 工具都帮你制定好了，
你只需要去 [ESLint 规则配置](http://eslint.cn/docs/rules/) 里去查看规则即可。

如果你还要学习 ESLint 更深层次的知识又嫌弃官网太罗里吧嗦，可以看后面章节 ESLint 的专讲。
5.集成模拟接口工具 Mock

mock 文件夹、.roadhogrc.mock.js 文件
写前端的都知道，最烦恼的事情莫过于没有服务提供数据接口，写出的前端代码没法测试。

Mock 就是干这个的，让一个前端程序员可以通过最熟悉不过的 js 文件简单配置模拟服务端提供的接口，
可以造假数据，**“搞的就跟真的一样”**。

本文没有使用 dva 自带的 Mock 做模拟接口，而是使用更轻量级的 json-server 来做模拟服务接口，不会的可以在后面章节学习。

.roadhogrc.mock.js 文件：Mock 是个独立的技术，你得把它用到框架里来不是，所以就有了这个文件。
6.集成服务启动打包工具 Roadhog

.roadhogrc 文件

先来说点有趣的事情。dva 的作者 sorrycc 是个守望先锋玩家。dva 这个名字是守望先锋游戏里一个英雄的名字（女性英雄，瞬间秒懂），
而 roadhog 同样是守望先锋的另一名英雄，长得五大三粗，在游戏里叫做“路霸”。意思就是 roadhog 为 dva 守架护航。

roadhog 是为 dva 服务的，可以认为是 dva 的配置文件。
通过它可以做到以下几件事情（当然远不止这些，其它可看 Roadhog 专讲）

与其它插件集成；
启动服务：roadhog server；
打包项目：roadhog build。
7.集成版本控制工具 Git

.gitingore 文件

这是 Git 专有的文件，用于管理项目版本。具体三言两语道不清说不明，建议直接去看下 Git 的教程之后这个文件就清楚干嘛的啦。
Desktop version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
为了让你对规则有个更好的理解，ESLint 对其进行了分门别类。

所有的规则默认都是禁用的。在配置文件中，使用 "extends": "eslint:recommended" 来启用推荐的规则，报告一些常见的问题，在下文中这些推荐的规则都带有一个标记。

命令行的 --fix 选项用来自动修复规则所报告的问题（目前，大部分是对空白的修复），在下文中会有一个的图标。

Possible Errors
这些规则与 JavaScript 代码中可能的错误或逻辑错误有关：

for-direction
enforce “for” loop update clause moving the counter in the right direction.
no-await-in-loop
disallow await inside of loops
no-compare-neg-zero
disallow comparing against -0
no-cond-assign
禁止条件表达式中出现赋值操作符
no-console
禁用 console
no-constant-condition
禁止在条件中使用常量表达式
no-control-regex
禁止在正则表达式中使用控制字符
no-debugger
禁用 debugger
no-dupe-args
禁止 function 定义中出现重名参数
no-dupe-keys
禁止对象字面量中出现重复的 key
no-duplicate-case
禁止出现重复的 case 标签
no-empty
禁止出现空语句块
no-empty-character-class
禁止在正则表达式中使用空字符集
no-ex-assign
禁止对 catch 子句的参数重新赋值
no-extra-boolean-cast
禁止不必要的布尔转换
no-extra-parens
禁止不必要的括号
no-extra-semi
禁止不必要的分号
no-func-assign
禁止对 function 声明重新赋值
no-inner-declarations
禁止在嵌套的块中出现变量声明或 function 声明
no-invalid-regexp
禁止 RegExp 构造函数中存在无效的正则表达式字符串
no-irregular-whitespace
禁止在字符串和注释之外不规则的空白
no-obj-calls
禁止把全局对象作为函数调用
no-prototype-builtins
禁止直接调用 Object.prototypes 的内置属性
no-regex-spaces
禁止正则表达式字面量中出现多个空格
no-sparse-arrays
禁用稀疏数组
no-template-curly-in-string
disallow template literal placeholder syntax in regular strings
no-unexpected-multiline
禁止出现令人困惑的多行表达式
no-unreachable
禁止在return、throw、continue 和 break 语句之后出现不可达代码
no-unsafe-finally
禁止在 finally 语句块中出现控制流语句
no-unsafe-negation
disallow negating the left operand of relational operators
use-isnan
要求使用 isNaN() 检查 NaN
valid-jsdoc
强制使用有效的 JSDoc 注释
valid-typeof
强制 typeof 表达式与有效的字符串进行比较
Best Practices
这些规则是关于最佳实践的，帮助你避免一些问题:

accessor-pairs
强制 getter 和 setter 在对象中成对出现
array-callback-return
强制数组方法的回调函数中有 return 语句
block-scoped-var
强制把变量的使用限制在其定义的作用域范围内
class-methods-use-this
enforce that class methods utilize this
complexity
指定程序中允许的最大环路复杂度
consistent-return
要求 return 语句要么总是指定返回的值，要么不指定
curly
强制所有控制语句使用一致的括号风格
default-case
要求 switch 语句中有 default 分支
dot-location
强制在点号之前和之后一致的换行
dot-notation
强制尽可能地使用点号
eqeqeq
要求使用 === 和 !==
guard-for-in
要求 for-in 循环中有一个 if 语句
no-alert
禁用 alert、confirm 和 prompt
no-caller
禁用 arguments.caller 或 arguments.callee
no-case-declarations
不允许在 case 子句中使用词法声明
no-div-regex
禁止除法操作符显式的出现在正则表达式开始的位置
no-else-return
禁止 if 语句中 return 语句之后有 else 块
no-empty-function
禁止出现空函数
no-empty-pattern
禁止使用空解构模式
no-eq-null
禁止在没有类型检查操作符的情况下与 null 进行比较
no-eval
禁用 eval()
no-extend-native
禁止扩展原生类型
no-extra-bind
禁止不必要的 .bind() 调用
no-extra-label
禁用不必要的标签
no-fallthrough
禁止 case 语句落空
no-floating-decimal
禁止数字字面量中使用前导和末尾小数点
no-global-assign
disallow assignments to native objects or read-only global variables
no-implicit-coercion
禁止使用短符号进行类型转换

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
