### ISSUE TITLE
使用externals  并不能过滤moment 等个别模块，依然会被打包进来，整个项目打包的文件特别大

### ISSUE THREAD

**Issue by UncleYuan** [sorrycc/roadhog#304]
`

    "externals": {
        "antd": "window.antd",
        "lodash": "window.lodash",
        "react": "window.React",
        "react-router": "window.ReactRouter",
        "react-dom": "window.ReactDOM",
        "moment": "window.moment"
    },
   
`

使用externals  并不能过滤moment 等个别模块，依然会被打包进来，整个项目打包的文件特别大

**Comment by moocss** [comment]
1. 过滤moment问题请在webpack配置文件中添加
```
plugins: [
  new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]
```
2. 当前解决办法是在你的项目根目录中新建`webpack.config.js`, roadhog 是支持通过 webpack.config.js 以编码的方式进行配置，但不推荐这么做。
具体请看https://github.com/sorrycc/roadhog/blob/master/README.md#配置

```
module.exports = function (webpackConfig, env) {
    // 对roadhog默认配置进行操作，比如：
    if (env === 'production') {
      webpackConfig.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/))
    }
}
```

**Comment by hzq001** [comment]
``` JavaScript
const webpack = require('webpack')
module.exports = function (webpackConfig, env) {
    // 对roadhog默认配置进行操作，比如：
    if (env === 'production') {
      webpackConfig.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/))
    }
    return webpackConfig
}
```

@moocss 

缺少了
``` JavaScript  
return webpackConfig
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/4f6379eeb7f3da61f4a7e1ab20dfa5cbe1552da2/webpack.config.js
