### ISSUE TITLE
请问roadhog怎么生成stats.json文件

### ISSUE THREAD

**Issue by jumpdog** [sorrycc/roadhog#305]

**Comment by hzq001** [comment]
roadhog build --analyze

**Comment by 520Yanxiaofei** [comment]
这个就支持html格式生成，有支持json的吗，因为我想在这上面看分析
https://webpack.github.io/analyse/

**Comment by Create-Peace** [comment]
> roadhog build --analyze

roadhog 2 没有生成stats.json?
