### ISSUE TITLE
roadhog build --analyze 

### ISSUE THREAD

**Issue by zhouzefei** [sorrycc/roadhog#306]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）0.5.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）node:6.9.2; npm:3.10.9;
- Operating environment (e.g. OS name) and its version（操作系统版本）:10.11.6

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
roadhog build --analyze 
打包文件

#### What do you expected?（预期的正常效果）
![image](https://user-images.githubusercontent.com/8566935/27267538-c08599f2-54db-11e7-8636-a3613cec8fb7.png)
js实际文件大小190.77kb

#### What happen?（发生了何种非正常现象）
![image](https://user-images.githubusercontent.com/8566935/27267555-d8fb1548-54db-11e7-9f42-71be3ccb68a9.png)
查看js文件大小为700多k

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

@sorrycc

**Comment by sorrycc** [comment]
日志里的是 gzip 之后的，791 -> 190，应该是正常的压缩率。
