### ISSUE TITLE
roadhog@1.0.0-beta.7

### ISSUE THREAD

**Issue by zuiidea** [sorrycc/roadhog#307]
- `webpack-dev-server@2.4.5` 报错   [解决方法](https://stackoverflow.com/questions/40597626/webpack-validateschema-is-not-a-function)

 > webpack.validateSchema is not a function

- 编译速度巨慢，可能是`webpack3`的原因，1.0.0-beta.7与0.6.0-beta.6对比

 > 1.0.0-beta.7 : 108s
 > 0.6.0-beta.6 : 10s内

**1.0.0-beta.7**
![qq 20170619215017](https://user-images.githubusercontent.com/16070518/27288963-ed8c0968-553a-11e7-8900-ba4b441fba85.jpg)

**0.6.0-beta.6**
![qq 20170619215521](https://user-images.githubusercontent.com/16070518/27289007-0f0dc4fa-553b-11e7-8db9-6ad215f592da.jpg)

**Comment by paranoidjk** [comment]
10倍的差距也太大了

**Comment by trexguo** [comment]
同样发现这个问题

**Comment by vipcxj** [comment]
为了兼容其他使用了webpack2的框架，只能使用1.0.0-beta.7，所以还是希望正式版能早点出来~ 或者有办法让不同依赖使用独立的不同版本的webpack？

**Comment by sorrycc** [comment]
重装下试试，最新的 webpack@3.4 性能上明显提升，详见：https://github.com/sorrycc/roadhog/pull/278

**Comment by zuiidea** [comment]
快了很多，相同的项目
![image](https://user-images.githubusercontent.com/16070518/28668012-90c5b07e-7300-11e7-8a93-b81e634e0713.png)
