### ISSUE TITLE
mock配置文件import自己写的其他js文件中不能import其他文件

### ISSUE THREAD

**Issue by vipcxj** [sorrycc/roadhog#310]
#### Environment(required) | 环境（必填）

- roadhog version 0.6
- Nodejs and Npm version v7.9.0/4.2.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: macOS Sierra 10.12.5

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
.roadhogrc.mock.js中可以正常import位于npm管理下的第三方库。但若是import了自己写的模块，比如src下的某个js文件，比如a.js，要分2种情况讨论。
1. a.js没有import任何东西，也就是说a.js是个不依赖任何其他模块的模块，那么一切正常。
2. a.js依赖自己写的某个模块，比如src下的b.js，只要b.js使用了较新的语法，那么mock config编译失败。好似b.js压根没被babel编译过一样。
3. a.js依赖于其他模块，但是npm下的模块， 那么同样一切正常。我认为这和2的区别在于npm上的模块都是用babel编译过的最终文件。
报错信息：
Failed to parse mock config
Error in Unexpected token import
/path/to/b.js:1
import moment from 'moment';
SyntaxError: Unexpected token import

#### What do you expected?（预期的正常效果）
当然是希望mock文件中能正常import我自己写的其他文件，而不是直接报错

#### What happen?（发生了何种非正常现象）
什么现象上面已经说了

update：
我发现不止是import，在b.js中很多新语法都不支持，比如export被认为是非法的。所以我猜测可能的原因是mock本身是支持了es6语法，直接import的文件也支持，但更深的依赖的文件就属于没被babel编译过的了，或者说可能编译mock.js太早了，那时src下的文件还没被编译，所以import的是原始文件，而非babel编译后的文件，导致出了这个问题。所以还有没有救？

#### Re-producible online demo (可复现的在线demo)
这个问题发生在编译阶段，无法在线复现。

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by vipcxj** [comment]
顺便提一句，这个问题0.5.4中已经遇到，今天我更新到6.0，问题依旧，实在忍不了了，才来提交issue

**Comment by vipcxj** [comment]
1.0问题依旧，使用babel-register也完全没有任何作用~

**Comment by vipcxj** [comment]
用babel-register+自定义require钩子搞定了，之前没作用是因为roadhog已经require过babel-register，由于cache的原因，我再次require也不会执行注册require钩子的代码。

**Comment by sorrycc** [comment]
可以放在 `mock` 文件夹里，这里面的都会走 babel 编译的。https://github.com/sorrycc/roadhog/blob/fd65abd/src/utils/registerBabel.js#L4

**Comment by vipcxj** [comment]
所以只有那3个目录的文件会被babel编译吗？但是这样没法解决我的需求啊，因为有部分代码是src下的，也就是mock会用到不少生产环境下的代码。我觉得至少把src也加进babel的编译目录吧~ 还有如果引用的第三方库如果是没编译的，岂不是也要杯具。所以如果这个babel编译的目录范围可以配置或者干脆不设限制更好点~
