### ISSUE TITLE
how to add hash code in production env

### ISSUE THREAD

**Issue by chenkang084** [sorrycc/roadhog#311]
since we need clean cache via hash file name ,how to add hash code in  **.roadhogrd** or **webpack.config.js**

**Comment by MrChongdong** [comment]
webpack.config.js
![image](https://user-images.githubusercontent.com/20316147/27507876-de2ed354-590b-11e7-9273-16144ae9b98a.png)

**Comment by chenkang084** [comment]
thx for your solution, it can generate three *.js files, looks good.
![Alt text](https://raw.githubusercontent.com/chenkang084/notes/master/imgs/others/hash-issue.png)
but how could we inject the files into index.html by **roadhog** ,just like using 
```
new HtmlWebpackPlugin({
            filename: './index.html',
            template: __dirname + "/src/index.html"
        }),
```
i have tried to config **HtmlWebpackPlugin **, but failed .
could you show me how to inject hash file dynamically ?

**Comment by MrChongdong** [comment]
when use html-webpack-plugin in roadhog, error: Cannot read property '0' of undefined
So I wrote a business-related plugin
My English is not good

**Comment by chenkang084** [comment]
我这边可以正确添加**HtmlWebpackPlugin**，但是，添加进去之后，没法正常读到 index.html。我试了很久，大概是 roadhog 用的是file loader处理html。我在我以前的项目中，用的是 html-loader 处理index.html ，这样是正常的。
方便留个qq/email/wechat,我们可以一起探讨。

**Comment by MrChongdong** [comment]
使用 HtmlWebpackPlugin 应该和 html-loader 无关吧, 我没用过这个 ,html-loader 不是用来处理 import 到 js 里面的 html 文件的吗?

**Comment by trexguo** [comment]
```
new HtmlWebpackPlugin({
            filename: './index.html',
            template: __dirname + "/src/index.html",
            inject: true
}),

```

> inject: true | 'head' | 'body' | false Inject all assets into the given template or templateContent - When passing true or 'body' all javascript resources will be placed at the bottom of the body element. 'head' will place the scripts in the head element.

**Comment by chenkang084** [comment]
i have tried the method before .but failed. have you successfully use the solution ?
could you share me the **url** or **screenshot** ?

**Comment by MrChongdong** [comment]
What the roadhog version do you use? @trexguo

**Comment by chenkang084** [comment]
@MrChongdong    似乎解决了。参考[231](https://github.com/sorrycc/roadhog/issues/231)
