### ISSUE TITLE
希望能支持html-webpack-plugin,和 chunkhash 输出

### ISSUE THREAD

**Issue by MrChongdong** [sorrycc/roadhog#312]
希望能支持html-webpack-plugin,和 chunkhash 输出

**Comment by MrChongdong** [comment]
利用 webpack.config.js 的方法引入使用 html-webpack-plugin 时报错, 升级到最新版本
<img width="662" alt="qq20170624-183248 2x" src="https://user-images.githubusercontent.com/20316147/27507865-a4cbcbda-590b-11e7-8f28-51d564f9727e.png">
我的写法
![image](https://user-images.githubusercontent.com/20316147/27507881-f3f26f8e-590b-11e7-9661-ff1e1e08bd48.png)

**Comment by chenkang084** [comment]
+1

**Comment by AlaiNiGuests** [comment]
+1

**Comment by sorrycc** [comment]
已支持。
