### ISSUE TITLE
antd 对应css 如何从js里提取？

### ISSUE THREAD

**Issue by huyawei** [sorrycc/roadhog#313]
默认的loader 目前css是根据引用的组件自动打包到对应的js文件里
有什么办法提取到[name].css 里吗

**Comment by huyawei** [comment]
{
      disable: false,
      allChunks: true
    }

**Comment by YuriTu** [comment]
@huyawei 兄弟你这个配置是在哪里加的？roadhogrc？

**Comment by huyawei** [comment]
@YuriTu 可以自己添加一个webpack.config.js

**Comment by sorrycc** [comment]
默认是开发状态下内联在 js 里，生成环境下提取到 css 里的。

**Comment by huyawei** [comment]
@sorrycc  我没记错的话 生产环境的确还是在js里的 然后参照了下以前atool-build的配置 找到上面的方法
在 webpack.config.js 里 遍历了一遍loader把 {disable: false,allChunks: true} 加了进去

**Comment by YuriTu** [comment]
@sorrycc 作者你好，我采用roadhog默认配置进行build，发现antd里面所有的css都没有了，并没有提取到生成css中，生成的css中只有我自己写的css

**Comment by sorrycc** [comment]
prod 的 css 全部抽出来的，https://github.com/sorrycc/roadhog/blob/f27eadb/src/config/webpack.config.prod.js#L64

**Comment by huyawei** [comment]
@sorrycc  刚才做了下测试 的确没问题， 这就尴尬了我之前测试的时候  prod的确还在js里，难道是缓存，不纠结了 现在没问题就好

**Comment by huyawei** [comment]
不知道是哪里的配置影响
新项目
npm run build 
默认配置不能提取css

{
disable: false,
allChunks: true
}
还是得加这个
