### ISSUE TITLE
多页类型在打包时可以实现为单页独立打包吗？

### ISSUE THREAD

**Issue by gafish** [sorrycc/roadhog#316]
我的 roadhogrc 配置的入口是这样的

"entry": "src/*.js",
"multipage": false,
"outputPath": "./build",

入口文件在目录中是这样

src
    admin.js
    home.js

目前的情况是，执行 roadhog build 所有页面不管是否需要都要打包一次，速度极慢。

如果把入口改成 "entry": "src/admin.js" 为每个页面单独做打包，后一次打包将覆盖前一次打包的 build 目录，导致前面打包的文件丢失。

是否可以增加为多页类型中每个页面独立打包的选项呢？

**Comment by sorrycc** [comment]
多页类型为啥要配成单页打包？

**Comment by sorrycc** [comment]
这个 issue 时间太久了，先关闭，有问题再 reopen 。

**Comment by gafish** [comment]
@sorrycc 好的，我试试自己去开发这个功能
