### ISSUE TITLE
临时环境变量BROWSER不起作用

### ISSUE THREAD

**Issue by kanweiwei** [sorrycc/roadhog#318]
-roadhog version
0.5.2

临时环境变量BROWSER的设置不起作用，在0.5.x的版本中，引用了yargs模块，并对BROWSER默认设置为true，但是下面打开浏览器时没有判断临时变量BROWSER的值。

> if (argv.open) {
>       openBrowser(`${protocol}://${host}:${port}/`);
>     }
建议改为
```
argv.open = process.env.BROWSER === 'none' ? false: true;
if (argv.open) {
    openBrowser(`${protocol}://${host}:${port}/`);
}
```
0.6.0的版本中，yargs删去了option方法的调用，下面的argv.open的判断也删掉了，如果改成上面的，似乎就没必要删了。

**Comment by sorrycc** [comment]
判断是加在 openBrowser 里面的。
