### ISSUE TITLE
roadhod build前加自定义环境变量打包错误

### ISSUE THREAD

**Issue by fe719319448** [sorrycc/roadhog#320]
#### Environment(required) | 环境（必填）

- roadhog version 0.6.0
- Nodejs  6.10.2 npm 3.10.10
- mac osx

package.json中的定义

    "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "server": "cd server && json-server db.json -w -p 3000",
    "dev": "BROWSER=none roadhog server",
    "totest": "NODE_ENV=totest roadhog build",
    "build": "roadhog build"
  },

.roadhgrc 中定义

    {
  "define" : {"NODE_ENV": "totest"}
}

运行 npm run totest  中打包出来的是开发版本
![image](https://user-images.githubusercontent.com/12410764/27668011-19c9d10e-5cb1-11e7-9abc-73018982d221.png)

运行 npm run build 打包的文件小很多，也是正常运行的版本，求解
![image](https://user-images.githubusercontent.com/12410764/27668002-0fddd820-5cb1-11e7-9456-d765a645d637.png)

**Comment by sorrycc** [comment]
只有是 production 时才会打生成版本。

**Comment by sosout** [comment]
@sorrycc  我们公司项目使用docker、Jenkins一键打包构建项目，其中测试库，预发库、生产库唯一不同的是接口的url，由于环境变量无法自定义，导致我们无法区分是哪个环境，该使用哪个接口。强烈建议打包环境可以自定义。谢谢roadhod团队。

**Comment by zhaoxj** [comment]
module.exports = (webpackConfig, env) => {}
所以这里的env还是不能动态的通过roadhog打包命令配置？打包出来的环境只能是production？

**Comment by colinzhy** [comment]
@sosout 方便交流一下你们是用什么方案在启动docker容器的时候配置URL的？
