### ISSUE TITLE
import 'mongoose'  and  occur Infinite loop

### ISSUE THREAD

**Issue by Syzmex** [sorrycc/roadhog#324]
#### Environment(required) | 环境（必填）

- roadhog version: latest
- Nodejs and Npm version: latest
- Operating environment (e.g. OS name) and its version: mac latest

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
import 'mongoose' in mock file

#### What do you expected?（预期的正常效果）
work normally

#### What happen?（发生了何种非正常现象）
Infinite loop

#### Re-producible online demo (可复现的在线demo)
none

Probably the mistake here：
https://github.com/sorrycc/roadhog/blob/master/src/utils/mock.js#L25

**Comment by vipcxj** [comment]
mock配置的毛病蛮多的样子，babel-register的注册疑似有问题，导致mock文件深层require的文件没有被babel编译过。我自己重新注册也没什么卵用，疑似是require cache的问题。所以我直接拷贝babel-register源码，import我自己的拷贝版就可以了，但是又引入新问题，roadhog源码中已经替换了require，babel-register也替换了require，两者就这样冲突了~ 目前我根据roadhog源码，稍微改了下，让2者同时发生作用，貌似可以正常工作，不过这做法实在很不优雅~ 如果lz觉得是require cache的问题，可以试试require之前先清除掉对应cache，甚至直接实现自己的require hook

**Comment by Syzmex** [comment]
@vipcxj 
由于 roadhog 问题较多，我就自己看着重写了一个开发服务器，我在移植mock代码的时候发现了这个问题，我就稍微改了一下，大概思路是删除产生变化的 require.cache，再 require，或许 @sorrycc 的想法是更新所有相关的文件会比较好吧。
欢迎交流 https://github.com/Syzmex/kiwiai/blob/master/src/utils/mock.js#L15-L42

**Comment by vipcxj** [comment]
我觉得babel-register的配置应该没有问题，因为直接require babel-register没有效果，原封不动照搬babel-register的源码到我自己的文件babel-register.js，然后require ./babel-register，就可以正常编译了。所以我猜觉得是之前roadhog 已经调用过babel-register，但不知道什么时候require被替换成非babel-register提供的require了，我再次require，因为有require cache，并且babel-register中的require hook只执行一次，所以没有生效。babel-register导出的对象只是为了进行配置，但并不会再次require hook，require hook只发生在第一次import。
但是奇怪的是我看源码中，roadhog在getConfig中hook require时，有先保存real require，然后再hook中调用real require，如果real require是 babel-register提供的require，不应该编译不了，只能说问题可能出在其他地方吧~ 关于这个问题我又提交issure: https://github.com/sorrycc/roadhog/issues/310
事实上.roadhog.mock.js本身是可以使用import的，但.roadhog.mock.js import的module有import就会报错，也就是.roadhog.mock.js中使用的require已经不是babel-register提供的了。.roadhog.mock.js中我可没进行过require hook~
