### ISSUE TITLE
mock 中对于转发到其他 url 的不应该解析 request body

### ISSUE THREAD

**Issue by Alex1990** [sorrycc/roadhog#325]
**问题出现步骤：**

- 发送 POST 请求，`Content-Type`为`x-www-form-urlencoded`
- mock 中配置

```
module.exports = {
  'POST /api/templates': 'http://dev.somedomain.com',
};
```

- 目前 roadhog 的 mock 会解析出`req.body`
- 然后 express-http-proxy 当中
  - https://github.com/villadora/express-http-proxy/blob/c0c8dbd54a6bbef8b773a69c30c0bb69d9e9d536/index.js#L327 这里如果存在`req.body`，则不会获取原始的 reqeust body，
  - 再然后，https://github.com/villadora/express-http-proxy/blob/c0c8dbd54a6bbef8b773a69c30c0bb69d9e9d536/index.js#L296 如果`req.body`是个`Object`，就会当作 JSON 字符串来处理，这样发送到服务器就会出现问题。

**总结**

对于 mock 文件当中，如果 key-value 的 value 不为函数，则不应该解析 request body。

**Comment by vipcxj** [comment]
你可以写成函数啊，貌似value不为函数只是提供了一个返回json格式的快速简便写法，因为express的api中并没有直接传个object当返回值的写法。

**Comment by vipcxj** [comment]
不过现在最大的问题是作者貌似不见了，issure越堆越多，commit也是很久前的了

**Comment by Alex1990** [comment]
@vipcxj 请你看懂我得问题再评论

**Comment by vipcxj** [comment]
你的问题不就是向在mock里面搞proxy吗？说白了作者在mock里加了这个功能只是锦上添花，简单的需求可以更快捷地实现，但像你这种更复杂的需求，在roadhogrc.js里配置proxy不就行了～

**Comment by sorrycc** [comment]
```
module.exports = {
  'POST /api/templates': 'http://dev.somedomain.com',
};
```

这个跳转的功能有问题，先不要用。
