### ISSUE TITLE
各种折腾：Failed to parse .roadhogrc config.  Unexpected token export

### ISSUE THREAD

**Issue by GreenAppleOne** [sorrycc/roadhog#329]
#### Environment(required) | 环境（必填）

- roadhog version：0.6.0

- Nodejs and Npm version（Nodejs 和 Npm 版本）
Nodejs :8.1.4  
Npm:5.0.3

- Operating environment (e.g. OS name) and its version（操作系统版本）:
Mac系统

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

antd-admin 项目或者新建一个项目，只要去掉 .roadhogrc ,增加 .roadhogrc.js 就会出现这个错误

我同事可以运行这个项目就我的不可以，应该和项目本身没有关系，我把所有的js相关的全局安装的包都删除掉 包括node ，都不行。就差重装系统了。

我看到Issues 有人遇到这个问题，说是版本的问题的，不清楚到底是那个安装包版本的问题。
项目本身代码配置是没有问题的，这一点我确定。不清楚这个错误到底跟什么有关系呢？
万分感谢！

**Comment by GreenAppleOne** [comment]
@sorrycc 能帮忙看一下吗？

**Comment by huyawei** [comment]
作者似乎很久没冒过泡了-  -什么鬼

**Comment by YuriTu** [comment]
作者似乎主要精力在DVA那边...

**Comment by GreenAppleOne** [comment]
@YuriTu  关键dva也bug一堆，没人接单，dva-cli那么明显的bug 也不修复。都不知道干嘛呢

**Comment by pigcan** [comment]
是不是不支持 es6 语法

**Comment by sorrycc** [comment]
`.roadhogrc.js` 里写了啥?

**Comment by GreenAppleOne** [comment]
@sorrycc 
const path = require('path')

const svgSpriteDirs = [
  path.resolve(__dirname, 'src/svg/'),
  require.resolve('antd').replace(/index\.js$/, ''),
]

export default {
  entry: 'src/index.js',
  svgSpriteLoaderDirs: svgSpriteDirs,
  "theme": "./theme.config.js",
  // 接口代理示例
  // "proxy": {
  //   "/api/v1": {
  //     "target": "http://api.zuiidea.com",
  //     "changeOrigin": true,
  //     "pathRewrite": { "^/api/v1" : "/v1" }
  //   },
  //   "/api/v2": {
  //     "target": "http://192.168.0.110",
  //     "changeOrigin": true,
  //     "pathRewrite": { "^/api/v2" : "/api/v2" }
  //   }
  // },
  "env": {
      "development": {
        "extraBabelPlugins": [
          "dva-hmr",
          "transform-runtime",
  		    ["import", { "libraryName": "antd", "style": true }]
        ]
      },
      "production": {
        "extraBabelPlugins": [
          "transform-runtime",
  		    ["import", { "libraryName": "antd", "style": true}]
        ]
      }
  }
}

**Comment by GreenAppleOne** [comment]
不能识别 export

Failed to parse .roadhogrc config.

Unexpected token export

**Comment by sorrycc** [comment]
看不出问题，我们项目也在用 `.roadhogrc.js` 的，没出现过问题。方便的话可以给个能重现的源码包，另外也可以把 node 换成 6 试试（还没在 node@8 里跑过）。

**Comment by sorrycc** [comment]
难道是 babel 转换没生效，试试 `export default {}` 改成 `module.exports={}` 呢?

**Comment by GreenAppleOne** [comment]
改成 module.exports 可以编译成功了，接着报这个错误
The app is running at:

  http://localhost:8000/

Note that the development build is not optimized.
To create a production build, use npm run build.

Failed to parse mock config.

Error in Unexpected token import
/Users/HH/Documents/js-workspace/antd-admin/src/mock/dashboard.js:1

(function (exports, require, module, __filename, __dirname) { import { color } from '../utils/theme'
                                                              ^^^^^^

SyntaxError: Unexpected token import


之前node换成6了，也不行，这个跟项目没关系，这个项目在同事的电脑上面是正常的，真是邪门了

**Comment by sorrycc** [comment]
mock 的也和这个是同一问题，感觉和你本机的 babel 配置有关。

**Comment by GreenAppleOne** [comment]
我没有全局安装  babel 配置 我装个试试，谢谢你的回复

**Comment by vipcxj** [comment]
我也遇到类似问题，我有提交[issure310](https://github.com/sorrycc/roadhog/issues/310)。但不同的是.roadhogrc.mock.js就算使用import和export也不会出问题，也就是说.roadhogrc.mock.js确实被babel编译了，所以我觉得这不应该是babel配置的问题。

**Comment by sorrycc** [comment]
仔细看 issue，不是同一问题。

**Comment by MinJieLiu** [comment]
registerBabel.js 中
```js
if (process.env.NODE_ENV !== 'test') {
  require('babel-register')({
    only: /(webpack.config.js|.roadhogrc.js|.roadhogrc.mock.js|mock\/)/,
  });
}
```
限制了只对配置文件进行转码。在  .roadhogrc.js 中再 `import` 其他 ESM 模块就不会被解析。只能 `import` 其他 CommonJS 模块。对吧😀

**Comment by vipcxj** [comment]
这个限制有点坑，可不可以去掉~

**Comment by sorrycc** [comment]
不可能所有文件都走 babel 编译实时的，性能上会很慢。

**Comment by vipcxj** [comment]
然而monk涉及的文件应该不会太多吧，而且这里便捷比性能更重要点吧~ 总不能就因为这个性能问题，已经写过一遍的代码，必须再写一遍，如果这个代码又引用了很多其他东西，那就更杯具了

**Comment by MinJieLiu** [comment]
在编译时需要引入的，一般都是一些与代码共享的配置文件，那点性能影响可以忽略不计。如果要再写一遍，那成本就高了。这个坎我觉得还是交给使用者来解决吧😊

**Comment by sorrycc** [comment]
放开后所有依赖都会走 babel 编译，包括 webpack 等依赖。。没人这样用的。

**Comment by vipcxj** [comment]
但实际操作其实没那么影响性能，限制了反而影响使用~ 毕竟这又不会影响生产环境的性能，最多影响开发环境的性能~ 而且还仅仅是mock部分的性能~

**Comment by sorrycc** [comment]
mock 相关的放在 mock 文件夹不就好了? 为啥要放其他文件夹？

**Comment by vipcxj** [comment]
同样的代码又不一定只有mock用到，总不能为此特意写2遍

**Comment by sorrycc** [comment]
举个具体的例子？什么情况下 mock 和 src 需要复用？

**Comment by vipcxj** [comment]
全局配置文件，还有一些工具类

**Comment by MinJieLiu** [comment]
`webpack` 等依赖会被走实时编译，不能全局放开，或者 放开  对 `src` 目录的限制？

**Comment by sorrycc** [comment]
> 放开 对 src 目录的限制？

好建议。

**Comment by vipcxj** [comment]
@sorrycc 不给可选配置只能定死，是怕先有鸡先有蛋的问题吧，如果在加个json格式的配置文件，只支持json格式，不就可以可以配置对配置文件的读取了~

**Comment by sorrycc** [comment]
约定优于配置，能约定就不走配置了。

**Comment by chengzhenping** [comment]
![image](https://user-images.githubusercontent.com/6301471/33931407-d89530ae-e02a-11e7-958e-da09686289b4.png)

我这里roadhog build就不支持.js啊啊啊  ,roadhog server支持.js配置
@sorrycc

**Comment by kuake** [comment]
@sorrycc 
我改了下src的名字，然后就报：
`Failed to parse mock config.

Error in Unexpected token import
/home/mi/ws/zlex/ppa/ppaCode/front_src/mock/dashboard.js:1

(function (exports, require, module, __filename, __dirname) { import { color } from '../utils/theme'
                                                              ^^^^^^

SyntaxError: Unexpected token import`

这个src名字不可以改吗？或者有什么地方可以配置下？

**Comment by kuake** [comment]
控制的太死，约定的应该是大家都知道的事，而且应该支持自定义配置内容的，特别是目录结构什么的。约定优于配置不是什么都不能自定义
