### ISSUE TITLE
roadhog build过慢

### ISSUE THREAD

**Issue by riverslob** [sorrycc/roadhog#330]
目前项目使用dvajs框架开发，动态加载。已经在70个module.
使用roadhog build目前超过20分钟时间，为防止内存溢出已经增大到了4G。

目前build时间和所需内存随着module增多还在不停增加。

请问这块有什么优化办法。

如果没有优化办法，有这块的计划吗？

或者有什么替代roadhog的方案？

**Comment by marginyu** [comment]
同问

**Comment by sorrycc** [comment]
- 大部分时间应该是消耗在压缩上，`roadhog build --debug` 应该是比较快的吧？
- `roadhog build --analyze` 分析看看是否有不需要的依赖

**Comment by riverslob** [comment]
谢谢

**Comment by sorrycc** [comment]
重新安装 roadhog 试试，背后依赖的 webpack@3.4 有较大性能提升。

**Comment by LDD123** [comment]
请问如何增加内存，直接  roadhog build --max_old_space_size=4096   这样吗

**Comment by superlbr** [comment]
期待webpack@4能有较大提升，有时候着急修个bug啥的，build。。。

**Comment by leohxj** [comment]
> 请问如何增加内存，直接 roadhog build --max_old_space_size=4096 这样吗

`node --max_old_space_size=4096 node_modules/roadhog/bin/roadhog build`
