### ISSUE TITLE
relay

### ISSUE THREAD

**Issue by bucaixiaot** [sorrycc/roadhog#331]
roadhog中怎么配置使用relay

**Comment by sorrycc** [comment]
抱歉，我对 relay 不了解，不过 roadhog 作为一个打包方案，应该和使用什么框架无关。

**Comment by bucaixiaot** [comment]
@sorrycc 对，没有关系,roadhog没有报错，relay的问题，relay的启动需要特殊的环境,我快折腾好了,不过也谢谢
