### ISSUE TITLE
项目根目录下的mock文件夹的作用？

### ISSUE THREAD

**Issue by huang6349** [sorrycc/roadhog#333]
我使用了最新版的dva-cli生成了一个新的项目，发现项目根目录下有个mock文件夹，我尝试在文件夹中写了一段请求，
`export default {
  'GET /api/user'(req, res) {
    res.json({ message: 'get success' });
  },
};
`

使用 http://localhost:8000/api/user 进行访问无法获得数据，同样的代码在.roadhogrc.mock.js中却能获得数据，请问大神这个mock文件夹是如何使用的？

**Comment by sorrycc** [comment]
可以在 .roadhogrc.mock.js 里 require mock 文件夹里的文件，mock 文件夹会走 babel 编译，可以用 es6 语法。

**Comment by huang6349** [comment]
原来是这样，我明白了，需要将mock文件夹中的js引入到.roadhogrc.mock.js中是吧，感谢大神的指导。
