### ISSUE TITLE
roadhogrc打包部署后，mock没被一起打包

### ISSUE THREAD

**Issue by wuyunjiang** [sorrycc/roadhog#334]
在本地开发时可以正常使用，打包部署到服务器后，mock就没效果
看了打包后的文件，应该是没有被一起打包
有时候只是想做个Dome放到服务器做简单的演示，还是想使用mock的数据，不想写后台连接数据库
不知道有什么好的方法，

或者可以让mock一起被打包过去，然后在服务器上做一些简单的配置，就能正常跑起来

#### Environment | 服务器环境

- roadhog version : 0.6.0-beta3

- Nodejs and Npm version : 7.8.0   &  4.2.0

- Operating environment (e.g. OS name) and its version（操作系统版本）
CentOS Linux release 7.2.1511 (Core)

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
在线演示地址：http://project.wuyunjiang.cn/CXF/
项目源码地址：https://github.com/wuyunjiang/CXF

#### What do you expected?（预期的正常效果）
能正常登录，显示数据

#### What happen?（发生了何种非正常现象）
控制台打印错误
请求路径404

**Comment by sorrycc** [comment]
mock 是测试用的，打包自然不会包含了。

**Comment by wuyunjiang** [comment]
我知道是开发时用的，不会包含，我是说能不能，让我们选择是否包含进去，可以默认不包含，通过改变配置项让它包含进去，因为毕竟也有这种需求

**Comment by trexguo** [comment]
@wuyunjiang mock模拟的是服务端提供的接口。打包打的是静态资源，部署的时候要放在web服务器下。就算打包在一起，你mock的数据有谁驱动？你再仔细想想。

**Comment by wuyunjiang** [comment]
好吧，最后选着了使用json-server，做了个笔记，希望能帮到后面有这种（只是想做个Dome放到服务器做简单的演示，使用mock的数据，不想写后台连接数据库）需求的朋友
[服务器使用mock](http://wuyunjiang.cn/blog/article/20177241)

**Comment by hanzhangyu** [comment]
> 背景：开发环境打包的静态文件部署在nginx服务器，但是需要使用部分mock。我不希望mock出现在我的生产环境，也不想在我的生产环境去修改我的代码。当然有更好的解决方案，期待你的提醒，3Q

webpack配置文件，加上mockData
```js
  webpackConfig.plugins = webpackConfig.plugins.concat([
    new HtmlWebpackPlugin({
      template: `${__dirname}/src/entry.ejs`,
      filename: 'index.html',
      minify: production ? {
        collapseWhitespace: true,
      } : null,
      hash: true,
      headScripts: production ? [] : ['/roadhog.dll.js'],
      mockData: production ? null : JSON.stringify(require('./.roadhogrc.mock.js')),
    }),
  ]);
```
模板文件插入
```html
 <% if (htmlWebpackPlugin.options.mockData) { %>
  <script>
    window.__mockData__ = JSON.parse('<%= htmlWebpackPlugin.options.mockData %>');
  </script>
  <% } %>
```
request修改
```js
const {url, options} = getOptions(params);
  let response;
  let data;
  if (/^\/api/.test(url)) {
    /* global window */
    data = window.__mockData__[`${options.method} ${url}`];
  } else {
    response = await fetch(url, options);
    checkStatus(response);
    data = await response.json();
  }
```
