### ISSUE TITLE
mock文件修改之后获取到的还是之前的版本

### ISSUE THREAD

**Issue by DrakeXiang** [sorrycc/roadhog#335]
#### Environment(required) | 环境（必填）

- roadhog version: 0.5.2
- Nodejs and Npm version: node: 6.9.2, npm: 4.1.2
- Operating environment (e.g. OS name) and its version（操作系统版本）: windows 10.0.15063

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
```
// .roadhog.mock.js
const mock = {}
let files = require('fs').readdirSync(require('path').join(__dirname + '/mock'));

files.forEach(function (file) {
  Object.assign(mock, require('./mock/' + file))
})

module.exports = mock
```
加载之后修改mock文件夹里的mock数据

#### What do you expected?（预期的正常效果）
页面应该获取到修改后的新数据

#### What happen?（发生了何种非正常现象）
roadhog.mock.js不会重新执行，也就不会获取修改后的数据

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by dicklwm** [comment]
升级到0.6.0试下

**Comment by sorrycc** [comment]
这是一个可以改进的点。mock 文件夹目前不会动态生效，只有 `.roadhog.mock.js` 可以。

**Comment by sorrycc** [comment]
升级到最新版试试，测了下发现没有问题。
