### ISSUE TITLE
support bundle-loader 

### ISSUE THREAD

**Issue by karzanOnline** [sorrycc/roadhog#337]
require.ensure使用起来比较繁琐，建议使用bundle-loader集成，同时.roadhogrc的配置中添加开关。

Require.ensure more cumbersome to use, it is recommended to use bundle-loader integration, while .roadhogrc configuration to add the switch.

**Comment by yautah** [comment]
+1
不过貌似得支持webpack2了才行？

**Comment by vipcxj** [comment]
1.0.0的beta版已经用webpack3.0了，不过不知道什么时候才能正式发布~
