### ISSUE TITLE
roadhog build 生产环境打包 文件夹拷贝问题

### ISSUE THREAD

**Issue by pmg1989** [sorrycc/roadhog#338]
roadhog build打包时，我使用了`copy-webpack-plugin`，也已经把 outputPath 配成另一个目录，然后想build 完 copy 过去，但一直报错`Module build failed: Error: Plugin 5 specified in "base" provided an invalid property of "apply" at Plugin.init`，请问是这块的配置有问题么，还望指教，谢谢！
![image](https://user-images.githubusercontent.com/13361827/28557387-addd38f8-713e-11e7-8ea2-0f1fca1bb3c6.png)

**Comment by sorrycc** [comment]
别用 CopyWebpackPlugin，在 roadhog build 完了之后用其他命令，比如 `cp` 进行复制。

**Comment by pmg1989** [comment]
原来如此，了解了，感觉这这块的处理，是不是丢给roadhog来做会更好些呢，我们也不是很希望，每次build后都来个copy命令吧

**Comment by sorrycc** [comment]
你这是特殊的场景，就特殊处理吧，通常不会 serve dist 目录的。

**Comment by lizy0329** [comment]
可以使用这个 filemanager-webpack-plugin
