### ISSUE TITLE
outputPath非默认值且public目录不为空时build

### ISSUE THREAD

**Issue by zuiidea** [sorrycc/roadhog#341]
#### 复现步骤
- roadhog版本`1.0.0-beta.7`
- outputPath非默认值，如`./dist/1.0.0`
- public目录下有文件
- roadhog build

#### 结果
```
EISDIR: illegal operation on a directory, open 'c:\web\sube\dist\1.0.0'

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
...
```

![qq 20170729230328](https://user-images.githubusercontent.com/16070518/28745798-704ef586-74b2-11e7-8672-cd89c577cbcc.jpg)

**Comment by zuiidea** [comment]
目前的解决方法是
- 新建一个目录作为public的目录
- 使用copy-webpack-plugin插件复制到指定目录

**Comment by sorrycc** [comment]
手动创建 `dist/1.0.0` 目录，`mkdir -p dist/1.0.0 && npm run build` 试试呢?
