### ISSUE TITLE
Icon不显示问题

### ISSUE THREAD

**Issue by luajoy** [sorrycc/roadhog#343]
### dva项目使用antd-mobile，引用src/assets/中的svg图标的时候，会报错：
 Icon props.type is invalid, have you set svg-sprite-loader correctly? see https://goo.gl/kN8oiw

引入svg-sprite-loader后还是报这个错。
dva项目需要怎么配置svg-sprite-loader？如何正确使用svg图标？谢谢

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog#svgspriteloaderdirs

**Comment by luajoy** [comment]
@sorrycc 按照文档在dva项目中创建.roadhogrc.js文件并配置svg图标路径，但是引用svg图标的时候还是报错，我的引用是：

/* Tab图标 */
.icon_account{
  width: 0.44rem;
  height: 0.44rem;
  background: url(**../assets/tabs/account.svg**) center center /  0.42rem 0.42rem no-repeat
}
刚学习dva，水平很差，麻烦前辈了，谢谢

**Comment by luajoy** [comment]
问题同 #345
