### ISSUE TITLE
model缓存无法清除

### ISSUE THREAD

**Issue by DrakeXiang** [sorrycc/roadhog#344]
#### Environment(required) | 环境（必填）

roadhog version: 0.5.2
Nodejs and Npm version: node: 6.9.2, npm: 4.1.2
Operating environment (e.g. OS name) and its version（操作系统版本）: windows 10.0.15063

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
貌似无法稳定重现，最近几天碰到两次，大概问题是在index.js注册 model 的时候打错了，比如 section 写成了 setion，自动刷新之后报错，改正之后还是报的找不到 setion 这个文件，之后的对应关系就都乱了，但 section 一定是对应 setion 的，我怀疑是webpack还是什么的有缓存，但我重启roadhog也没用，现在只能用 setion 这个文件才能正常加载

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
需要清下 babel-loader 的缓存，`rm -rf node_modules/.cache/babel-loader`。

**Comment by DrakeXiang** [comment]
@sorrycc 谢大佬，清了之后重启server才好了
