### ISSUE TITLE
antd-mobile + Icon props.type is invalid

### ISSUE THREAD

**Issue by lilonghe** [sorrycc/roadhog#348]
win 10
dva 1.2.1
antd-mobile 1.6.0
roadhog 0.6.0
svg-sprite-loader 0.3.1

.roadhogrc.js已配置，.roadhogrc已删除

```
Icon props.type is invalid........
```

**Comment by zuiidea** [comment]
到roadhog的安装目录

`npm i svg-sprite-loader@0.3.0`


@sorrycc ，对了，roadhog@1.0.0-beta.7里

` "svg-sprite-loader": "^3.0.2"`

未做相应处理，如果使用了antd-mobile，antd-mobile的Icon组件会报此错

**Comment by lilonghe** [comment]
@zuiidea  thanks
dva创建项目自带的 roadhog 版本低
我升级的是全局的
