### ISSUE TITLE
关于Webpack 中 Alias别名功能，想用又不敢用？？

### ISSUE THREAD

**Issue by dkvirus** [sorrycc/roadhog#349]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）：0.6.0-beta.6
- Nodejs and Npm version（Nodejs 和 Npm 版本）：node 6.9.5 + npm 3.10.10 
- Operating environment (e.g. OS name) and its version（操作系统版本）: Window7

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
- 在代码编写过程中，之前一直使用相对路径，像这样：```  ../../../../Models ```；
- 后来需要变换目录位置的时候需要一一修改路径很是麻烦，就想着使用绝对路径，像这样：``` D:\work\antd-admin\Models ```；
- 但如果把项目跟目录的位置换一下，比如从 d 盘移动到 e 盘，就要改路径；
- 在 Webpack 配置文章中找到了 alias 属性，可以把根目录配置给一个变量，之后就换从 d 盘移动到 e 盘，也只需要改 webpack.config.js 文件即可；
- 可是 Roadhog 官网又强烈建议不要使用 Webpack，所以现在项目中不敢使用，担心后面 roadhog 更新后直接不能用到时影响更严重。

#### What do you expected?（预期的正常效果）

期望 roadhog 的配置文件能提供 webpack 中 allias 属性的功能，设置路径。

或者直接明确以后 roadhog 更新不会影响到 webpack 中  alias 属性。真的很纠结。

#### What happen?（发生了何种非正常现象）

roadhog 官网说不推荐使用 webpack，倒不如直接说就不准用 webpack 来的果断。

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
可以用 https://www.npmjs.com/package/babel-plugin-module-alias 实现。

**Comment by alishamarie57** [comment]
Can I switch all this over to my 6s this phone is literally broken

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
It's a diff iCloud

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dkvirus** [comment]
@sorrycc  查了一下资料，babel-plugin-module-alias 这个包现在已经不用了，替代品是 [babel-plugin-module-resolver](https://npm.taobao.org/package/@cpsubrian/babel-plugin-module-resolver)，测试结果是可以的。

不过又产生了一个尴尬的问题，项目中使用 ESlint，导致使用别名后无法识别的错误。如代码： ``` import { config } from 'utils'; ```，这里的 utils 是使用别名后的名称。网上说了使用 [eslint-import-resolver-babel-module](https://npm.taobao.org/package/eslint-import-resolver-babel-module)在 .eslintrc 文件中进行如下配置：
```
"settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
```
这一步很是尴尬，试了好久都不行，不知有没有同仁也遇到过这种问题。

**Comment by sorrycc** [comment]
这是使用 alias 的副作用，副作用还包括不能在 IDE 里直接跳转到指定模块或者函数，这也是我为啥不推荐用 alias 并且没有把 webpack 的 alias 配置暴露出来的原因。

**Comment by dkvirus** [comment]
@sorrycc  了解了，多谢你的回答！

**Comment by alishamarie57** [comment]
Ok thank you I understand

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
为什么写这篇 Blog

起初，是由于项目的需要，开始正式接触 dva。

dva 的开发模式不同于传统页面的开发，学习起来有一定的技术门槛。

在 dva 的作者sorrycc Blog 里逗留了数个日夜，对新的开发模式好像是理解了，于是就迫不及待的下载了一个 demo，准备开发 CRUD。

故事情节的发展往往不会这么顺利，开发过程中发现，学会 dva 和在项目中使用 dva 进行完整开发完全是两码事：因为项目不仅仅是代码开发，还要关注项目的整体生命周期，代码规范，打包上线等等。

初学 dva 时心里变化

如果你和我一样，不能容忍在你的项目存在看不懂的东东，哪怕是一个配置文件，存在必有价值，不明白的东东就该 DELETE 掉，那么来到这里就对了，本文就是对 dva 做一次“大手术”，肢解它的技术组成，掌握项目中的 dva。

学习的过程中，难免会花费很多时间去查阅资料，有时候整篇英文文档看的让人直抓狂，本文总结作者在学习过程中看到的一些好的技术 Blog，贴上相关技术比较友好的 API 文档，帮助各位节约时间。

项目中的 dva

项目中的 dva

开发环境

npm@3.10.10
dva@0.7.8
antd@2.11.1
目录

初识 dva
dva 简介
创建一个 dva 脚手架工程
脚手架目录分析
语言基础
ES6
React
工具
包管理工具 Npm
版本控制工具 Git
开发工具 Webstorm
项目启动打包工具 Roadhog
代码格式化工具 ESLint
前后台接口规范工具 Swagger
es6 编译工具 Babel
模拟后台提供接口工具 json-server
核心技术
react-router
react-redux
axios
antd

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
1.1 dva 简介

dva 是什么

dva 是阿里前端架构师 sorrycc 带 team 研发的一套轻量级前端框架，其目的是尽量避免前端重复性劳动，简化开发流程。

实际上也确实如此，一个简单的 CRUD 模块只需要1-2个小时即可完成前端作业。

dva 脚手架是什么

前面说到 dva 是一个框架，那么 dva 脚手架就是这个框架的具体表现。

我们习惯于称：创建一个 dva 脚手架，实际上就是创建一个项目目录。

脚手架都包含什么

一个完整的 dva 脚手架应该包含以下内容：

自动创建一个包含 package.json 的项目。
自动创建成体系的目录结构。
自动安装项目需要的基础包。
集成代码检查工具 ESLint。
集成模拟接口工具 Mock。
集成服务启动打包工具 Roadhog。
集成版本控制工具 Git。
可以看到，脚手架帮我们做了很多的事，这就是脚手架带给我们的便利，否则从零开始搭建项目，无疑是一件费时费力又考验技术水平的事情。

当然，上面列举的几条你可能暂时无法明白具体指什么。

不用着急，下面几节会介绍如何创建一个 dva 脚手架，以及详细分析脚手架目录结构来依次解释脚手架包含的内容。

下一节：1.2 创建一个 dva 脚手架工程
Desktop version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alishamarie57** [comment]
1.1 dva 简介

dva 是什么

dva 是阿里前端架构师 sorrycc 带 team 研发的一套轻量级前端框架，其目的是尽量避免前端重复性劳动，简化开发流程。

实际上也确实如此，一个简单的 CRUD 模块只需要1-2个小时即可完成前端作业。

dva 脚手架是什么

前面说到 dva 是一个框架，那么 dva 脚手架就是这个框架的具体表现。

我们习惯于称：创建一个 dva 脚手架，实际上就是创建一个项目目录。

脚手架都包含什么

一个完整的 dva 脚手架应该包含以下内容：

自动创建一个包含 package.json 的项目。
自动创建成体系的目录结构。
自动安装项目需要的基础包。
集成代码检查工具 ESLint。
集成模拟接口工具 Mock。
集成服务启动打包工具 Roadhog。
集成版本控制工具 Git。
可以看到，脚手架帮我们做了很多的事，这就是脚手架带给我们的便利，否则从零开始搭建项目，无疑是一件费时费力又考验技术水平的事情。

当然，上面列举的几条你可能暂时无法明白具体指什么。

不用着急，下面几节会介绍如何创建一个 dva 脚手架，以及详细分析脚手架目录结构来依次解释脚手架包含的内容。

下一节：1.2 创建一个 dva 脚手架工程

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vonxq** [comment]
@dkvirus 你解决eslint报错的问题了吗？ 我现在eslint-import-resolver-babel-module安装好之后配置了也照样报错

**Comment by u3u** [comment]
@sorrycc vscode 配置 `jsconfig.json` 可以完美解决使用 webpack alias 导致智能提示无法使用的问题
希望可以增加别名选项，像 vue-cli 那样使用 `@` 代替 `src` 目录，否则 `../` 太多了不优雅
https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases

**Comment by imink** [comment]
@dkvirus 遇到了和你一样的问题，webpack 用 alias，结果 eslint 报错，暂时用 eslint-disable 来处理了。我在想写一个webpack loader，来处理路径问题。

**Comment by xuqinggang** [comment]
使用 [eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack)，告诉eslint，使用webpack的resolver来检查package是否引用正确

   ```
 module.exports = {
      // ...
      // eslint-import-resolver-webpack 让eslint，使用webpack的resolver来检查package是否引用正确
      settings: {
          "import/resolver": 'webpack',
      },
    };
```

**Comment by xylong** [comment]
> @sorrycc vscode 配置 `jsconfig.json` 可以完美解决使用 webpack alias 导致智能提示无法使用的问题
> 希望可以增加别名选项，像 vue-cli 那样使用 `@` 代替 `src` 目录，否则 `../` 太多了不优雅
> https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases
phpstorm呢，怎么解决alias导致智能提示失效的问题
