### ISSUE TITLE
能不能可以指定一些目录下的文件都走babel编译。

### ISSUE THREAD

**Issue by bjwulin** [sorrycc/roadhog#35]
我将一些项目的通用代码抽出来，用npm pack打包成本地包，由于代码都是jsx+es6的，现在都是pack前用babel编译，这样其它项目使用的时候看到的是es5的代码。如果不用 babel编译后打包，会提示"SyntaxError: Unexpected token"的错误。

能不能类似src，我们指定其它几个node-modules目录下的js也需要babel编译？

**Comment by sorrycc** [comment]
现在的通用约定就是 node_modules 下打包成 es5 的，然后 babel 不处理 node_modules 下的文件。

**Comment by bjwulin** [comment]
我知道，但是打包后的es5代码阅读差，所以我希望能加上指定目录能够用babel编译。

**Comment by sorrycc** [comment]
阅读差是要在项目开发时要调试依赖库的代码? 我通常会到具体的依赖库里写 demo 或用例进行调试。如果你坚持这么做，下个版本会加入 `webpack.config.js` 的扩展支持。 #36

**Comment by fritx** [comment]
@sorrycc 

> 现在的通用约定就是 node_modules 下打包成 es5 的，然后 babel 不处理 node_modules 下的文件。

我被这个坑啦，ie打开空白报错，我最近引了一个库 sindresorhus大神的[dot-prop](https://github.com/sindresorhus/dot-prop)，说实话这是一个普通的js库，但用了新语法。

如果我们webpack默认不处理node_modules的话，当引入任何js库的时候，都有可能面临这种风险，然后我们需要手动加入webpackrc.js，应该要默认处理才对嘛

```diff
// .webpackrc.js
   "extraBabelPlugins": [
     ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
   ],
+  "extraBabelIncludes": [
+    "node_modules/dot-prop"
+  ],
   "ignoreMomentLocale": true,
   "theme": "./src/theme.js",
```

**Comment by Vuchan** [comment]
@fritx 我遇到了同样的问题，使用了同样的解决方式，然后并没有什么用。 😊
