### ISSUE TITLE
the command "set BROWSER=none" has no effect

### ISSUE THREAD

**Issue by Downsview** [sorrycc/roadhog#353]
I've tried many times, but it turns out that the configuration "set BROWSER=none" has no effect, the browser opens every time, that's so disgusting to me, how to fix it?

**Comment by sorrycc** [comment]
Windows OS ?

**Comment by Downsview** [comment]
Right, Windows 7

**Comment by alishamarie57** [comment]
import Visualizer from 'webpack-visualizer-plugin';
import getEntry from '../utils/getEntry';
import getTheme from '../utils/getTheme';
import getCSSLoaders from '../utils/getCSSLoaders';
import addExtraBabelIncludes from '../utils/addExtraBabelIncludes';
import {
 getBabelOptions,
 baseSvgLoader,
 spriteSvgLoader,
 defaultDevtool,
 getResolve,
 getFirstRules,
 getCSSRules,
 getLastRules,
 getCommonPlugins,
 node,
} from './common';

export default function (args, appBuild, config, paths) {
 const { watch, debug, analyze } = args;
 const NODE_ENV = debug ? 'development' : process.env.NODE_ENV;

 const {
   publicPath = '/',
   library = null,
   libraryTarget = 'var',
   devtool = debug ? defaultDevtool : false,
 } = config;

 const babelOptions = getBabelOptions(config);
 const cssLoaders = getCSSLoaders(config);
 const theme = getTheme(process.cwd(), config);

 const output = {
   path: appBuild,
   filename: '[name].js',
   publicPath,
   libraryTarget,
   chunkFilename: '[name].async.js',
 };

 if (library) output.library = library;

 const finalWebpackConfig = {
   bail: true,
   devtool,
   entry: getEntry(config, paths.appDirectory, /* isBuild */true),
   output,
   ...getResolve(config, paths),
   module: {
     rules: [
       ...getFirstRules({ paths, babelOptions }),
       ...getCSSRules('production', { config, paths, cssLoaders, theme }),
       ...getLastRules({ paths, babelOptions }),
     ],
   },
   plugins: [
     ...(watch ? [] : [
       new webpack.optimize.OccurrenceOrderPlugin(),
       new webpack.optimize.DedupePlugin(),
     ]),
     new ExtractTextPlugin('[name].css'),
     ...getCommonPlugins({
       config,
       paths,
       appBuild,
       NODE_ENV,
     }),
     ...(debug ? [] : [new webpack.optimize.UglifyJsPlugin({
       compress: {
         screw_ie8: true, // React doesn't support IE8
         warnings: false,
       },
       mangle: {
         screw_ie8: true,
       },
       output: {
         comments: false,
         screw_ie8: true,
         ascii_only: true,
       },
     })]),
     ...(analyze ? [new Visualizer()] : []),
   ],
   externals: config.externals,
   node,
 };

 if (config.svgSpriteLoaderDirs) {
   baseSvgLoader.exclude = config.svgSpriteLoaderDirs;
   spriteSvgLoader.include = config.svgSpriteLoaderDirs;
   finalWebpackConfig.module.rules.push(baseSvgLoader);
   finalWebpackConfig.module.rules.push(spriteSvgLoader);
 } else {
   finalWebpackConfig.module.rules.push(baseSvgLoader);
 }

 return addExtraBabelIncludes(finalWebpackConfig, paths, config.extraBabelIncludes, babelOptions);

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by irrigator** [comment]
roadhog@0.5.2 on macOS also has this issue

**Comment by sorrycc** [comment]
roadhog@0.5.2 don't support `BROWSER=none`

**Comment by irrigator** [comment]
@sorrycc thanks for your quick response! Can I upgrade roadhog without upgrading dva?

**Comment by sorrycc** [comment]
@irrigator Sure.

**Comment by sorrycc** [comment]
```
{
  "scripts": {
    "start": "set BROWSER=none&&roadhog server",
    "test": "roadhog server"
  },
  "devDependencies": {
    "roadhog": "^1.0.2"
  }
}
```

I've test in my Window 10 and it works. `npm start` don't open browser, and `npm test` open browser.
