### ISSUE TITLE
How to import / resolve relative paths?

### ISSUE THREAD

**Issue by aislanmaia** [sorrycc/roadhog#355]
I'm trying to import components that living in the folder src/components from the routes folder files.
e.g. `import Count from 'components/Count';`

Using the default configurations that comes with roadhog, I'm getting the following: 
```
Error in ./src/routes/CountPage.js
Module not found: components/Count in /home/aislan/Projects/Javascript/Antd/myapp/src/routes
```

**Comment by paranoidjk** [comment]
Just use relative path, eg  `import Count from './path-to-components/Count';`

Roadhog do not support [resolve-alias](https://webpack.github.io/docs/configuration.html#resolve-alias)

**Comment by aislanmaia** [comment]
@paranoidjk many thanks for the information. :smiley:
