### ISSUE TITLE
webpack stats.toJSON(options) 支持CLI自定义

### ISSUE THREAD

**Issue by bshy522** [sorrycc/roadhog#359]
https://github.com/sorrycc/roadhog/blob/master/src/runServer.js#L82

是否可以考虑让stat的信息可以通过参数来配置下？ 有时候的确需要这些信息啊。

**Comment by sorrycc** [comment]
比如需要啥信息?

**Comment by bshy522** [comment]
就是stats可配置的那些信息。
都有哪些chunk和module，打包出来的文件名是什么

**Comment by bshy522** [comment]
@sorrycc
