### ISSUE TITLE
支持 webpack.config.js 的编程配置，但不推荐

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#36]
⚠️⚠️⚠️ 使用这种配置方式将不能保证 roadhog 之后的无缝升级，比如切换到 webpack2，rollup 或者其他，比如内部配置变更也可能导致失效。

所以会在支持的同时给予 WARN 警告。

**Comment by sorrycc** [comment]
https://github.com/js-cli/js-rechoir

**Comment by sorrycc** [comment]
- https://github.com/webpack/webpack/blob/f4ab7fc/bin/convert-argv.js

**Comment by sorrycc** [comment]
支持 es6，会用 babel-register 进行 transform。

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/21535213/d69101a2-cdac-11e6-9cfb-2563e8dc7f1e.png)

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/21535235/0e410570-cdad-11e6-8ae7-1a5c6295cec9.png)

**Comment by Kaijun** [comment]
请问使用 webpack 配置，是一个和 roadhog 默认配置 merge 的操作，还是完全根据 webpack.conf.js 配置的跑？

**Comment by Kaijun** [comment]
找了半天没找到example，看了下源码：

发现正确的使用姿势是：定义 `webpack.config.js` 返回一个 function 接受两个参数 webpackConfig, env
```
module.exports = function (webpackConfig, env) {
    // 对roadhog默认配置进行操作，比如：
    webpackConfig.plugins.push('...')
}
```

**Comment by weishijun14** [comment]
@Kaijun 请问下我想使用sass-loader 应该如何写？谢谢

**Comment by Kaijun** [comment]
@weishijun14 

不好意思回复晚了，希望还可以帮到你
参考上面的回复， 需要操作原有webpackConfig

使用sass-loader的话可能需要去掉原有的less-loader

参考默认配置：https://github.com/sorrycc/roadhog/blob/master/src/config/webpack.config.prod.js

需要删除 webpackConfig.module.loaders 里面关于css/less的loader,
然后 webpackConfig.module.loaders.push(sassLoader)

当然这样子违背了roadhog的初衷，请谨慎使用

**Comment by weishijun14** [comment]
@Kaijun 明白了！谢谢！！

**Comment by yeluolei** [comment]
强烈需求可以配置css loader。。 更改现有的css实现太麻烦了

**Comment by afc163** [comment]
```diff
module.exports = function (webpackConfig, env) {
    // 对roadhog默认配置进行操作，比如：
    if (env === 'development') {
        webpackConfig.plugins.push('...')
    }
+  return webpackConfig
}
```

**Comment by fsiaonma** [comment]
赞

**Comment by cater111** [comment]
我们现在用roadhog出现一个问题，工程打包太慢。是因为什么配置的原因吗？打开debug模式，原来几个小时，瞬间3分钟就打完了。但是感觉不能上生产。有什么方式可以加快速度吗。比如说第三方库与业务代码分离等。用roadhog怎么配置呀？求指导，万分感谢
