### ISSUE TITLE
设置publicPath并使用public文件夹时，引用文件路径不正确

### ISSUE THREAD

**Issue by wuzhuzhu** [sorrycc/roadhog#366]
#### Environment(required) | 环境（必填）

- roadhog version 0.6.0-beta3
- Nodejs and Npm version 8
- Operating environment (e.g. OS name) and its version（操作系统版本）: OSX

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
# .roadhogrc.js
"publicPath": "/subfolder/"
...

静态serve文件例
public/pic/zh/common.gif

代码：
<img src="/pic/zh/common.gif">

#### What do you expected?（预期的正常效果）
图片可以显示

#### What happen?（发生了何种非正常现象）
图片实际存在于/subfolder/pic/zh/common.gif 但是引用路径依然是/pic/zh/common.gif

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
你的场景应该不是 publicPath 所能覆盖的。

**Comment by yixiudadi** [comment]
那这种场景在生产环境应该怎么正确的引用public里面的文件
