### ISSUE TITLE
ie9 bug css oversize , can not display when size > 250kb *ie9 bug、css大小超过250kb时会自动截断，如何生成多个独立css文件？*

### ISSUE THREAD

**Issue by Restry** [sorrycc/roadhog#369]
when  i run roadhog build . it's was create a single css file name is index.css .

how can i separate it or make it lower than 250kb to fix this problem ?

--

**Comment by sorrycc** [comment]
参考 https://github.com/ant-tool/atool-build/issues/182

**Comment by Restry** [comment]
谢谢@sorryccc
用css-split-webpack-plugin 完美解决问题 。

但是我在.roadhogrc.js里面加了 externals: {
    'react':'React',
    'antd':'antd',
   'lodash':'_',
     'moment':'moment'
   }          但是我发现build生成后的大小和时间都差不多。index.js才少了20kb。

是不是还有其它地上来处理？
