### ISSUE TITLE
roadhog打包文件后，css无法加载。

### ISSUE THREAD

**Issue by hopperhuang** [sorrycc/roadhog#371]
使用了roadhog默认配置来进行打包

.roadhogrc文件如下：

`{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "proxy": {
    "/api": {
      "target": "https://cnodejs.org/api/v1",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  },
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd-mobile", "libraryDirectory": "lib", "style": "css" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd-mobile", "libraryDirectory": "lib", "style": "css" }]
      ]
    }
  }
}`

没有配置webpack.config.js文件。

期望：css 以style标签的方式动态加载。

实际：css并没有加载，元素除了浏览器提供的样式外，没有其他样式。

请问用roadhog打包应该怎么配置webpack文件或者roadhogrc文件？

**Comment by hopperhuang** [comment]
问题已解决,roadhog打包后antd的css文件不会自动插入到html模板中，需要手动添加<link rel="stylesheet" href="/index.css" />。

**Comment by babizhu** [comment]
我也是这样，虽然很好解决，但我想知道原因
