### ISSUE TITLE
 svg-sprite-loader

### ISSUE THREAD

**Issue by pigongting** [sorrycc/roadhog#372]
使用这种配置只在roadhog@0.6.0-beta1下有用？
svgSpriteLoaderDirs: [
    require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
    path.resolve(__dirname, 'src/assets/svg'), // 业务代码本地私有 svg 存放目录
],

roadhog@1.0.2时报错：Icon props.type is invalid, have you set svg-sprite-loader correctly?

**Comment by paranoidjk** [comment]
> 使用这种配置只在roadhog@0.6.0-beta1下有用？

不是，更高版本都可以。

> roadhog@1.0.2时报错：Icon props.type is invalid, have you set svg-sprite-loader correctly?

给出你 Icon 的调用代码

**Comment by pigongting** [comment]
非常感谢回复，后来看到了这个提示解决了问题：https://mobile.ant.design/changelog#1.2.0
antd-mobile Icon 所依赖的开源 webpack loader svg-sprite-loader 最近从 0.3 直接升级到了 2.0, 其配置方案发生了 break change，但由于此 loader 的版本由用户代码控制，而功能被 antd-mobile 和用户代码所共同依赖， antd-mobile 团队只能选择在 2.0 对其进行升级，请各位用户在 antd-mobile@1.x 期间暂时不要升级 svg-sprite-loader，在项目里仍然使用 svg-sprite-loader@0.3.x 即可。

**Comment by weishijun14** [comment]
+1

**Comment by paranoidjk** [comment]
@sorrycc 这个暂时不能升级 https://github.com/sorrycc/roadhog/issues/360

**Comment by paranoidjk** [comment]
@sorrycc https://github.com/ant-design/ant-design-mobile/releases/1.2.0

`antd-mobile@1` 强依赖 `svg-sprite-loader@0.3.1`

**Comment by paranoidjk** [comment]
@weishijun14 @pigongting 如果是 antd-mobile@1.x 的用户，可以选择先不要升级 roadhog@1.0

本来 major 更新就是可能包含 break change 的

**Comment by weishijun14** [comment]
主要要用到roadhog@1.0.2的hash

**Comment by sorrycc** [comment]
antd-mobile@1 的用户先别升 roadhog@1 吧。

**Comment by Elvin1993** [comment]
项目用的 antd-mobile 1 由于升级到2成本太大 然后今天折腾一下午 升级roadhog 结果发现升不了

 https://github.com/ant-design/ant-design-mobile/releases/1.2.0
antd-mobile@1.x 强依赖 svg-sprite-loader@0.3.x
[antd-mobile@1 的用户先别升 roadhog@1 吧。] 这句建议加到Read release notes 里面

**Comment by sorrycc** [comment]
@Elvin1993 感谢提醒，已更新。

**Comment by yourVictor** [comment]
在项目下安装svg-sprite-loader@0.3.1即可解决问题；

项目的pacage.json相关部分代码如下：

"antd-mobile": "^1.6.3",
"roadhog": "^1.3.4",
"svg-sprite-loader": "^0.3.1"
