### ISSUE TITLE
更新1.0.2版本后hot reload报错

### ISSUE THREAD

**Issue by ShadowRambler** [sorrycc/roadhog#373]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
1.0.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）
npm 4.6.1
node v6.10.3
- Operating environment (e.g. OS name) and its version（操作系统版本）:
osx 10.11.6 
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
从0.6升级到1.0.2 

#### What do you expected?（预期的正常效果）
之前的版本是正常的，更新了1.0.2后报错

#### What happen?（发生了何种非正常现象）

1.热替换的时候报错
![1](https://user-images.githubusercontent.com/5702449/29203888-56e793e8-7ea6-11e7-9b02-9e4007a0952f.jpg)
我的model是动态加载的和例子里相同
[https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/router.js](https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/router.js)

2.另外升级后antd版本没变的情况下 Card组件偶尔出现报错,暂时没升级antd，当前版本2.11.2
![2](https://user-images.githubusercontent.com/5702449/29204033-19bdc158-7ea7-11e7-8ff0-f4e9becfd8f2.jpg)
偶尔还有别的莫名其妙的报错，都是之前没有的
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
我找时间验证下。

**Comment by MinJieLiu** [comment]
@ShadowRambler 
[https://github.com/dvajs/dva-example-user-dashboard/pull/9](https://github.com/dvajs/dva-example-user-dashboard/pull/9)

换个写法，不是 `roadhog` 的问题
