### ISSUE TITLE
roadhog全局安装，server起来后页面报错

### ISSUE THREAD

**Issue by blanky01** [sorrycc/roadhog#377]
roadhog全局安装，demo其他配置都没有更改，server起来后页面报如下错误：

生成的roadhog.dll内容也不一样（左边是全局安装模式下，右边是本地安装）
![image](https://user-images.githubusercontent.com/11348798/29240893-c3cb43b0-7fa0-11e7-8cb5-24b41ee5d68f.png)

**Comment by sorrycc** [comment]
版本不同？另外，别全局安装，都用本地安装吧。
