### ISSUE TITLE
有没有结合mock的例子

### ISSUE THREAD

**Issue by TDiDa** [sorrycc/roadhog#38]

**Comment by sorrycc** [comment]
你希望怎么样的 mock 方式?

**Comment by TDiDa** [comment]
使用数据mock，需要怎么设置"proxy"

**Comment by sorrycc** [comment]
目前没有内置 mock 方案，之后可能会支持，可关注 #22 。现在可以利用 proxy 和 json-server 或其他 server 结合实现 mock，参考 https://github.com/sorrycc/blog/issues/18 第三步。

**Comment by sorrycc** [comment]
在 #22 里更新进度。
