### ISSUE TITLE
index.html didn't have hash after build

### ISSUE THREAD

**Issue by acwong00** [sorrycc/roadhog#382]
#### Environment(required) | 环境（必填）

- roadhog version: 1.0.2
- Nodejs version: v6.10.2
- Npm version: v3.10.10
- Operating environment and its version: windows 7

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
my `.roadhogrc`:

```json
{
  "entry": "src/pages/*.js",
  "theme": "src/theme.js",
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": true }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": true }]
      ]
    }
  },
  "hash": true,
  "multipage": true
}
```

after run `npm build`

my dist/index.html file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>hello</title>
  <link rel="stylesheet" href="index.css" />
</head>
<body>

<div id="root"></div>

<script src="index.js"></script>

</body>
</html>
```

the index.js don't have the hash. When I start the server can't find the target js file

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by ouzhou** [comment]
我现在的"roadhog": "^1.1.1"没毛病， 试试更新包呢？

**Comment by acwong00** [comment]
@ouzhou 你是多页的吗？

**Comment by sorrycc** [comment]
多页还不支持 html-webpack-plugin ，关注 #361 吧。
