### ISSUE TITLE
egg+dva，能否自定义roadhog的src目录

### ISSUE THREAD

**Issue by kchjxxgh** [sorrycc/roadhog#383]
虽然约定优于配置，但还是希望能放开src目录。我想把egg和dva放在同一个目录下开发，这时如果把dva的代码目录叫做“src”有些不合适，所以改为"client"之类的，但是roadhog只认“src”目录，所以我现在不得不用webpack-dev-server来启动client的server。
我是个新手，请教是否能放开src的配置，或者egg + dva放在同一目录下，有什么更好的方案？

**Comment by sorrycc** [comment]
可以提 PR 。
