### ISSUE TITLE
能否增加一个自定义chunkname的入口？

### ISSUE THREAD

**Issue by lengjing** [sorrycc/roadhog#384]
如果项目里页面很多的话就不得不用文件夹归类，这样的话就很容易出现文件名重复。

另外能不能再加一个 `plugins`入口，让用户自定义webpack插件。

**Comment by sorrycc** [comment]
- 你指 filename 还是 chunkFilename，chunkFilename 是 Code Splitting（按需加载）时才会用到吧
- plugins 就不暴露了，定制性太强，开放后就无法无痛升级了

**Comment by lengjing** [comment]
@sorrycc filename 吧

**Comment by sorrycc** [comment]
filename 能解决文件名冲突的问题？怎么解决？

**Comment by not3** [comment]
暴露下chunkFilename吧
```
{
	path: "/roles",
	getComponent(nextState, cb) {
		require.ensure([], (require) => {
			registerModel(app, require("./models/auth/role"))
			cb(null, require("./routes/role/index"))
		}, "roles")
	}
}
```
按需加载，避免文件名冲突。

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/blob/073eaac/src/config/webpack.config.prod.js#L37
默认就是 `[name].[hash].async.js`

**Comment by lengjing** [comment]
https://github.com/sorrycc/roadhog/blob/073eaac2add2e92d876dd5d7df32716db7a7d934/src/utils/getEntry.js#L9

把这个 `key` 暴露出来让用户自定义就可以了

**Comment by sorrycc** [comment]
entry 传 Object 就可以自定义 key 了，https://github.com/sorrycc/roadhog/blob/073eaac2add2e92d876dd5d7df32716db7a7d934/src/utils/getEntry.js#L48

**Comment by lengjing** [comment]
@sorrycc 3Q
