### ISSUE TITLE
can we remove the dependency on webpack-visualizer-plugin?

### ISSUE THREAD

**Issue by chaofan-nirvana** [sorrycc/roadhog#388]
webpack-visualizer-plugin is dependent on react 0.14.x and its latest version 0.1.11 was created on Feb 2017.

That will produce warning as following:
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

I think this package is just a tool, we can install it by hand.

**Comment by sorrycc** [comment]
> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see fb.me/prop-types-docs

When do you see this warning? After `roadhog build --analyze` and open the result html?

**Comment by chaofan-nirvana** [comment]
Sorry, never use the feature 'roadhog build --analyze'. The dependency has its reason.

I receive the warning from chrome console.

![image](https://user-images.githubusercontent.com/28529650/29351722-7e19a9c6-8296-11e7-9840-0c9513083fd8.png)

**Comment by sorrycc** [comment]
It has nothing to do with webpack-visualizer-plugin.

**Comment by chaofan-nirvana** [comment]
I will put an issue on webpack-visualizer-plugin to yell for a new version. Thanks!
