### ISSUE TITLE
升级roadhog 之后的问题

### ISSUE THREAD

**Issue by chanping** [sorrycc/roadhog#394]
#### Environment(required) | 环境（必填）
- roadhog version（roadhog版本）
v1.1.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）
v8.1.2
- Operating environment (e.g. OS name) and its version（操作系统版本）:
win10 64

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
npm run build 提示编译失败

#### What do you expected?（预期的正常效果）
能够正常编译

#### Re-producible online demo (可复现的在线demo)
无
<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 

- [ ] 项目示例源码偏于排查）

#
![image](https://user-images.githubusercontent.com/16409424/29422554-2a7a6b46-83ab-11e7-952e-d80f8c906b71.png)

#

**Comment by chanping** [comment]
#
![Uploading 企业微信截图_20170818002110.png…]()

**Comment by chanping** [comment]
![_20170818002110](https://user-images.githubusercontent.com/16409424/29422676-854830bc-83ab-11e7-8174-ce7a7c6e8384.png)

**Comment by sorrycc** [comment]
看不出问题在哪，传个可重现的 zip 包上来？
