### ISSUE TITLE
what's the intent of specifying `resolve.modules`

### ISSUE THREAD

**Issue by jdz321** [sorrycc/roadhog#395]
see https://github.com/sorrycc/roadhog/blob/master/src/config/common.js#L46

为何要指定 `resolve.modules` ，使用默认的 `node_modules` 有什么弊端吗？

在我的场景里有这样的结构

    ├── packages
        └── my-package
            ├── node_modules
                └── module-A
            └── index.js
    └── src
        └── index.js

引用关系：src/index.js  ->  packages/my-package  ->  module-A

此时roadhog build会报错： 找不到 `module-A`

使用默认webpack的`resolve.modules`值则没有问题。

期待解答。。  谢谢

**Comment by codering** [comment]
减少监控范围，提高性能而已

**Comment by jdz321** [comment]
感谢回复     roadhog刚升到1.x发现这个问题，对我的场景只能自己在webpack.config.js里增加resolve.modules解决了吗😅

**Comment by sorrycc** [comment]
不是从性能上考虑的，只是默认的规则不会去找 roadhog 的 node_modules，这样就无法加载 webpack 提供的 polyfill。我再加个 `node_modules` 的解析吧。

**Comment by sorrycc** [comment]
+roadhog@1.2.0-beta.1
