### ISSUE TITLE
roadhog好像不能 “roadhog app-test” 创建一个项目,而且create-react-app 的项目直接roadhog server报错

### ISSUE THREAD

**Issue by dingyanqiang** [sorrycc/roadhog#397]
roadhog好像不能 “roadhog app-test” 创建一个项目,
而且create-react-app 的项目直接roadhog server报错。
为啥不能roadhog创建项目.

#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
目前的方案是用 dva-cli 创建项目。

**Comment by mofengfs** [comment]
@sorrycc  作者在文档中的一句话估计会把很多人都误导了>"你可以想象他为可配置版的 create-react-app",  我认为这句话存在很大的误导性, 建议把它删了.
