### ISSUE TITLE
可配置额外需要做 babel 转换处理的文件规则

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#40]
https://github.com/ant-design/ant-design/issues/4418, #35

**Comment by szwork2013** [comment]
如果没有 webpack.config.js配置文件，动态加载route还不能对 chunkFilename配置吗？比如 '[name].[hash].js'

**Comment by sorrycc** [comment]
动态加载的文件为何要进行命名？

**Comment by szwork2013** [comment]
我是说按需加载方式生成在dist的文件，加上 [hash]后可以自动部署在生产环境，不用手工加其他防止缓存的参数

**Comment by gzbigegg** [comment]
这个现在有了吗？我在 .roadhog.mock.js 中引入了 mockjs，估计要这个才能修复。

**Comment by sorrycc** [comment]
> 这个现在有了吗？我在 .roadhog.mock.js 中引入了 mockjs，估计要这个才能修复。

这个和 babel 转换无关吧。

**Comment by gzbigegg** [comment]
好象之前看你写到过 babel 默认只对 ./src 目录下的文件做处理。我在 .roadhog.mock.js 文件中包含了其他的带有 mockjs 数据的文件，因为 .roadhog.mock.js 不在 ./src 目录下，所以这一系列的文件都必须用老的 JS 的语法。目前来看问题不是很大，能绕过去，比较困扰的是有一个浏览器的 localStorage 不能直接用了。

**Comment by sorrycc** [comment]
`./.roadhogrc.mock.js` 和 `./mock/` 文件夹都是走 babel 解析的。

**Comment by gzbigegg** [comment]
等你下一个版本发布了我再试试吧。

**Comment by sorrycc** [comment]
roadhog 实现：

1. 通过 .roadhogrc 的 `extraBabelIncludes` 规则，指定除 src 目录外需要 babel 处理的文件夹
2. 一条文件夹加一个 babel loader 处理规则

```js
{
  test: /\.(js|jsx)$/,
  include: %文件夹%,
  loader: 'babel',
},
```

**Comment by zhengqingxin** [comment]
@sorrycc `一条文件夹加一个 babel loader 处理规则`这里还是没太懂，要在哪里加呢？

**Comment by sorrycc** [comment]
这是内部实现，不用管。参考这个用例进行配置吧，https://github.com/sorrycc/roadhog/blob/master/test/fixtures/build/extraBabelIncludes/.roadhogrc

**Comment by zhengqingxin** [comment]
我用dva新建了一个项目，修改目录结构为：

![](https://p5.ssl.qhimg.com/t019ec8ddcdd4c8d11a.png)

然后将`.roadhogrc`改为一下内容：
```
{
  "entry": "src/index.js",
   "extraBabelIncludes": [
      "www/static/src"
    ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  }
}

```
发现将 index.js 和 index.css 编译成了 html 的内容？如图：

![](https://p0.ssl.qhimg.com/t01ff10230ece1eaf0b.png)

**Comment by sorrycc** [comment]
entry 没配对。

**Comment by zhengqingxin** [comment]
entry 要配成 `www/static/src` 吗？  这样配会报 `Unexpected token` 那个错误了

**Comment by sorrycc** [comment]
roadhog 升级下，0.5.4 估计还没这个配置项。

**Comment by baobao12356** [comment]
"extraBabelIncludes": [
		"node_modules/qs",
		"node_modules/query-string",
		"node_modules/events",
		"node_modules/dashjs",
		"node_modules/pearplayer",
		"node_modules/webtorrent",
		"node_modules/dplayer",
		"node_modules/shaka-player",
		"node_modules/hls.js",
		"node_modules/flv.js",
		"node_modules/typescript",
		"node_modules/event-emitter",
		"node_modules/dva-immer",
		"node_modules/immer"
	]这样么?

**Comment by baobao12356** [comment]
> 这是内部实现，不用管。参考这个用例进行配置吧，https://github.com/sorrycc/roadhog/blob/master/test/fixtures/build/extraBabelIncludes/.roadhogrc

这打开是404
![Uploading image.png…]()
