### ISSUE TITLE
roadhog的publicPath默认值建议改成undefined

### ISSUE THREAD

**Issue by www3com** [sorrycc/roadhog#403]
用html-webpack-plugin插件，html里生成css和js的相对路径，需要publicPath设置成undefined，而roadhog的publicPath默认是"/",不能传参数undefined，所以，这样无法生成引入资源的相对路径，建议roadhog的publicPath默认为undefined。

**Comment by sorrycc** [comment]
为啥要设为 undefined ?

**Comment by p2227** [comment]
一直都是用`''`

**Comment by sorrycc** [comment]
有问题再 reopen 。
