### ISSUE TITLE
不支持less、stylus？

### ISSUE THREAD

**Issue by zkeyword** [sorrycc/roadhog#406]
没看到支持less、stylus的配置，不支持？

**Comment by zkeyword** [comment]
使用webpack.config.js:

import ExtractTextPlugin from 'extract-text-webpack-plugin'
module.exports = (webpackConfig) => {
    webpackConfig.module.loaders.push({
        test: /.styl$/,
        loader: ExtractTextPlugin.extract('style', 'css!stylus')
    })
    return webpackConfig
}

报以下错误：

I:\test\dvaTest\node_modules\webpack-core\lib\LoadersList.js:58
        if (element.loader) return element.loader.split("!");
                                                  ^

TypeError: element.loader.split is not a function
    at getLoadersFromObject (I:\test\dvaTest\node_modules\webpack-core\lib\LoadersList.js:58:44)
    at LoadersList.<anonymous> (I:\test\dvaTest\node_modules\webpack-core\lib\LoadersList.js:78:12)
    at Array.map (<anonymous>)
    at LoadersList.match (I:\test\dvaTest\node_modules\webpack-core\lib\LoadersList.js:70:19)
    at I:\test\dvaTest\node_modules\webpack\lib\NormalModuleFactory.js:111:68
    at I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:726:13
    at I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:723:17
    at I:\test\dvaTest\node_modules\webpack\node_modules\async\lib\async.js:167:37
    at I:\test\dvaTest\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:29:4
    at onResolved (I:\test\dvaTest\node_modules\enhanced-resolve\lib\Resolver.js:39:10)
    at I:\test\dvaTest\node_modules\enhanced-resolve\lib\Resolver.js:123:21
    at I:\test\dvaTest\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (I:\test\dvaTest\node_modules\enhanced-resolve\lib\Resolver.js:104:30)

**Comment by sorrycc** [comment]
默认支持 less，不支持 stylus。

**Comment by sorrycc** [comment]
stylus 这样简单配是不行的。

**Comment by WangYang-Rex** [comment]
@sorrycc 
配置stylus，不报错，但是也没成功，请问需要怎么配置呢
```js

module.exports = (webpackConfig) => {
  const config = webpackConfig;
  // // Alias
  config.resolve.alias = {
    components: `${__dirname}/src/components`,
    utils: `${__dirname}/src/utils`,
    config: `${__dirname}/src/utils/config`,
    services: `${__dirname}/src/services`,
    models: `${__dirname}/src/models`,
    routes: `${__dirname}/src/routes`,
  };
  config.resolve.extensions.push('.styl');
  webpackConfig.module.loaders.push({
    test: /\.styl$/,
    include: `${__dirname}/src`,
    loader: 'style!css!stylus',
  });
  // console.log(JSON.stringify(webpackConfig), env);
  return config;
};
```

**Comment by zkeyword** [comment]
stylus用户量那么少么? 都不支持

**Comment by zkeyword** [comment]
@WangYang-Rex 我没用dva-cli，但还是dva的架子，你瞅瞅，https://github.com/zkeyword/dynamax-react-scaffold-dva
