### ISSUE TITLE
在开发环境设置 <img src="img/logo.png"> 找不到

### ISSUE THREAD

**Issue by sunzd116** [sorrycc/roadhog#41]
在开发环境下，引用图片
`<div className='header__container--left'>
          <img
            src="img/logo.png"
            />
          <div className='header__text'>
            {title}
          </div>`

打开浏览器，图片无法显示，而且开发者工具里面显示的是
![image](https://cloud.githubusercontent.com/assets/9314683/21563062/ce92fdcc-ceb8-11e6-822d-5150e41ffeb1.png)

**type 不是 png 而是 text\html** 请问大大怎么解决这个问题。
**使用 roadhog 时静态资源需要放在什么特殊的地方吗？** 附上我的配置文件和项目结构如下
![image](https://cloud.githubusercontent.com/assets/9314683/21563101/3e0691d2-ceb9-11e6-8e07-599fae801313.png)

![image](https://cloud.githubusercontent.com/assets/9314683/21562974/26bf7ef4-ceb8-11e6-9ce2-059165a82e78.png)

**Comment by sunzd116** [comment]
查阅 create-react-app 的文档找到解决方案了 原来是要放在 public/文件夹下

**Comment by heyi** [comment]
我也重现了， 文档里并没有说明一定要放在public目录下，所以无觉得还是要补充说明一下

**Comment by paranoidjk** [comment]
@heyi PR
