### ISSUE TITLE
npm build 时怎么给js加上版本号

### ISSUE THREAD

**Issue by kingsily** [sorrycc/roadhog#411]
npm build 时怎么给index.js index.css 加上版本号
比如 index.js => index.1.js
 require.ensure([], (require) => {
       
          cb(null, require('./routes/test'));

        },'test')
我想实现的是每次生成出来的文件名都不一样，不要一直是1.test.js，我想要的结果是1.test.version.js
version是版本号或者随机值什么的都可以

**Comment by sorrycc** [comment]
配 `"hash": true`。

**Comment by kingsily** [comment]
配置了，结果还是一样

**Comment by sorrycc** [comment]
roadhog 需升级到最新。

**Comment by kingsily** [comment]
刚刚升级到1.1.2，但是打包出来的还是和之前一样
![image](https://user-images.githubusercontent.com/12093660/29902910-86575662-8e33-11e7-8705-aed958510185.png)

**Comment by codering** [comment]
你把  ` "hash": true` 配哪里了？

**Comment by kingsily** [comment]
已解决，谢谢

**Comment by codering** [comment]
如果感觉js过大，可以参考下 #405

**Comment by albafica2015** [comment]
@kingsily 请问我配了，怎么还是一样的？    "roadhog": "^1.2.2" 版本
