### ISSUE TITLE
roadhog server可否支持写入磁盘选项

### ISSUE THREAD

**Issue by bulldog478** [sorrycc/roadhog#412]
目前roadhog server构建文件缓存于内存，可否支持写入磁盘呢，因为roadhog build -w经过了很多优化实在是有些慢。例如我使用springmvc，服务端需要读取静态资源文件。希望可以采纳，或者有什么配置方法。多谢。

**Comment by sorrycc** [comment]
不行的，webpack-dev-server 没有写入磁盘的选项。
