### ISSUE TITLE
升级dva和roadhog后 启动页面空白

### ISSUE THREAD

**Issue by albafica2015** [sorrycc/roadhog#428]
http://localhost:8000/#/ 现在启动的

http://localhost:8000   原来启动的

现在启动出来就是空白页面

<div id="root"></div>

请问怎么修改？

**Comment by sorrycc** [comment]
没有重现步骤帮不了你，参考 https://github.com/dvajs/dva/tree/master/packages/dva-example-user-dashboard 。

**Comment by sorrycc** [comment]
空白且没有报错通常是路由不匹配。
