### ISSUE TITLE
升级后的roadhog与amd模式不兼容

### ISSUE THREAD

**Issue by Aiooioo** [sorrycc/roadhog#431]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） 1.2.1
- Nodejs and Npm version（Nodejs 和 Npm 版本）8.1.2/3.12
- Operating environment (e.g. OS name) and its version（操作系统版本）: Win10 x64

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
在新的项目中，通过dva-cli初始化的项目用了新版本的roadhog， 注意到你在新版本中对index.html引入了ejs模板，遗憾的是你反复的添加了对bundle文件index.js的直接引用，这直接导致在amd模式下无法使用了。

#### What do you expected?（预期的正常效果）
本来预期的效果是，页面中通过script标签引入dojoloader作为amd管理器，bundle文件以amd的方式引用：
    <script>
    require(['./index.js'], function() {
    console.log('Index loaded!');
    });
    </script>
但紧跟着之后roadhog又插入了一段script来引用index.js
    <script type="text/javascript" src="/index.js">

在这种场景下面，完全没法使用roadhog了

#### What happen?（发生了何种非正常现象）
AMD multi-define错误

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by HelloHxz** [comment]
我也同样有个问题就是 为什么 现在打包的文件 是 <script type="text/javascript" src="/index.js"> 斜杠 而不是./index.js 或者 index.js

**Comment by 104gogo** [comment]
@HelloHxz  配置下publicPath，默认是‘/'

**Comment by HelloHxz** [comment]
@104gogo 谢谢~

**Comment by sorrycc** [comment]
需要手动引入 index.js 的场景不要用 index.ejs。
