### ISSUE TITLE
npm run build 打包Hash:true后静态资源文件路径的问题

### ISSUE THREAD

**Issue by HelloHxz** [sorrycc/roadhog#432]
为什么 现在打包的文件 是 <script type="text/javascript" src="/index.js"> 斜杠 而不是./index.js 或者 index.js

**Comment by zyc017** [comment]
这是根路径，当服务启动的时候所有资源都是相对于你当前html来加载的，如果写相对路径，不能保证你所有资源都能加载到

**Comment by HelloHxz** [comment]
配置 publicPath为‘./’
