### ISSUE TITLE
antd-mobile+dva+roadhog中svg图标不显示

### ISSUE THREAD

**Issue by ningpy123** [sorrycc/roadhog#433]
我的antd-mobile版本1.6.7，roadhog版本0.6.0，svg-sprite-loader版本0.3.1

svg目录配置：
const svgSpriteDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''),
  // antd-mobile 内置svg
  // 业务代码本地私有 svg 存放目录
  path.resolve(__dirname, 'src/assets/svg'),
];

.roadhogrc文件已经确认删除

可是在Button组件中使用svg图标不显示

<Button className={styles.searchBtn} activeStyle={false} inline icon={require('../assets/svg/search.svg')}>
                搜索</Button>

用antd-mobile自带的search图标也一样不显示，用img标签直接require svg图标同样效果

开始时由于版本问题，浏览器有报错，调整过版本以后目前没有报错，不过图标不显示，请帮忙看一下问题。

**Comment by nicejacket** [comment]
svg-sprite-loader版本升级后返回的数据不是string的类型
我是切换roadhog的svg-sprite-loader版本为以前的版本可以了
在webpack.config.js里加
`  config.module.rules.forEach((item) => {
    if (item.loader === 'svg-sprite') {
      item.loader = require.resolve('svg-sprite-loader');
    }
  });`
再在package.json里添加svg-sprite-loader的老版本依赖就可以了
