### ISSUE TITLE
babel-plugin-react-css-modules插件

### ISSUE THREAD

**Issue by rendongsc** [sorrycc/roadhog#445]
有没有在roadhog中正确使用babel-plugin-react-css-modules
[https://github.com/gajus/babel-plugin-react-css-modules](url)
的配置例子？
我的配置不起作用。
```
const path = require('path')
const context = path.resolve(__dirname, 'src');
export default {
  entry: 'src/index.js',
  publicPath: `/`,   
  extraBabelPlugins: [   
    "transform-runtime",
    [
      'react-css-modules',
      {
        context
      }
    ]
  ]
}
```

**Comment by rendongsc** [comment]
弃用babel-plugin-react-css-modules了，关掉这个问题。

**Comment by shirleyYing** [comment]
@rendongsc 请问为什么弃用了，我现在项目重构也是想用这个插件

**Comment by rendongsc** [comment]
@shirleyYing 这个时间有点长了，忘了具体原因。
好像是：我们的业务组件分了很多包，引用公共包时好像className会报不存在的问题。
