### ISSUE TITLE
hash 无效

### ISSUE THREAD

**Issue by Cuihongsen** [sorrycc/roadhog#458]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） 1.2.2
- Nodejs and Npm version（Nodejs 和 Npm 版本） 8.7.0  5.4
- Operating environment (e.g. OS name) and its version（操作系统版本）: Mac 10.12.6

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

设置了 "hash": true
但是生成的文件没有hash 
如何更改生成文件的目录我需要在/static而不是/

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by Cuihongsen** [comment]
还生成了1.1.js和2.3.js 不是很懂为啥这样

**Comment by narutowyh** [comment]
我也想知道怎么配置生成的文件的名字为文件的hash，想解决每次发布版本都无法清http缓存的问题

**Comment by jiangtl** [comment]
我也遇到了缓存问题，同问。

**Comment by Cuihongsen** [comment]
忘记了当时是怎么解决的了，貌似是给dva还是roadhog升级了，就好使了
