### ISSUE TITLE
.roadhogrc.mock.js 使用Forward 的时候在Win下出现 地址被转义出错的问题

### ISSUE THREAD

**Issue by ghostlitao** [sorrycc/roadhog#465]
在.roadhogrc.mock.js配置中:
const API='http://test.local/'

export default {
	'/api/*': API,
};
在mac 开发下一切正常,但是在Win下出现了Forword之后返回400 的错误.
查了服务器的Access_log 之后发现访问的地址被代理成了:

"GET \x5Capi\x5Cactivity\x5Crecommend HTTP/1.1" 400 166 "-" "-"
当时的路径应该是:
\api\activity\recommend

#### Environment(required) | 环境（必填）

- roadhog version（1.2.1）
- Nodejs and Npm version（5.5.1）
- Operating environment (e.g. OS name) and its version（操作系统版本）:Win7

**Comment by ghostlitao** [comment]
采用了同样的配置文件,API地址是公网的Centos服务器.

**Comment by ghostlitao** [comment]
用了Proxy 可以解决这个问题.但是 .roadhogrc.mock.js 还是有问题.

**Comment by isghost** [comment]
兄弟， 解决办法能详细描述一下吗？

**Comment by ghostlitao** [comment]
@isghost  Hi 你也遇到同样问题了? 就是不要用 
'/api/*': API,
这种形式转发,而是用 Proxy 的功能 再配置一遍.

**Comment by ghostlitao** [comment]
@isghost  就是用:
https://github.com/sorrycc/roadhog#proxy
这个,而不是用 mock

**Comment by isghost** [comment]
我也遇到相同问题，用你的方法解决了，谢谢

**Comment by cfZeng** [comment]
还是没有解决.roadhogrc.mock.js里配置代理的模式，https://github.com/sorrycc/roadhog#proxy配置是全局的吧？只想针对某个连接去做也不行吧，感觉还是得解决win下Forword反斜线的问题才行。

**Comment by ghostlitao** [comment]
@cfZeng 不知道怎么原因,但是proxy 肯定能解决,你看下具体的文档,其实道理都一样.

**Comment by ghostlitao** [comment]
@cfZeng 针对多个链接,就多写几个proxy的配置:
"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  },
"/api2": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api2" : "" }
  }
}
