### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by JoneXiong** [sorrycc/roadhog#477]
1. 拉最新发布的 Antd pro 项目 build 出来跑报错: “webpackJsonp is not defined”
2. 直接 npm start 正常，但是用 roadhog server 跑报错: "Uncaught TypeError: Super expression must either be null or a function, not undefined"
以上问题用了 #455 这个pr后可以解决，So 尽快合并？

**Comment by sorrycc** [comment]
已发布。
