### ISSUE TITLE
postcss-pxtorem 不能处理antd-mobile css

### ISSUE THREAD

**Issue by semicoder** [sorrycc/roadhog#48]
未采用roadhog时使用:
```js
webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }));
```
能够正确处理antd-mobile和自己css文件中的单位
现在使用roadhog无法处理antd-mobile，但能够处理自己的css文件:
```js
let postcss = webpackConfig.postcss();

  postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }));

  webpackConfig.postcss = function () {
    return postcss;
  };
```

**Comment by sorrycc** [comment]
我找时间重现下。

**Comment by sorrycc** [comment]
有空等这周的 0.5 发布后再测下，我在用例里加了没有问题。

**Comment by lnlfps** [comment]
我也遇到了这个问题，有临时的解决方法吗?

**Comment by lnlfps** [comment]
找到问题了，在config目录下的webpack.config.dev.js这行代码有问题
`    {
        test: /\.less$/,
        include: paths.appNodeModules,
        loader: `style!${cssLoaders.nodeModules}!less?{"modifyVars":${theme}}`,
      },`
修复后是：
`    {
        test: /\.less$/,
        include: paths.appNodeModules,
        loader: `style!${cssLoaders.nodeModules.join('!')}!less?{"modifyVars":${theme}}`,
      },`

缺少join('!')字符串连接符，导致loader的定义格式错误。
webpack.config.prod.js 这个里面好像也有类似的问题，请核查下。

**Comment by sorrycc** [comment]
升级 roadhog 到 0.5，然后按这个配置试试，https://github.com/sorrycc/roadhog/blob/master/test/fixtures/build/pxtorem/.roadhogrc.js 。

**Comment by sorrycc** [comment]
确实是代码层不对，感谢定位问题，我稍后发个 bugfix 版本。

**Comment by sorrycc** [comment]
@lnlfps 已在 0.5 中修复。

**Comment by lnlfps** [comment]
@sorrycc 0.5的npm包里好像还是有点问题，src目录里的webpack.config.dev.js是对的，但lib目录下的webpack.config.dev.js还是和之前的代码一样，没有加join('!')。

**Comment by sorrycc** [comment]
@lnlfps 是 Makefile 脚本的问题，publish 前没有 build 。我看过 0.5.1 的发布包是好的，你试试看。

**Comment by lnlfps** [comment]
@sorrycc  刚试了，0.5.1已经好了，谢谢！

**Comment by jozhi** [comment]
@sorrycc  目前使用的 0.5.2 依然有这个问题，按照以上说明添加了.roadhogrc.js 再次测试依然没有解决。
