### ISSUE TITLE
How to get the source-map in build？

### ISSUE THREAD

**Issue by remotesc2** [sorrycc/roadhog#484]
使用 .roadhogrc 配置吗？
在介绍中，没有找到相关说明

**Comment by sorrycc** [comment]
暂不支持。

**Comment by remotesc2** [comment]
那上线后的代码，如果需要调试，暂时只能走别的方式了？

**Comment by bochen2014** [comment]
。。。

以前版本还支持重载webpackonfig， 可以重定义一下（比如devtools就可能支持source-map了）。最新版好像没这个选项了。。

其实你可以做一个`eject command`, 一但`eject` 就由用户自己配置webconfig
angular, create-react-native都是这么做的

**Comment by bochen2014** [comment]
BTW， `roadhog@^1.3.1`肯定支持source-map

**Comment by remotesc2** [comment]
@bochen2014 
你说的支持是指？

**Comment by sorrycc** [comment]
It's supported in roadhog@2, config `devtool` in `.webpackrc`.

**Comment by prionkor** [comment]
Is there any documentation available to enable sourcemap for js bundle?
