### ISSUE TITLE
dva new 出来的项目，css 引入重复问题

### ISSUE THREAD

**Issue by hangyangws** [sorrycc/roadhog#487]
# dva new 出来的项目，css 引入重复问题

> roadhog version: ^1.2.1

### 重现步骤

1. dva new myApp
1. cd myApp
1. 查看 myApp/src/index.ejs 的代码
1. 查看 myApp/src/index.js 的代码
1. 发现 `myApp/src/index.js`、`myApp/src/index.ejs` 都引入了 `index.css`

### 期望

`myApp/src/index.js`、`myApp/src/index.ejs` 之中又有一个引入了 `index.css`

**Comment by sorrycc** [comment]
Fixed via new version of dva-cli.
