### ISSUE TITLE
在dva项目中，此命令如何实现模块按需加载

### ISSUE THREAD

**Issue by liysw** [sorrycc/roadhog#49]
代码按主框架和业务模块分开打包，使用时按需加载，是否可行？

**Comment by halsn** [comment]
占个坑，正在研究中

**Comment by sorrycc** [comment]
这是 webpack 的功能，用 require.ensure 就可以了，roadhog 是基于 webpack，所以肯定也是支持按需加载的。例子可参看这个 [commit](https://github.com/dvajs/dva-example-user-dashboard/commit/df2a7a0e1e7295840cfd2032a677f5e69c968c8a)。
