### ISSUE TITLE
roadhog proxy

### ISSUE THREAD

**Issue by wyl199** [sorrycc/roadhog#490]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
```
"roadhog": "^1.2.1"
```
- Nodejs and Npm version（Nodejs 和 Npm 版本）
```
cnpm@5.1.1 
```
- Operating environment (e.g. OS name) and its version（操作系统版本）:
```
win7
```

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

- .roadhogrc文件配置proxy如下：
```
"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}
```
- 然后访问 /api/users

#### What do you expected?（预期的正常效果）

- Request URL: http://jsonplaceholder.typicode.com/users

#### What happen?（发生了何种非正常现象）

- Request URL:http://localhost:8101/api/users

- 请求链接不正确，但却请求到了正确的数据

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by czl1378** [comment]
请问是怎么解决的？
