### ISSUE TITLE
mock 不支持中文 url 吗?

### ISSUE THREAD

**Issue by oldfeel** [sorrycc/roadhog#503]
#### Environment(required) | 环境（必填）

- roadhog version（^1.3.1）
- Nodejs and Npm version（npm:5.5.1, node:8.6.0）
- Operating environment (e.g. OS name) and its version（deepin 15.5）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

````
  'GET /接口/用户/登录': {
    $desc: "用户登录",
    $params: {
      名称: 'admin',
      密码: 'admin'
    },
    $body: {
      "Id": 1,
      "F名称": "admin",
      "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
    },
  },
````

#### What do you expected?（预期的正常效果）

访问 http://localhost:8000/接口/用户/登录?名称=admin&密码=admin 返回
````
{
      "Id": 1,
      "F名称": "admin",
      "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
}
````

#### What happen?（发生了何种非正常现象）

返回了 http://localhost:8000/ 的内容

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by hushiyi** [comment]
@oldfeel 访问 http://localhost:8000/jiekou/yonghu/login?mingchen=admin&mima=admin，难道是英文你能支持吗？我写的英文demo也不能支持的呀，例：
export default {
	'POST /jkkit-gp/service?method=cashier.paymentList':  {
    $params: {
      method: 'cashier.paymentList',
    },
    $body: {
      "Id": 1,
      "f": "admin",
      "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
    },
  }
};

请求报404

**Comment by oldfeel** [comment]
@hushiyi 
````
'POST /jkkit-gp/service?method=cashier.paymentList': {
````
这里的 url 不能加问号吧.问号后面的是参数,放到 $params 中就行了.

**Comment by hushiyi** [comment]
果然这可以  @oldfeel  谢谢啊。
但是返回是这样：
{
    "$params": {
        "method": "cashier.paymentList"
    },
    "$body": {
        "Id": 1,
        "f": "admin",
        "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
    }
}
不能直接获取到 {
        "Id": 1,
        "f": "admin",
        "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
    }这种格式呢？然后再请教下这是什么语法，为什么参数要放到返回里面才生效。

**Comment by oldfeel** [comment]
@hushiyi 哦,我用的是 https://github.com/nikogu/roadhog-api-doc ,不一样.参考文档 https://pro.ant.design/docs/api-doc-cn

**Comment by hushiyi** [comment]
恩 安装了npm install roadhog-api-doc --save-dev可以了。
我刚刚测试了中文，也是可以正常获取到数据哦。
export default format({
	'POST /jkkit-gp/service':  {
    $params: {
      '测试': 'cashier.paymentList',
    },
    $body: {
      "Id": 1,
      "f": "admin",
      "Token": "qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"
    },
  }
});
**返回：**
{"Id":1,"f":"admin","Token":"qGTlxBAmknIqsUmpCyywZDnlnAalPNyz"}

**Comment by oldfeel** [comment]
@hushiyi 中文 URL 不可以
````
'POST /jkkit-gp/中文': {}
````
