### ISSUE TITLE
React16的新特性componentDidCatch无法捕获到真实的错误信息

### ISSUE THREAD

**Issue by longzhaobi** [sorrycc/roadhog#506]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）：1.3.1
- Nodejs and Npm version（Nodejs 和 Npm 版本）6.10.2  5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）:win10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

子组件抛出错误：Error msg，componentDidCatch捕获到的错误信息为：Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

#### What do you expected?（预期的正常效果）

希望捕获到的错误信息为：Error msg

#### What happen?（发生了何种非正常现象）

目前不清楚是DVA的问题还是roadhog的问题，也不清楚是不是我写的是不是有问题，我在create-react-app脚手架创建的项目测试是可以正常捕获到错误信息的。
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
重复，在 dva 的 issue 里已回。
