### ISSUE TITLE
自己跟自己冲突，启动时指定端口

### ISSUE THREAD

**Issue by LitileXueZha** [sorrycc/roadhog#509]
npm start的时候显示已经有app在8000端口上运行，set PORT为其它端口如8065、8001也是相同错误，但是接下来输入y随机端口却可以启动

**Comment by magicyangmei** [comment]
我也是，进程没杀死，手动kill掉

**Comment by ldwonday** [comment]
遇到了同样的问题，这个端口根本没有被占用，找不到对应的进程，我的是mac

**Comment by ldwonday** [comment]
@LitileXueZha 这个问题你解决了吗？

**Comment by LitileXueZha** [comment]
源码里没有拿到启动端口，而是随机的。在判断语句中写死就能规避

**Comment by ldwonday** [comment]
@LitileXueZha 具体在哪里？

**Comment by cpu220** [comment]
同样遇到，完全没搞明白什么原因。每次启动都随机端口很烦。无奈之下手动去改了源码写死端口
@sorrycc

**Comment by jzoe** [comment]
同样的问题

**Comment by albertzzy** [comment]
话说这个问题有解决吗？

**Comment by SilentFlute** [comment]
> 源码里没有拿到启动端口，而是随机的。在判断语句中写死就能规避

话说我到af-webpack>lib>dev.js中修改它的DEFAULT_PORT为80了，但是启动的时候还是提示端口被占用，改为其他的端口号比如8002 8003就是ok的，你是怎么改的呢？我的roadhog的版本是2.5.0-beta.4
@LitileXueZha
