### ISSUE TITLE
新需求:增加对dist压缩打包支持

### ISSUE THREAD

**Issue by kingyang** [sorrycc/roadhog#51]
方便分发.
 支持自定义打包命名规则和位置

**Comment by sorrycc** [comment]
现在默认就会压缩的，如何自定义命名规则和位置？需求是啥？

**Comment by kingyang** [comment]
早啊,谢谢回复
我的需求build之后,需要对build再压缩成一个zip文件.便于分发到测试/或现场
现在我们是用gulp再次处理一下,zip文件命名为项目名+当前日期

**Comment by sorrycc** [comment]
这个就用 gulp 吧，职责清晰，roadhog 只管 webpack 这一层的打包。

**Comment by kingyang** [comment]
嗯,好的
