### ISSUE TITLE
如何提取antd的css成公用css

### ISSUE THREAD

**Issue by kingsily** [sorrycc/roadhog#513]
#### Environment(required) | 环境（必填）

- roadhog 1.1.2（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）node 6.10.0 npm 3.10.10
- Operating environment (e.g. OS name) and its version（操作系统版本）:
windows 7
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
打包的时候想把antd的样式都打包到指定的css文件中不再插入到js文件里，要 怎么实现呢

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
dev 模式下加 css 打包在 JS 里，production 模式下是抽出来的。

**Comment by tcstory** [comment]
@sorrycc js里的css,是抽离到各自的css文件里,还是统一抽离到index.css里?
我观察到的是,就算是动态加载的模块里的css,也会被放到index.css里面
