### ISSUE TITLE
roadhog server运行两次

### ISSUE THREAD

**Issue by wellorange** [sorrycc/roadhog#519]
src/
   index.js:
           console.log("a")
   index.ejs:
          这里是正常的html代码
.roadhogrc:
  { "entry:"src/app.js"}

package.json:
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start":"roadhog server"
  },
  "author": "",
  "license": "ISC"
}

就是这么几个简单的文其余什么文件都没有,我运行后app.js会运行两遍，因为控制台打印了两遍

roadhog本来是运行两遍还是怎么回事

**Comment by sorrycc** [comment]
删除模板里的 index.js 和 index.css 引用，会自动注入的。
