### ISSUE TITLE
新需求:增加对普通Node项目babel编译支持

### ISSUE THREAD

**Issue by kingyang** [sorrycc/roadhog#52]
增加对普通Node项目babel编译支持

**Comment by sorrycc** [comment]
没 get 到店，详细说明下？

**Comment by kingyang** [comment]
具体需求:
我们小型项目是放在一个前端web和rest api(node)放在一个项目中,前端放在src中,后端放在APP目中,生成结果放在run目录中,而web的dist输出在run/www目录 

大概的目录结构:
-root
 --src
 --app(rest api)
 --run
   --www(常用静态资源直接放在里面)
   ----dist(src的生成目录)
   --app(app编译后运行目录)
 --dev(构建脚本)

目前roadhog能够支撑我们web相关的支持,但rest api这块还需要自己写构建脚本



最终构建会按照项目情况打zip压缩包进行分发([#51](https://github.com/sorrycc/roadhog/issues/51) )
若项目有rest api相关代码,则会把run目录打包(包括运行时必须的node_modules)
若项目没有rest api相关代码,则只会对run/www进行打包

**Comment by sorrycc** [comment]
rest api 是后端代码？后端代码为啥要打包?

**Comment by kingyang** [comment]
方便分发或测试

**Comment by kingyang** [comment]
嗯 rest api 是后端代码

**Comment by sorrycc** [comment]
要把 rest api 下的文件也打包成一个？包含 node_modules 依赖也打进去？感觉已经超出 roadhog 的范畴了。。

**Comment by kingyang** [comment]
嗯 可能是我要求多了哈 ,若roadhog 只定义webpack范围的话就可以不考虑这个问题了.
