### ISSUE TITLE
roadhog是否能方便的支持类似webpack的按需加载

### ISSUE THREAD

**Issue by liangmuxue** [sorrycc/roadhog#527]
之前看到说按需加载可以通过webpack的require.ensure来实现，不过webpack2以后只需要使用import就可以了，并且支持vendor的分离以及按需加载。比如
    new webpack.optimize.CommonsChunkPlugin({
      name:'app',
      async: 'echarts',
      minChunks: ({ resource } = {}) => (
        resource &&
        resource.includes('node_modules') &&
        /echarts|zrender/.test(resource)
      ),
    }),
通过类似的配置，可以按需加载echarts的库文件，并且在jsx中直接写import就好了
打包的时候会把echarts单独打包，并且按需加载。
我的问题是roadhog是否也能实现这样方便的配置方式，来实现按需加载。

**Comment by sorrycc** [comment]
roadhog@2 里会支持配置 commons，等 2 的发布吧。
