### ISSUE TITLE
Roadhog也应该像CRA工具一样，提供一个eject命令

### ISSUE THREAD

**Issue by fhchina** [sorrycc/roadhog#529]
比如把Webpack的配置，完全Dump出来，生成一个webpack.conf.js文件。

**Comment by sorrycc** [comment]
定位不同，roadhog 没有提供 eject 的计划。

**Comment by fhchina** [comment]
有没有手工配置webpack的范本，能够完全支持Ant Design Pro? roadhog目前无法满足我的要求，node_modules下的less没有被处理 @sorrycc
