### ISSUE TITLE
能否支持watch模式工作？

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [sorrycc/roadhog#534]
具体来说，roadhog的server、hmr和proxy等虽然很方便，但不利于嵌入其它应用。比如我现在试图构建的基于Phoenix的[app](https://github.com/zhengxiaoyao0716/honeycomb-adventure)，只需要roadhog提供监测文件改动并编译输出到指定目录即可，其它服务由后端提供了。

可以参考 [parcel watch](https://parceljs.bootcss.com/getting_started.html) 和 [brunch watch](http://brunch.io/docs/getting-started)

**Comment by sorrycc** [comment]
能。

```bash
$ roadhog build --watch
```

**Comment by zhengxiaoyao0716** [comment]
哦，谢谢！

**Comment by WinterWoods** [comment]
roadhog build --watch 这个还是不会监听.

**Comment by LightningVII** [comment]
roadhog build -w 'import model' is defeated
