### ISSUE TITLE
@timer/detect-port 包引发的惨案！

### ISSUE THREAD

**Issue by dkvirus** [sorrycc/roadhog#535]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）  v1.2.2
- Nodejs and Npm version（Nodejs 和 Npm 版本） 8.0.0 and 5.0.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: windows7

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

安装 roadhog。

#### What do you expected?（问题）

`roadhog` 依赖 `react-dev-utils`，而 `react-dev-utils` 又依赖 `@timer/detect-port` 包。公司如果使用的是自己搭建的私有 Npm 服务器，会从淘宝镜像上同步包，但是像 `@` 打头的包是没法同步下来的，导致每次 `npm install` 都会闹点小毛病。

#### What happen?（期望）

咨询下官方的兄弟，能否使用功能相似的包替代 `@timer/detect-port` 包，尽量减少使用 @ 打头的私有包。

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
这是你包同步的问题，后面 `@` 开头的会越来越多，比如 babel。另外，react-dev-utils 的依赖，我改不了。

**Comment by dkvirus** [comment]
排查了一下确实是我这边问题，对于本质仓库去淘宝镜像同步包，会拼接路径去查找包，如：`xxxx/eslint` 去同步 `eslint` 包，如果前面有 `@angular/core` 这种，拼接之后就变成了 `xxxx@angular/core` 默认去同步 core 包，不是 `@` 影响的，是 `/`  影响的，记录一下，防止其它兄弟踩坑。
