### ISSUE TITLE
"roadhog": "^2.0.0-0" Cannot find module '../lib/scripts/server'

### ISSUE THREAD

**Issue by joriewong** [sorrycc/roadhog#536]
npm start
Cannot find module '../lib/scripts/server'

**Comment by sorrycc** [comment]
It's a bug, but you can `roadhog dev` before I fixed it.

**Comment by ctocto** [comment]
"roadhog": "^1.3.1" Cannot find module '../lib/server'
![image](https://user-images.githubusercontent.com/16641120/50582856-8460bf80-0ea0-11e9-9ea5-0110c0105e5f.png)
