### ISSUE TITLE
roadhog2.0怎么配置svg-sprite-loader

### ISSUE THREAD

**Issue by hopperhuang** [sorrycc/roadhog#539]
既然2.0不再支持svg-sprite-loader的属性，那么需要饮用svg-sprite-loader的时候，要怎么去处理呢？

**Comment by sorrycc** [comment]
给 antd-mobile 用？升级 antd-mobile 到 2，已经不需要这个 loader 了。

**Comment by hopperhuang** [comment]
好的，看到antd-mobile 2的升级指南了。再问一个问题，后续有打算增强roadhog可配置性的计划吗？比如，roadhog2 和antd-mobile1结合的话，没有svg配置选项，就需要用网上的图标库去引入icon图标了。当然，还可能出现其他，需要特别配置的webpack-config，有打算开发额外的接口，例如extraWebPackPlugin，extraWebpackConfig这样的接口给开发者去配置吗？？

**Comment by sorrycc** [comment]
`webpack.config.js` 还是支持的，可以随意扩展。
