### ISSUE TITLE
roadhog build --analyze 但是没有生成 stats.html

### ISSUE THREAD

**Issue by herrdu** [sorrycc/roadhog#541]
![image](https://user-images.githubusercontent.com/6762269/34492427-7f45097c-f022-11e7-8796-582ec1f7e02c.png)
 有提示了，但是没有生成stats.html 页面

**Comment by afc163** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/507615/34861153-b9ee9a52-f79d-11e7-8a0b-d53e2b929d31.png">

2.0 以后有一样的问题。

**Comment by sorrycc** [comment]
2.0 是这样，我去更新下文档。

```bash
$ ANALYZE=1 roadhog build
```

**Comment by kaykie** [comment]
看不明白  怎么弄?

**Comment by xiongchen2012** [comment]
> 看不明白 怎么弄? ANALYZE 不是一个命令

ANALYZE 是环境变量，设置成1，然后就可以分析打包结果了。
