### ISSUE TITLE
升级2.0后无法动态require资源, require('./locale/'+config.locale); 

### ISSUE THREAD

**Issue by elivoa** [sorrycc/roadhog#544]
roadhog升级2.0， 之前使用了一个变量来动态引用资源，升级之后报错了。

`
console.log(config);

require('./locale/'+config.locale); 
`

报错：config is  not defined.
但是输出是有值的。

感觉升级roadhog之后require和原来的require不是一个东西了。

请问应该怎样动态的引入资源呢？

**Comment by sorrycc** [comment]
config is not defined? 这在 require 之前啊。

**Comment by elivoa** [comment]
这个是会报错的例子：我的变量是在另外一个文件中的，import进来的就会报错。

// config.js
`export const lang = 'en';`

// index.js

```
import { lang } from './config';
console.log(lang);  // output: en
require('./locale/'+config); // Uncaught ReferenceError: lang is not defined
```
而且使用require和import是一样报错。

我想实现webpack文档中的这这样的效果：

> Every module that could potentially be requested on an import() call is included. For example, import(`./locale/${language}.json`) will cause every .json file in the ./locale directory to be bundled into the new chunk. At run time, when the variable language has been computed, any file like english.json or german.json will be available for consumption.

所以觉得之前的require是运行时执行的，现在的require不是了。

像下面这样直接声明变量就不报错。
```
const lang = 'en';
require('./locale/'+config);
```

**Comment by sorrycc** [comment]
```
./src/index.js
  Line 5:  'config' is not defined  no-undef
```

这是 eslint 报错，config 确实没有定义。。

**Comment by elivoa** [comment]
那eslint如何设置才不阻止build过程呢？

**Comment by elivoa** [comment]
我看了一下并不是eslint报的错。run dev 编译可以通过，页面报错。

![image](https://user-images.githubusercontent.com/958954/34521815-c788278e-f0ca-11e7-820e-49f0f03906b6.png)

这是Console报错：

![image](https://user-images.githubusercontent.com/958954/34521858-f8c48a54-f0ca-11e7-8de0-80ea5ca5487a.png)

**Comment by sorrycc** [comment]
这是运行时错误，上面的是 eslint 报错。

**Comment by elivoa** [comment]
就是这个运行时错误导致我没办法 require 一个带变量的资源（变量是在其他文件中import进来的）。在roadhog1.x的时候是可以这样引用的。而且webpack的文档里面也说可以这样用。现在roadhog2.0的这样用就报错。
如何才能require一个带变量的资源？

**Comment by sorrycc** [comment]
给个能重现的最小库，传到 github 上，我来看下。

**Comment by elivoa** [comment]
好的，这是我上传的最小库。

https://github.com/elivoa/roadhog_bug_test.git

**Comment by sorrycc** [comment]
改成下面这样就好了，没深入探究原因，谁知道的可以告诉我下。

sysconfig.js

```js
export function getLang() {
  return 'en';
}
```

index.js

```js
import { getLang } from './sysconfig/sysconfig'
...
const lang = getLang();
console.log('lang', lang);
const messages = require(`./locales/${lang}`);
```

**Comment by elivoa** [comment]
试了一下，只要声明一个变量指向import进来的值就可以了，可以不用写function也可以生效。

```javascript
import { lang } from './sysconfig/sysconfig'
...
const lang = lang;
const messages = require(`./locales/${lang}`);
```
