### ISSUE TITLE
build出错

### ISSUE THREAD

**Issue by dai875939260** [sorrycc/roadhog#548]
#### Environment(required) | 环境（必填）

- roadhog version 2.0.1
- Nodejs and Npm version node:v8.9.1 npm:v5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

错误堆栈
```
Failed to minify the bundle. Error: 0.0f3f4c41.async.js from UglifyJs
Unexpected token: operator (*) [0.0f3f4c41.async.js:23907,42]
    at compiler.run (/Users/daihy/IdeaProjects/ideaspace/notarycloud/dep2/sys-base/node_modules/af-webpack/lib/build.js:57:23)
    at emitRecords.err (/Users/daihy/IdeaProjects/ideaspace/notarycloud/dep2/sys-base/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/Users/daihy/IdeaProjects/ideaspace/notarycloud/dep2/sys-base/node_modules/webpack/lib/Compiler.js:371:38)
```
错误代码行
```
    s += (digit[Math.floor(num * 10 * (10 ** index)) % 10] + item).replace(/零./, '');

```
#### What do you expected?（预期的正常效果）
正常build，感觉是两个`**`号的问题，该代码出自ant design pro，看了下两个`**`号的用途好像还是个实验性功能
![image](https://user-images.githubusercontent.com/6057326/34546165-172f4b3e-f12d-11e7-88d3-64675c982896.png)

#### What happen?（发生了何种非正常现象）
压缩报错

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
@yesmeck 是 `**` 没转，还是 antd 一定得用 uglify-es 进行压缩了？

**Comment by yesmeck** [comment]
这个不是 antd 里的代码。

**Comment by yesmeck** [comment]
奥，是 ant-design-pro 里的，我看看。

**Comment by yesmeck** [comment]
我本地试着 build 了下 ant-design-pro  没发现问题。而且这个 `**` 已经包含在 [stage-0](https://github.com/sorrycc/roadhog/blob/dbc589ba3f4f58327c02cda16269a215862433bc/src/config/common.js#L17) 里了。

@dai875939260 能否提供一下能重现问题的 repo。

**Comment by dai875939260** [comment]
@yesmeck roadhog有升级到2.0么？1.x版本是没有问题，东西太多不好整，我是按sorrycc的pr升级的

**Comment by yesmeck** [comment]
@sorrycc [这里](https://github.com/umijs/umi/blob/master/packages/babel-preset-umi/src/index.js#L66) 把  transform-exponentiation-operator 排除了。

**Comment by sorrycc** [comment]
修复了，重装 roadhog 试试。
