### ISSUE TITLE
是否可以把自定义的环境变量传给webpack.config.js

### ISSUE THREAD

**Issue by neewbee** [sorrycc/roadhog#549]
https://github.com/sorrycc/roadhog/blob/dbc589ba3f4f58327c02cda16269a215862433bc/src/build.js#L74

改成 process.env

**Comment by sorrycc** [comment]
直接从 process.env 取就好了。

**Comment by neewbee** [comment]
借机会问个另外的问题 ： 如何使用webpack define plugin ?

**Comment by sorrycc** [comment]
配 define 。
