### ISSUE TITLE
roadhog2.0为什么不能自动打开浏览器了？

### ISSUE THREAD

**Issue by hanxiansen** [sorrycc/roadhog#550]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog2.0.1）
- Nodejs and Npm version（Nodejs8.9.3 和 Npm5.0.3）
- Operating environment (e.g. OS name) and its version（操作系统版本）: win10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

运行 roadhog server 不能自动打开浏览器。

#### What do you expected?（预期的正常效果）
之前运行roadhog server 命令能用命令打开浏览器。

#### What happen?（发生了何种非正常现象）
现在不能用命令打开浏览器了，只能手动复制ip和端口号到浏览器上。

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
Try roadhog@2.0.3

**Comment by hanxiansen** [comment]
@sorrycc brother, 你的响应速度真快！

**Comment by 951759534** [comment]
没有Browser=none选项了吗 尝试这样设置 but fail

**Comment by sorrycc** [comment]
@951759534 试过有效，`BROWSER=none roadhog dev`

**Comment by 951759534** [comment]
好的 我搞错了 在windows配置了linux命令了
