### ISSUE TITLE
2.0版本去掉了 dllPlugin，dev编译太慢，有什么的替代品可以尝试么？

### ISSUE THREAD

**Issue by elivoa** [sorrycc/roadhog#552]
有什么办法可以提高dev server速度的么？我的项目dev编译时间半分钟左右。
现在没了dll plugin，dev启动速度和重新编译速度都很慢。
想寻找替代品。

**Comment by sorrycc** [comment]
自己实现按需编译，或者等 [umi](https://github.com/umijs/umi) 的发布。
