### ISSUE TITLE
[Roadhog 2] Babel在Windows上不能使用

### ISSUE THREAD

**Issue by ghostoy** [sorrycc/roadhog#553]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）1.3.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）Nodejs 9.3.0 Npm 5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）: Windows 10 Pro

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

1. src目录里某文件使用Babel支持的语法，比如import
2. 运行roadhog dev

#### What do you expected?（预期的正常效果）

无错误

#### What happen?（发生了何种非正常现象）

报错：Unexpected token import

打开DEBUG环境变量，发现Babel忽略了src下面文件的转换。观察发现由于Babel使用反斜杠（\）的路径名，但是Roadhog注册的路径使用的是正斜杠（/），导致正则表达式与路径不匹配。

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
roadhog@2? 匹配是通过正则实现的，应该不会才对。

```
{
  test: /\.(js|jsx)$/,
  exclude: /node_modules/,
  use: babelUse,
},
```

手上没有 windows 电脑，方便的话帮忙查找下原因。

**Comment by ghostoy** [comment]
是src目录的正则表达式问题，Windows的绝对路径是（\）的，Babel的匹配也是按照\分隔的路径做的匹配，但是Roadhog里的`registerBabel`里，用了一个`winPath`把正则表达式路径里的\都替换成了/，导致Babel匹配失败。

**Comment by sorrycc** [comment]
试试 roadhog@2.0.4
