### ISSUE TITLE
[Roadhog 2] devtool选项不能正确生成source map

### ISSUE THREAD

**Issue by ghostoy** [sorrycc/roadhog#554]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）2.0.3
- Nodejs and Npm version（Nodejs 和 Npm 版本）Nodejs: 9.3.0 Npm: 5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）: Windows 10 Pro

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

1. 使用React的JSX语法实现一个简单页面，或者使用`import { localVar} from 'some-module'`语法
2. `.webpackrc.js`里`devtool`设置成`eval-source-map`
2. 运行roadhog dev
3. 浏览器打开页面的开发者工具，查看源代码

#### What do you expected?（预期的正常效果）

根据webpack的文档，`eval-source-map`的文档，源代码应该正确显示原始JSX语法或import语法

#### What happen?（发生了何种非正常现象）

显示的源代码里的JSX语法和import语法都被转义过，在roadhog v1的是没有这个问题的。

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by ssehacker** [comment]
+1 ， 请尽快解决，谢谢

**Comment by fantaishao** [comment]
+1 ， 也碰到这个bug了

**Comment by remotesc2** [comment]
关注中~
现在调试，很痛苦

**Comment by lyingd** [comment]
关注，试了各种source map，都不能正确生成

**Comment by TimYi** [comment]
我也遇到了这个问题，看来是个疑难杂证，source map已经生成了，但是在浏览器中没有效果。

**Comment by csshere** [comment]
同问，es5调试太痛苦了

**Comment by yiqingj** [comment]
关注

**Comment by chenlin8** [comment]
关注

**Comment by cjm0000000** [comment]
关注

**Comment by sunny920406** [comment]
关注

**Comment by weifansc** [comment]
关注

**Comment by cyh5kf** [comment]
关注，希望能尽快解决

**Comment by CodingPapi** [comment]
关注这个问题好久了，大年初一拜个年，过年好。顺便催下。。。希望尽快解决

**Comment by YinRenjie1993** [comment]
关注中~

**Comment by douglasjunior** [comment]
@sorrycc are you looking to this?  Can I do anything to help?

**Comment by gjqiang** [comment]
这个问题解决了就升上2

**Comment by gjqiang** [comment]
关注。。

**Comment by sorrycc** [comment]
今明两天修复。

**Comment by zenjava** [comment]
太痛苦了 没法调试

**Comment by TimYi** [comment]
立了flag, 会发布新版本么？

**Comment by sorrycc** [comment]
It's fixed [roadhog@2.3.0-beta.1](https://github.com/sorrycc/roadhog/releases/tag/2.3.0-beta.1).

**Comment by douglasjunior** [comment]
Worked, thanks!

![image](https://user-images.githubusercontent.com/1512341/36867225-43498ec4-1d73-11e8-922d-1544fc6cf74b.png)

**Comment by Malenconiaprincep** [comment]
cool

**Comment by TimYi** [comment]
cool

**Comment by pengshaosu** [comment]
如果使用了按需加载，调试代码时运行的是编译后的代码（分割的代码），还是没法调试未编译的源码。
求解

**Comment by LeehanLee** [comment]
> It's fixed, try [roadhog@2.3.0-beta.1](https://github.com/sorrycc/roadhog/releases/tag/2.3.0-beta.1).

大佬，edge下可以看到source map了，但是firefox下似乎还是看不到source map，版本2.5.0-beta.4
![图片](https://github.com/sorrycc/roadhog/assets/14244974/510f37da-b5b4-41db-9cea-44eb167cb9e0)
