### ISSUE TITLE
[Roadhog 2] .webpackrc cann`t use [import: [ ... ]]

### ISSUE THREAD

**Issue by remotesc2** [sorrycc/roadhog#557]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）2.0.6
- Nodejs and Npm version（Nodejs 和 Npm 版本）Nodejs: 8.9.1, Npm: 5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）: window 10 pro

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

在 roadhog@2 中，无法使用 babel-plugin-import 中的 [...] 语法，例如

```
"extraBabelPlugins": [
    "transform-decorators-legacy",
    ["import", 
       [
            { "libraryName": "antd", "libraryDirectory": "es", "style": true },
            { "libraryName": "xxxx", "libraryDirectory": "es", "style": true }
       ]
    ]
  ],
```

#### What do you expected?（预期的正常效果）

和 roadhog@1.3 一样，可以如此使用

#### What happen?（发生了何种非正常现象）

会导致如下异常

```
Module build failed: Error: .plugins[1][1] must be an object, or undefined
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

**Comment by sorrycc** [comment]
babel 7 的配置项不支持数组了，改成引多个 `import` 插件的方式。

```
"extraBabelPlugins": [
    "transform-decorators-legacy",
    ["import",
            { "libraryName": "antd", "libraryDirectory": "es", "style": true }
    ],
    ["import",
            { "libraryName": "xxxx", "libraryDirectory": "es", "style": true }
    ]
  ],
```

**Comment by remotesc2** [comment]
babel 的错误确实没有了，不过出现了错误提示...

```
isPlainObject is not defined
```

我查看了 node_modules 里，确实是有 is-plain-object 这个文件夹

**Comment by remotesc2** [comment]
当在 env 当中使用两个对象时，就会出现 `isPlainObject is not defined` 的错误提示，例如：

```
"development": {
    "define": {
      "__DEV__": true
    },
    "extraBabelPlugins": [
      "dva-hmr"
    ]
}
```

**Comment by sorrycc** [comment]
已修复，重装 roadhog 试试。
