### ISSUE TITLE
roadhog2.0下IE报错

### ISSUE THREAD

**Issue by dai875939260** [sorrycc/roadhog#558]
#### Environment(required) | 环境（必填）

- roadhog version 2.0.6
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

https://github.com/ant-design/ant-design-pro/issues/612

#### What happen?（发生了何种非正常现象）

好像是这段代码没转
```
ErrorOverlay.setEditorHandler(function editorHandler(errorLocation) {
  // Keep this sync with errorOverlayMiddleware.js
  fetch(`${launchEditorEndpoint}?fileName=` + window.encodeURIComponent(errorLocation.fileName) + '&lineNumber=' + window.encodeURIComponent(errorLocation.lineNumber || 1));
```
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
修复了，重装 roadhog 试试。
