### ISSUE TITLE
ie11下报错：SCRIPT1014: 无效字符，报错代码位置：af-webpack/lib/webpackHotDevClient.js 33行的上句号在ie中不能被识别

### ISSUE THREAD

**Issue by qiaogr** [sorrycc/roadhog#560]
已经确认在index中引入了以下库：
const _es5shim = require('es5-shim');
const _es5sham = require('es5-shim/es5-sham');
const _polyfill = require('console-polyfill');
const _assign = require('core-js/fn/object/assign');
const _babekPolyfill = require("babel-polyfill");
const _es6Promise = require('es6-promise');
const _fetchDetector = require('fetch-detector');
const _fetchIe8 = require('fetch-ie8');
const _fetchJsonp = require('fetch-jsonp');

**Comment by sorrycc** [comment]
重装 roadhog 试试，在 https://github.com/umijs/umi/commit/7858491a31ec8b37a9989fd9685c36dfffa0017e 修复了。

**Comment by qiaogr** [comment]
多谢@sorrycc ，更新以后就可以了。但是ie上会出现fouc闪屏的问题。谷歌上开发环境没有闪屏的问题，但是打包之后访问的话谷歌上也会有闪屏的问题。

**Comment by sorrycc** [comment]
闪屏的问题新启一个 issue 详细描述下吧，没明白。
