### ISSUE TITLE
fouc闪屏问题

### ISSUE THREAD

**Issue by qiaogr** [sorrycc/roadhog#562]
ie11 浏览器：刷新浏览器页面会先变成白色，然后才会显示渲染好的页面
chrome、firefox：在开发环境中没有问题，但是打包之后访问也会出现如上ie中闪屏问题。

**Comment by sorrycc** [comment]
打包后不是提取了 css 出来吗？css 在 head 里引入，也会有闪屏问题？

**Comment by qiaogr** [comment]
刚刚测了一下确实有的，
这个是打包出来的index.html:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dva Demo</title>
  <link rel="stylesheet" href="index.css" />
</head>
<body>

  <div id="root"></div>
  <script src="index.js"></script>

</body>
</html>
下面是我修改的.webpackrc文件的内容。打包出来之后的index.js文件有1.54MB...
{
	"entry": "src/index.ts",
	"extraBabelPlugins": [
		"dva-hmr",
		["import", { "libraryName": "antd", "style": "css" }]
	]
}
我是通过dva-cli新建的项目
dva-cli version 0.9.2
    dva version 2.1.0
roadhog version 2.0.6。
配置文件没有其他的修改。

**Comment by qiaogr** [comment]
index.html的内容：<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dva Demo</title>
  <link rel="stylesheet" href="index.css" />
</head>
<body>

  <div id="root"></div>
  <script src="index.js"></script>

</body>
</html>

**Comment by sorrycc** [comment]
得打包出 css 文件，然后在 index.html 里通过 `<link>` 引入这个 css 文件。

**Comment by sorrycc** [comment]
非 roadhog 问题，issue 我关了。
