### ISSUE TITLE
support augument as filter of roadhog test

### ISSUE THREAD

**Issue by afc163** [sorrycc/roadhog#563]
```
roadhog test .e2e.js
```
  
like

```
jest .e2e.js
jest src/components
```

**Comment by sorrycc** [comment]
It seems `roadhog test` have some problem with UI test, I have work on it for a long time, but did not found the solution.

**Comment by afc163** [comment]
It works fine: https://github.com/ant-design/ant-design-pro/pull/640

**Comment by sorrycc** [comment]
Bumped roadhog@2.1
