### ISSUE TITLE
配置outputPath 和 publicPath 后 Disconnected from the devServer, trying to reconnect...

### ISSUE THREAD

**Issue by kousuutetu** [sorrycc/roadhog#565]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）"roadhog": "^2.0.6",
- Nodejs and Npm version（Nodejs 和 Npm 版本）Nodejs (v6.9.1)  Npm(3.10.8)
- Operating environment (e.g. OS name) and its version（操作系统版本）: macOS 10.13.1 (17B1003)

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
```
pro new
npm start

#修改.webpackrc
#删除
"disableDynamicImport": true,
#在其位置添加
"outputPath": "../web/assets/bundle",
"publicPath": "/assets/bundle/",
```

#### What happen?（发生了何种非正常现象）
```
Disconnected from the devServer, trying to reconnect...
```

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
修改 `.webpackrc` 后需要重启 webpack 的。

**Comment by kousuutetu** [comment]
@sorrycc 重启后仍然不可以

<img width="1280" alt="2018-01-11 9 40 12" src="https://user-images.githubusercontent.com/5842445/34804441-936e2b30-f6b3-11e7-8edc-6db4e63291bf.png">

**Comment by sorrycc** [comment]
不配 publicPath 就好了？

**Comment by kousuutetu** [comment]
是的, 两个都删除了就好了...

**Comment by sorrycc** [comment]
估计是 bug，我找时间排查下。

**Comment by kousuutetu** [comment]
嗯好的, 我先脚本替换来使用吧

**Comment by kousuutetu** [comment]
@sorrycc 这样配置可以
```
  "env": {
    "production": {
      "outputPath": "../web/assets/bundle",
      "publicPath": "/assets/bundle/"
    }
  }
```

**Comment by agalwood** [comment]
@kousuutetu 握爪，升级到roadhog 2.0后同样的问题，roadhog dev启动失败，周末折腾了两天啊啊，感谢你提供的配置搞定了

**Comment by tsuijie** [comment]
如何配置或者禁用此功能？有些特殊情形下，需要将所有资源输出到public文件夹，而不是dist文件夹。

**Comment by goonwzz** [comment]
dev 模式下 不要 添加“publicPath” 就可以了

**Comment by sorrycc** [comment]
楼上正解，roadhog@2 的 publicPath 在 dev 模式下没有写死为 `/`，所以 publicPath 改成其他的之后，`index.html` 会找不到。
