### ISSUE TITLE
support  babel node_modules ?

### ISSUE THREAD

**Issue by kingyang** [sorrycc/roadhog#573]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
2.1.0 

#### What do you expected?（预期的正常效果）
项目中期望支持node_modules中es6文件的babel处理

看代码中 af-webpack/registerBabel是支持ignore的，但roadhog没有传递配置，是有其它方案支持这类需求吗

**Comment by sorrycc** [comment]
Try [extraBabelIncludes](https://github.com/sorrycc/roadhog#extrababelincludes).

**Comment by kingyang** [comment]
@sorrycc 
谢谢回复.

在提问前我是尝试了的写法,extraBabelIncludes写法,也参考了部分Issues的提问,#40 #220 
你在回复中涉及到的连接已经不能访问了

> https://github.com/sorrycc/roadhog/tree/master/test/fixtures/build/extraBabelIncludes

我的extraBabelIncludes写法
```extraBabelIncludes: ['/node_modules/prettier-xw/']```

我也尝试了```./node_modules/prettier-xw/```

**结果是都没有生效**

完整配置.
```javascript
export default {
  entry: 'src/entry/*.js',
  theme: './src/theme.js',
  html: { template: './src/index.ejs' },
  hash: true,
  ignoreMomentLocale: true,
  externals: cfg.externals,
  extraBabelIncludes: ['/node_modules/prettier/'],
  extraBabelPlugins: [
    '@babel/transform-runtime',
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
    production: {
      outputPath: './dist/',
      publicPath: './',
    },
  },
};
```

**Comment by sorrycc** [comment]
？为啥 prettier 需要走 babel？这个不应该被打入前端代码吧。

**Comment by kingyang** [comment]
prettier 目前官方的包是不支持web,我在项目中用了prettier 的部分核心源码,重新写了部分组件,是通过npm+git安装的
