### ISSUE TITLE
IE11 React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by yixiudadi** [sorrycc/roadhog#579]
用roadhog2.1.0 新生成的官方demo 打包后在ie11 下报错

SCRIPT5022: Minified React error #143; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=143 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
文件: index.68a8fa9c.js，行: 1，列: 100783

打包前开发时能正常在IE11 跑起来

143 我去我去官方查是 React.Children.only expected to receive a single React element child.

自己尝试来很多办法和找了很多 没有找到合适的解决方案

**Comment by sorrycc** [comment]
是不是要加 `@babel/polyfill`?

**Comment by yixiudadi** [comment]
加了，也是这样

**Comment by sorrycc** [comment]
用 dva-cli 创建的项目？

**Comment by yixiudadi** [comment]
是的

**Comment by yixiudadi** [comment]
之前1.X的版本不会出现这种情况

**Comment by sorrycc** [comment]
试试不压缩打包会不会有问题，`NO_COMPRESS=1 roadhog build`，我手上没 windows 电脑。

**Comment by yixiudadi** [comment]
还是一样

**Comment by yixiudadi** [comment]
index.js，行: 14832，列: 489

**Comment by yixiudadi** [comment]
大概能推断出是那部分的问题吗，我自己也去找找解决方案，主要现在是没有解决的方向

**Comment by sorrycc** [comment]
> 是不是要加 @babel/polyfill?

你没试过？我加了之后就好了。

**Comment by yixiudadi** [comment]
我试了，polyfill 和不压缩打包都加了

**Comment by yixiudadi** [comment]
你的polyfill是加在哪的

**Comment by sorrycc** [comment]
NO_COMPRESS 有点问题，不用管他，`src/index.js` 里第一行加上 `import '@babel/polyfill'` 就好了。

**Comment by yixiudadi** [comment]
难道和ie11的版本有关

**Comment by yixiudadi** [comment]
我是加在这个文件的，不过不是第一个

**Comment by yixiudadi** [comment]
现在在路上，我回家了再试试看

**Comment by yixiudadi** [comment]
感谢，感谢，搞定了，
测试过了
2.X的版本要在第一行引入。在dva之前。
之前项目是1.X的版本可以不用放在第一行

**Comment by landfei** [comment]
在IOS8上也有同样的问题, NO_COMPRESS=1加上就好了,可是我想压缩用什么方法?

**Comment by jingkeke** [comment]
我也遇到了.....edge没问题, IE11本地测试没问题,就是打包后IE11报这个错.搜了半天,看到这个文章,加上NO_COMPRESS=1加上是解决了....但是是不是就是没压缩了...

**Comment by kairi1227** [comment]
@sorrycc 这个问题在2.3.0依然存在。
`import '@babel/polyfill'` 还是不起作用。
只有在build的时候，配置`COMPRESS=none`才可以，但是打包出来的文件好大。希望给出一个解决方案。
