### ISSUE TITLE
我需要做一个自动替换服务器代码的功能

### ISSUE THREAD

**Issue by 492580195** [sorrycc/roadhog#580]
我需要自动更新服务器部门模块代码，但是chunkname无法设置，因为全部都是hash，或者async的那么我如何找到我要替换的模块文件的名字.

**Comment by sorrycc** [comment]
试试用 https://github.com/sorrycc/roadhog#manifest 生成映射表。

**Comment by 492580195** [comment]
如果我要动态添加组件模块文件，那么这种情况就无法满足，我需要做一个开发平台，可动态为项目加入编译后模块组件到项目中，

**Comment by 492580195** [comment]
{
  "0.async.js": "0.async.js",
  "commons.js": "commons.js",
  "index.css": "index.css",
  "index.js": "index.js",
  "static\\yay.jpg": "static/yay.44dd3333.jpg"
}

生成后无法对照0.async.js是什么了

**Comment by sorrycc** [comment]
`import()` 可以指定 chunkname 的，看 webpack 文档。

**Comment by 492580195** [comment]
谢谢!可以了
