### ISSUE TITLE
对文件code spliting后，文件并不是按需加载的

### ISSUE THREAD

**Issue by guopingzhao** [sorrycc/roadhog#583]
const PageA = lazy(import(/* webpackChunkName: "pagea" */'./pageA'));
const PageB = lazy(import(/* webpackChunkName: "pageb" */'./pageB'));
const PageC1 = lazy(import(/* webpackChunkName: "pagec1" */'./pageC/pageC1'));
const PageC2 = lazy(import(/* webpackChunkName: "pagec2" */'./pageC/pageC2'));

**Comment by sorrycc** [comment]
你配了 [disableDynamicImport](https://github.com/sorrycc/roadhog#disabledynamicimport) 了？

**Comment by guopingzhao** [comment]
没有配置，文件打包出来是文件拆分了的，但是是进入系统就加载了所有的js文件

**Comment by sorrycc** [comment]
那是逻辑的问题，import() 的执行得按需。

**Comment by guopingzhao** [comment]
class Lazy extends React.Component {
  state = {
    Compoennt: null,
  }
  render() {
    const { Compoennt } = this.state;
    return Compoennt && <Compoennt {...this.props} />;
  }
  async componentDidMount() {
    const { com } = this.props;
    const Com = (await com).default;
    this.setState({
      Compoennt: Com,
    });
  }
}
function lazy(com) {
  return props => <Lazy props={props} com={com} />;
}

这是懒加载组件和方法

**Comment by sorrycc** [comment]
`lazy(import())`，这里直接执行了，当然就加载了，改成类似 `lazy(() => import())` 的方式。

**Comment by guopingzhao** [comment]
thanks
