### ISSUE TITLE
Source maps for production builds

### ISSUE THREAD

**Issue by megawac** [sorrycc/roadhog#585]
### What problem does this feature solve?
Support including source maps in production builds when an option is enabled. This will ease identifying issues that may arise in some production environments. At least at my company our test team runs on specific production builds and will include stack traces in their tickets; having source maps will make their stack traces much more useful

### What does the proposed API look like?
In `.roadhogrc`

```js
"env": {
    "production": {
       "enableSourcemaps": true
    }
  }
```

**Comment by sorrycc** [comment]
If you are using roadhog@2, you could configure it via `devtool`, https://github.com/sorrycc/roadhog#devtool

**Comment by megawac** [comment]
That's sufficient for now, thanks

**Comment by megawac** [comment]
The one issue I have with doing this through `devtool` is that I can't have different configurations based on whether I'm developing or if I'm building a production bundle. For instance, before roadhog my webpack configs typically had

  `devtool: production ? '#source-map' : process.env.SOURCEMAP_PRAGMA || '#inline-source-map',`
