### ISSUE TITLE
新版怎么配置scss?

### ISSUE THREAD

**Issue by Andesome** [sorrycc/roadhog#590]
官方文档说的不甚明了，可以给个配置的demo吗？

**Comment by sorrycc** [comment]
安装 node-sass 和 sass-loader 依赖，然后在 .webpackrc 里配置 `sass: {}` 。

**Comment by Andesome** [comment]
这个我知道，我是不知道json里面怎么配？/捂脸

**Comment by Tommy-White** [comment]
When I code  `sass: true,` I got an error `The sass config must be Plain Object, but got true`. Are there have some pre-check with the sass config. I've seen the `commit` [e39dbdb](https://github.com/sorrycc/roadhog/commit/e39dbdb6ac97bf0edbebe883bef00b1d255a92d5) that found I could also code `sass: {},`  it's same as  `sass: true,` but what should I DO just support sass without any options.
