### ISSUE TITLE
roadhog build 中能否设置过滤文件夹？？？？

### ISSUE THREAD

**Issue by coleShang** [sorrycc/roadhog#593]
只在build时候过滤 server的时候不过滤

**Comment by sorrycc** [comment]
什么叫过滤？

**Comment by coleShang** [comment]
比如 ant-design-pro项目 的public文件夹 build 的时候会直接把这个文件夹下的内容复制过去 ，public下我建了一个 aa 的文件夹  我需要build不把aa也复制过去~~

**Comment by sorrycc** [comment]
为啥会有这个需求？

**Comment by sorrycc** [comment]
可以在 build 后加命令，比如 `roadhog build && rm -rf dist/aa`。

**Comment by coleShang** [comment]
额~~我思路受限了  - -！
