### ISSUE TITLE
suggest body-parser strict mode set false

### ISSUE THREAD

**Issue by zhiyan** [sorrycc/roadhog#596]
#### Environment(required) 

All

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
```
mock:
'POST /test' : {success: true}

service:
request('/test', {
 headers:{
  'Content-Type': 'application/json'
 },
 body: 1
}
```

#### What do you expected?（预期的正常效果）
mock return {success: true}

#### What happen?（发生了何种非正常现象）
return 400 of body parse error

I think as a mock server it dont need to validate request body so much. Wish turn it off:
```
devServer.use(bodyParser.json({ limit: '5mb', strict: false }));
```

**Comment by sorrycc** [comment]
Done, will support in next release.
