### ISSUE TITLE
2.0版本 如何添加svg的loader呢？ 

### ISSUE THREAD

**Issue by devmsg** [sorrycc/roadhog#597]
如题 
![image](https://user-images.githubusercontent.com/15261658/35472442-2ae251f0-03aa-11e8-80c7-6d7062b54477.png)
配置项
我看https://www.npmjs.com/package/roadhog 并没有关于  svg-sprite-loader
使用的ui是ant-mobile  用dva2按照官网给的icon 加载方式 并不可取  请给个解决方案 谢谢

**Comment by sorrycc** [comment]
给 antd-mobile 用？升级 antd-mobile 到 2，已经不需要这个 loader 了。

**Comment by devmsg** [comment]
@sorrycc  好吧 反正按照mobile的文档来看 是加载不出来svg的  那我再去mobile那边发个issues吧 谢谢 云谦兄

**Comment by sorrycc** [comment]
记得 @paranoidjk 回答过这个问题的，参考这个呢？https://github.com/sorrycc/blog/issues/55#issuecomment-358288169

**Comment by devmsg** [comment]
@sorrycc  初步判定的原因是 roadhog 将所有的 img 以及 svg都解析成了 base64格式的 所以导致前端解析不了  并且按照antd-mobile2的icon加载方式 是show不出来的

**Comment by birdycn** [comment]
请问你解决了吗。。。webpack配置能发一份吗

**Comment by zcfreestyle** [comment]
请问这个问题解决了吗，require进来的svg是base64 导致自定义的Icon组件显示不了，如果解决了，webpackrc的配置借我参考一下

**Comment by Carrotzpc** [comment]
同样的问题 +1，暂时在 `url-loader` 的 `exclude` 数组里面加上了 `/\.svg$/`，`webpack.config.js` 配置如下：
```js
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin')

module.exports = webpackConfig => {
  webpackConfig.module.rules.forEach(item => {
    if (String(item.loader).indexOf('url-loader') > -1) {
      item.exclude.push(/\.svg$/)
    }
  })

  webpackConfig.module.rules = ([
    {
      test: /\.svg$/,
      use: [
        {
          loader: 'svg-sprite-loader',
          options: {
            extract: true,
          },
        },
        {
          loader: 'svgo-loader',
          options: {
            plugins: [
              { removeTitle: true },
              { removeStyleElement: true },
            ],
          },
        },
      ],
    },
  ]).concat(webpackConfig.module.rules)

  webpackConfig.plugins = webpackConfig.plugins.concat([
    new SpriteLoaderPlugin(),
  ])

  return webpackConfig
}
```

@sorrycc 有其他好的解决方案吗？

**Comment by zcfreestyle** [comment]
@Carrotzpc  按照你的配置试了一下。package.json如下
`    "svg-sprite-loader": "^3.7.3",
    "svgo-loader": "^2.1.0"`
结果require了一张svg报错 ` ./src/assets/xh/svg/home.svg
Module build failed: TypeError: callback is not a function`

**Comment by zcfreestyle** [comment]
@Carrotzpc  按照你的配置试了一下。package.json如下
`    "svg-sprite-loader": "^3.7.3",
    "svgo-loader": "^2.1.0"`
结果require了一张svg报错 
![_20180322180719](https://user-images.githubusercontent.com/30515821/37765134-6b76e130-2dfe-11e8-85e9-c4af7796edff.png)

**Comment by Carrotzpc** [comment]
@zcfreestyle 没遇到过，`svg-sprite-loader` 配置问题可以看看官方文档 https://github.com/kisenka/svg-sprite-loader

**Comment by zcfreestyle** [comment]
svg-sprite-loader配置成功
![2](https://user-images.githubusercontent.com/30515821/37810990-3d0ac9bc-2e92-11e8-985e-a59d80ebebe9.png)
webpack.config.js配置如下：
![1](https://user-images.githubusercontent.com/30515821/37810987-3cd3672e-2e92-11e8-99f4-0e2b4b5f7607.png)
.webpackrc.js配置如下：
![3](https://user-images.githubusercontent.com/30515821/37810982-358ce90e-2e92-11e8-89d7-ca31f40d4e7e.png)
