### ISSUE TITLE
可以把is-ali-env中检查到不是阿里内部环境后打印返回状态码去除吗？

### ISSUE THREAD

**Issue by sunny920406** [sorrycc/roadhog#600]
roadhog@2.2.0
在运行buid，或dev命令时每次都会去检查是否是内部ip,但是我们不是阿里内部环境，所以每次运行命令时控制台都会打印404，强迫症患者很难受啊！

**Comment by sorrycc** [comment]
😓，404 是这个打印的啊。

**Comment by sunny920406** [comment]
里面有这样一段代码
  if (res.status === 200) {
        return res.json();
      } else {
        console.log(res.status);
        resolve(false);
      }
就是那个console.log

**Comment by remotesc2** [comment]
我也在好奇从某天开始，就都冒出来个 404，已经有人扒到源码了。。。

**Comment by sorrycc** [comment]
Fixed.

**Comment by jwmann** [comment]
I'm still getting an outbound connection to this.
I don't get a 404 but I'd rather it not make an external call at all.

#765
