### ISSUE TITLE
roadhog 2.0 升级遇到的坑..........

### ISSUE THREAD

**Issue by dkvirus** [sorrycc/roadhog#601]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） 2.2.0
- Nodejs and Npm version（Nodejs 和 Npm 版本） 8.0.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: window7

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

对 roadhog 进行升级，发现有两个地方一直报错。

1. 关于扩展运算符

roadhog1.0 里扩展运算符位置没有严格要求，当时写的时候是放在前面；
```
const EditorModal = ({ ...modalProps, item = {} }) => {
```
roadhog2.0 里要求扩展运算符的变量必须放在最后面，否则报错；
```
const EditorModal = ({ item = {}, ...modalProps }) => {
```

这个改动不知道是 es 的改动还是 babel 的改动，总之所有代码都修改了一遍，很是麻烦.........

2. 'xxx' does not contain an export named 'xxxx' 报错

这个问题我在 [stackoverflow](https://stackoverflow.com/questions/44172727/home-does-not-contain-an-export-named-home) 上找到了答案。

roadhog 1.* 写法：

utils.js
```
export default {
  icon,
  config,
}
```

home.js
```
import { icon, config } from 'utils';
```

roadhog 2.* 就会报错 does not contain an export named。原因就是 utils 导出的是默认对象，得像下面这么写才行。

home.js
```
import utils from 'utils';
const { icon, config } = utils;
```

![image](https://user-images.githubusercontent.com/29170168/35667948-76d99212-076a-11e8-9699-ff9bb8a08275.png)

又要全部改........

3. roadhog dev 启动之后，页面变成了这样：

暂时还不知道啥原因。

![image](https://user-images.githubusercontent.com/29170168/35667884-37b8c0bc-076a-11e8-8504-c5688eb15e1d.png)

4. 项目启动控制台莫名其妙打印 404？？

![image](https://user-images.githubusercontent.com/29170168/35667974-91d2cd7c-076a-11e8-9447-90fe78ae22d8.png)

**Comment by sunny920406** [comment]
这个问题我已经提了，404是在检查内部环境那里打印出来的
require('atool-monitor').emit();

**Comment by sunny920406** [comment]
出现你的那个页面是应为你在.webpackrc里配置了publicPath 才会这样，在路径后加你配置的那个路径就可以了

**Comment by dkvirus** [comment]
@sunny920406 多谢兄弟，页面出来了。

**Comment by feibi** [comment]
问题2还有其他解决方案吗

**Comment by archerU** [comment]
问题3 还是没有解决怎么破

**Comment by jszjgqq** [comment]
@archerU 

"publicPath": process.env.NODE_ENV === 'production' ? 'http://xxxxxxxxxxx' : '/',

**Comment by 15207799874** [comment]
问题3如何解决？？？
