### ISSUE TITLE
build: roadhog build api proxy url

### ISSUE THREAD

**Issue by kbardi** [sorrycc/roadhog#608]
#### Environment(required) | 环境（必填）

- roadhog version: (1.3.4),
- Nodejs and Npm version（Nodejs v6.9.1 Npm 5.6.0）
- Operating environment (OS High Sierra) and its version（10.13.3）:
- Antd (3.2.0)
- dva (2.1.0)

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
I execute "npm run build" and I need to setup api url, because we use an API. In dev with no-proxy it works great, but build doesn't work. How can I configure api url for build?

#### What do you expected?（预期的正常效果）
I expect to call our api from our built web.

#### What happen?（发生了何种非正常现象）
It calls api methods on localhost (running url) and it doesn't exists any API there.

#### Re-producible online demo (可复现的在线demo)

Thanks in advance for any answer @sorrycc.
<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
Proxy is used for debugging, you should request the real server api after the build.

**Comment by jwmann** [comment]
@sorrycc Where do I put the real server api code?
I'm assuming _not_ in `.roadhogrc.mock.js`

I tried to put it in `/src/utils/request.js` but it overwrites the Mock API when using `npm start`

**Comment by jwmann** [comment]
@sorrycc 
Also how do I use the `process.env.NO_PROXY` inside `/src/utils/request.js`?

As far as I understand:
`npm start` should use _fake data_ from `.roadhogrc.mock.js`
`npm run start:no-proxy` should ignore fake data.

But if you changed `src/utils/requests.js` so that it uses the actual real API server, the real API is used even when you use `npm start`

**Comment by kbardi** [comment]
Hi @jwmann, what I've done is inside publicRequest function, at the beginning, I wrote:
`
export function publicRequest(url, options) {
  let apiUrl = url;
  if (process.env.NODE_ENV !== 'development') {
    apiUrl = `https://your_domain.com${apiUrl}`;
  }

  return fetch(apiUrl, fetchOptions)
  ...
`
so if I'm not in development environment,  it will use "https://your_domain.com".

I'm still with troubles because I need to distinguish between production environment and staging or UAT environment. NODE_ENV doesn't contain this information, so I have to update manually url before each deploy.

@sorrycc Probably there is a better way to do that, but I don't know how to do it in a different way.

Cheers

**Comment by kbardi** [comment]
Hi @jwmann, I found a new solution for this. and it works great.

**.roadhogrc.js**
I converted my roadhogrc from json to javascript file.
Then I added define attribute like below:
```
define: {
    'process.env': {},
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.API_ENV': process.env.API_ENV,
  },
```
So now I have available to use API_ENV.

**src/utils/request.js**
Inside request I created a constant with my available environments:
```
const availableEnvironments = {
  staging: 'https://staging_api.my_url.com',
  production: 'https://api.my_url.com',
  uat: 'https://uat_api.my_url.com',
};
```

and a method that returns full url with host, receiving the request uri.
```
export function getRequestHost(url) {
  let apiUrl = url;

  if (process.env.API_ENV !== 'development') {
    apiUrl = availableEnvironments[process.env.API_ENV] + apiUrl;
  }
  return apiUrl;
}
```

So from my publicRequest method I call that function to fetch data:
```
export function publicRequest(url, options) {
    ...
    const apiUrl = getRequestHost(url);
    return fetch(apiUrl, options)
    ...
}
```

**package.json**
And finally I added some scripts commands to run for each environment deploy.
> "start:no-proxy": "cross-env API_ENV=development roadhog server --debug",
> "start:staging-proxy": "cross-env API_ENV=staging roadhog server --debug",
> "build:local": "cross-env API_ENV=development roadhog build",
> "build:staging": "cross-env API_ENV=staging roadhog build",
> "build:production": "cross-env API_ENV=production roadhog build",

**cross-env** is important because it will work on Windows, Linux and Mac.

**Comment by jwmann** [comment]
@kbardi I will try this out, thanks! 👍 
I'll let you know how it goes.

**Comment by jwmann** [comment]
Well I gave it a shot but it doesn't seem to work for me.
First of all, I didn't have a `.roadhogrc.js` so I made one and put in exactly this:
```
define: {
  'process.env': {},
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.API_ENV': process.env.API_ENV,
}

```

And it had no affect.

Then I added that same thing to my `.roadhog.mock.js` and it actually made my dva redux setup to stop working. Probably because it broke my `request.js` call
```
SyntaxError: Unexpected token < in JSON at position 0
    at request.js:75
    at <anonymous>
```

Any ideas?

**Comment by kbardi** [comment]
@jwmann  Can you add your request.js file? It throws an error on line 75, but I don't know what is there.

If you hadn't .roadhogrc.js file is because you have a .roadhogrc file. You can use a javascript file (.roadhogrc.js) OR a json file (.roadhogrc), but you shouldn't use both. Please try to copy all settings from your json file to your js file, and remove .roadhogrc, because for the settings I sent before you need to use javascript one.

**Comment by jwmann** [comment]
@kbardi I didn't have a `.roadhogrc` or a `.roadhogrc.js` I literally only have a `.roadhog.mock.js`
Adding a `.roadhogrc.js` didn't seem to do anything.

This is almost exactly my `request.js` (I'm using ant-design-pro)
https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js

My `.roadhog.mock.js` looks very similar to this
https://github.com/ant-design/ant-design-pro/blob/master/.roadhogrc.mock.js

Maybe there's something unique in the way ant-design-pro uses roadhog?

**Comment by strangewolf** [comment]
Hii @jwmann i think @kbardi trying to say
add 
```
define: {
  'process.env': {},
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.API_ENV': process.env.API_ENV,
}```
in `.webpackrc.js` file
