### ISSUE TITLE
feature建议：dev指令新增entry参数

### ISSUE THREAD

**Issue by TimYi** [sorrycc/roadhog#609]
希望能给roadhog的dev指令新增entry参数解析。

用途是希望能通过命令行指定需要运行的程序入口，方便构建可展示的测试程序。

就和roadhog的test命令支持的功能一样。

**Comment by sorrycc** [comment]
我觉得可以有，有空提个 PR ?

**Comment by TimYi** [comment]
@sorrycc 没有开源项目提pr的经验，有需要规范的地方请多指教。

**Comment by TimYi** [comment]
Feature added.
