### ISSUE TITLE
支持开发模式下配置 publicPath

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#61]
有些场景还是需要的。

**Comment by sorrycc** [comment]
由于是 break change 并且场景少，先不加了，等 1.0 再考虑。有需要的可以通过配 `webpack.config.js` 解决。

**Comment by tcstory** [comment]
请问这个功能有实现吗?

**Comment by sorrycc** [comment]
@tcstory 有需求在 webpack.config.js 里配。
