### ISSUE TITLE
roadhog dev 重新编译好慢呀

### ISSUE THREAD

**Issue by kingyu** [sorrycc/roadhog#612]
- roadhog version（2.1.0）
- Nodejs and Npm version（6.6.0 and 3.10.3）
- Operating environment (e.g. OS name) and its version（操作系统版本）: win7 x64

你好，我用的是ant-design-pro 脚手架，里面的roadhog 是2.1.0，编译速度相比 1.3.0 的dllPlugin后大概慢3-4倍，翻阅了@sorrycc  好多解答，只看到一句话，按需加载会提高编译速度，但是鉴于技术有限，希望能出一些例子，怎么能提高  roadhog2 的编译速度，umi现在还是刚起步，而且ant-design-pro脚手架 替换 umi工具 学习成本有点高，最近项目很紧

#552 这个问题和我问题是一样的  求出示例吧

**Comment by sorrycc** [comment]
按需加载不会提高编译速度，按需编译才会，roadhog 是通用工具，没有掌控路由，所以上做这个不太现实。你可以尝试 externals 掉一些库试试。

**Comment by kingyu** [comment]
@sorrycc 可能我技术有限，自己实现 按需编译，没有头绪，希望作者大大可以给一点指导

**Comment by rainyx** [comment]
这个无法解决，只能自己写webpack.config，roadhog对webpack封装的过于重度（各有利弊），导致很多优化项无法添加进去。

**Comment by xiaolongyuan** [comment]
编译贼慢 +1

**Comment by liumin1128** [comment]
+1

**Comment by wufeng3** [comment]
+1

**Comment by guonanci** [comment]
+1

**Comment by Gpia** [comment]
编译非常慢，现在我的已经达到了 10分钟的级别

**Comment by songning0605** [comment]
我都到20分钟了

**Comment by chenhonghui** [comment]
我也慢，求分享如何迁移到webpack @rainyx

**Comment by rainyx** [comment]
> 我也慢，求分享如何迁移到webpack @rainyx

直接复用roadhog的webpack配置文件即可。
