### ISSUE TITLE
better roadhog console & debug experience request

### ISSUE THREAD

**Issue by arvinxx** [sorrycc/roadhog#615]
two parts to improve user experience.
## 1.better console message

now:
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180211/kHk7hk8jfH.png)

want:
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180211/bCcjCI513k.gif)

refer to [webpack-messages](https://github.com/lukeed/webpack-messages/blob/master/readme.md)

## 2.debug web error message
now when error:
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180211/fg5DBEf61L.png)

want as Creat react App:
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180211/99iIckkLH2.png)

or tell how to include it  and I will help.

## 3.use Browsersync to make live load 

I think it may get better dugging experience with [browsersync](http://www.browsersync.cn/)
And it's easy to config in Webpack,and also have great compatibility with HMR.

```js

const BrowserSyncPlugin = require('browser-sync-webpack-plugin'); // 使用 BrowserSync 作为重新加载的工具
module.exports = {
  ...
  plugins: [
    ...
    // BrowserSync 配置
    new BrowserSyncPlugin(
      {
        // 通过 BrowserSync 的访问地址为 http://localhost:9999/
        host: 'localhost',
        port: 9999,
        // 让 BrowserSync 代理 WDS 的访问地址(默认情况下为 http://localhost:8080/)
        // 注意：在这种情况下，需要使用 ` webpack-dev-server --env development `指令开启访问
        proxy: 'http://localhost:8080/',
      },
      {
        // 参数配置
        reload: false, // 阻止 BrowserSync 重新加载页面，让 Webpack Dev Server 完成加载工作
      },
    ),
  ...
  ]
}
```

One more thing.
Would there is any possible to include [storybook](https://github.com/storybooks/storybook) test package into construction progress？
I think it must get better experience to develop component in seperate environment like storybook than implement in a hole page with lots of stuff.

**Comment by sorrycc** [comment]
👍

**Comment by sorrycc** [comment]
> debug web error message

What is the version of your create-react-app?

**Comment by arvinxx** [comment]
> What is the version of your create-react-app?

My mistake. It isn't the feature of CRA, but one of webpack-dev-server.

And I check the webpack-dev-server of CRA, it use custom compiler to log warning and error messages.

```js
//webpackDevServer.config.js
module.exports = function(proxy, allowedHost) {
  return {
   //...
   // WebpackDevServer is noisy by default so we emit custom message instead
   // by listening to the compiler events with `compiler.plugin` calls above.
   quiet: true,
   //...
}
```
```js
//scripts/start.js
    //....
    // Serve webpack assets generated by the compiler over a web sever.
    const serverConfig = createDevServerConfig(
      proxyConfig,
      urls.lanUrlForConfig
    );
    const devServer = new WebpackDevServer(compiler, serverConfig);
    // Launch WebpackDevServer.
    devServer.listen(port, HOST, err => {
    //....
}
```

And in the above case I didn't use CRA, instead I configure webpack by myself.

The key config is  [overlay](https://doc.webpack-china.org/configuration/dev-server/#devserver-overlay) in dev-web-server
```
    overlay: {
      errors: true, // 编译出现错误时，错误直接贴到页面上
    },
```
Oh, another misktake. I use the [FriendlyErrorsWebpackPlugin](https://www.npmjs.com/package/friendly-errors-webpack-plugin). Forget plugin name,sorry.

Use overlay config with FriendlyErrorsWebpackPlugin can relpace RCA's custom compiler and get better experience.

Here is configuration:
```js
// webpack config root 
const FriendlyErrorsWebpackPlugin = require('friendly-errors-webpack-plugin');
module.exports = {
  // ... 
  devServer: {
    // ... 
    quiet: true,
    overlay: {
      errors: true
    },
    // ... 
  },
  // ... 
  plugins: [
    new FriendlyErrorsWebpackPlugin(),
  ],
}
````

Here is total demo.
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180212/cFd9jc8lDm.gif)

And here is my [configuration](https://github.com/arvinxx/JNode/tree/master/config)
