### ISSUE TITLE
roadhog makes a connection to ip.taobao.com

### ISSUE THREAD

**Issue by jwmann** [sorrycc/roadhog#621]
#### Environment(required) | 环境（必填）

- roadhog version: ^2.1.0
- Nodejs and Npm version: 9.5.0 & 5.6.0
- OS: MacOS 10.13.3

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
```
// package.json
"scripts": {
  "start": "cross-env DISABLE_ESLINT=true roadhog dev"
}

npm start
```

#### What happen?（发生了何种非正常现象）
The dev server made a connection to `ip.taobao.com`

#### What do you expected?（预期的正常效果）
No connection to `ip.taobao.com`

**Comment by sorrycc** [comment]
Reinstall roadhog, it's fixed.

**Comment by jwmann** [comment]
This does seem to be fixed. Thank you!

For those also wondering this, simply updating the module won't fix it, you have to uninstall it and install it again.
