### ISSUE TITLE
配置  hash后html上引用 怎么自动变换？

### ISSUE THREAD

**Issue by albafica2015** [sorrycc/roadhog#625]
<link rel="stylesheet" href="index.css" />
  <script src="index.js"></script>

index.html上面的引用是个死的，每次build怎么自动根据hash变换？

**Comment by ianyang1207** [comment]
在roadhog的webpack配置文件里有html template的配置，在那添加一个html模板就好了

**Comment by albafica2015** [comment]
那请问模版里面的 <script src="index.js"></script>  这句话怎么写？

**Comment by xaasu** [comment]
@ianyang1207  可以说详细一点吗？

**Comment by Superman-wc** [comment]
还是没看到怎么把manifest.json里的内容替换到index.ejs里面， 楼上诸位答非所问。。。

**Comment by Superman-wc** [comment]
@ianyang1207 你的回复没有说到重点啊，webpackrc配置传给ejs有变量， 可是js,css 是打包出来的， 对应关系在mainfest.json里

@sorrycc 具体要怎么实现？
