### ISSUE TITLE
entry如何配置

### ISSUE THREAD

**Issue by yamakasiluke** [sorrycc/roadhog#626]
roadhog你倒是把entry如何配置说明白啊。兄弟。

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#entry

**Comment by yamakasiluke** [comment]
English version 没有。
pr一发。
https://github.com/sorrycc/roadhog/pull/629

**Comment by sorrycc** [comment]
👍
