### ISSUE TITLE
can't import antd

### ISSUE THREAD

**Issue by pssgo** [sorrycc/roadhog#627]
![image](https://user-images.githubusercontent.com/16378134/36774946-fbb7f754-1c9a-11e8-96ff-20213a0483bb.png)
![image](https://user-images.githubusercontent.com/16378134/36774957-08723888-1c9b-11e8-9a5e-8cdc93cf22f9.png)
![image](https://user-images.githubusercontent.com/16378134/36774979-18d79876-1c9b-11e8-9a12-562527ee0cd9.png)

```javascript
{
     "husky": "^0.12.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.2.0"
}

```

why????

**Comment by yamakasiluke** [comment]
明显index.js没有引入button，打包编译一把。

**Comment by pssgo** [comment]
@yamakasiluke 第一张截图是index.js  里面引入了Button

**Comment by yamakasiluke** [comment]
第二三张没有引入

**Comment by pssgo** [comment]
@yamakasiluke  第二张是浏览器的报错， 第三张是编译后sourcemap

**Comment by yamakasiluke** [comment]
我都成功了，第二三张图中为什么没有button

**Comment by yesmeck** [comment]
重新安装依赖 https://github.com/ant-design/ant-design-pro/issues/936
