### ISSUE TITLE
historyApiFallback not working when set a different publicPath

### ISSUE THREAD

**Issue by douglasjunior** [sorrycc/roadhog#634]
#### Environment(required) | 环境（必填）

- roadhog version "2.3.0-beta.1"
- Nodejs and Npm version v8.9.4 and 5.6.0
- Operating environment (e.g. OS name) and its version: Mac OSX 10.13.3

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

On `.webpackrc.js`, set a different `publicPath`:

```js
module.exports = {
    ...
    publicPath: "/painel",
}
```

On html template, set a `<base />` tag:

```html
<head>
    <base href="/painel/" target="_blank">
</head>
```

If using **react-router**, set the router `basename`: 

```jsx
    <BrowserRouter basename="/painel" >
         ....
    </BrowserRouter>
```

#### What do you expected?（预期的正常效果）

When access `http://localhost:8000/painel/anything` the wepback should do a fallback to `/painel/index.html`.

#### What happen?（发生了何种非正常现象）

404 Cannot GET /painel/anything

#### Re-producible online demo (可复现的在线demo)

I can create if needed.

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by zyc017** [comment]
roadhog depend on webpack-dev-server ,if you change the publicPath , the server should change the redirect ,but roadhog did not allow to set the config ,so i change the source code(roadhog/node_modules/af-webpack/lib/dev.js) ,just like this
`function dev({
  webpackConfig,
  extraMiddlewares,
  beforeServer,
  afterServer,
  onCompileDone = noop,
  onCompileInvalid = noop,
  proxy,
  openBrowser: openBrowserOpts,
  historyApiFallback = {
    disableDotRule: true,
    index:webpackConfig.output.publicPath + 'index.html'
  }
})`

**Comment by douglasjunior** [comment]
Thanks. Unfortunately I went back to using webpack directly.

I believe that roadhog should make it easier, but not block changes to the webpack settings :/

**Comment by patientayo** [comment]
@douglasjunior you can set `proxy` property in `.webpack.js` as follows.

**Comment by patientayo** [comment]
@douglasjunior 
```javascript
export default {
  ...properties,
  "proxy": {
    "/painel": {
      "target": "http://<devhost>:<devport>",
      "pathRewrite": () => ("/painel/index.html"),
    },
  },
}
```

**Comment by douglasjunior** [comment]
Good idea, I'll try this next time, thanks!
