### ISSUE TITLE
请问如何在.webpackrc 里面配置webpack的第三方插件，譬如进度条插件

### ISSUE THREAD

**Issue by davecat** [sorrycc/roadhog#636]
脚手架是  adtd-pro

根据webpack官方文档，我在.webpackrc里面写：
plugins: []
报错plugins  字段设置非法，请删除。.webpackrc改成.webpackrc.js依然不能增加plugins

**Comment by vipcxj** [comment]
根目录加webpack.config.js，里面导出一个函数，入参是config，即webpack的config，你可以console.log一下看看结构，对这个config你可以随便改，然后返回，开发服务器就会使用这个你修改过的配置。貌似我在某个issure里看到的，是个超神秘但又及非常强大的功能，不知道为神马貌似作者不待见这个功能~ 文档里都没提。这个功能1.x就有了，2.x貌似也没去掉~

**Comment by cpu220** [comment]
我也碰到这问题，想自定义打包流程。写了个webpack插件，结果发现无法入手

**Comment by mountainmoon** [comment]
@cpu220 大致是这么一个写法
```js
var webpack = require('webpack')
module.exports = (config, env) => {
  if (env === 'production') {
    config.plugins.push(
      new webpack.optimize.UglifyJsPlugin({...})
    )
  }
  return config
}
```

**Comment by cpu220** [comment]
@mountainmoon  感谢。打印了下日志看懂了

**Comment by skyFi** [comment]
自定义配置 yaml-loader：
```javascript
module.exports = (config, { webpack }) => {
  config.module.rules.unshift(
    {
      test: /\.ya?ml$/,
      exclude: [/node_modules/],
      use: ['yaml-loader'],
    }
  );
  return config;
};

```

**Comment by skyFi** [comment]
！！ 已解决。

新增自定义 Loader（PS：官方不建议，扩展需谨慎。）
```javascript
'use strict';

module.exports = (config, { webpack }) => {
  config.module.rules.unshift(
    {
      test: /\.ya?ml$/,
      use: ['json-loader', 'yaml-loader'],
    }
  );
  config.module.rules.forEach(r => {
    if (Array.isArray(r.exclude)) {
      r.exclude.push(/\.ya?ml$/);
    }
  });
  return config;
};

```

**Comment by davecat** [comment]
@cpu220 thanks for your answer,but its not work，example：
![image](https://user-images.githubusercontent.com/21263055/37693604-c3fd4bd0-2c8e-11e8-86df-19bf4739d759.png)
warning:
![image](https://user-images.githubusercontent.com/21263055/37693836-55815014-2c90-11e8-8142-e777228f2c1f.png)
