### ISSUE TITLE
本地开发配置proxy后是好的，传到服务器上为什么调的是自己的ip？

### ISSUE THREAD

**Issue by albafica2015** [sorrycc/roadhog#639]
本地ip是http://localhost:8000/

build 把dist文件夹传到服务器上接口地址是： http://localhost:8000/mit/shoppingCart/getCartCount?userToken=null 

什么原因呢？为什么不是http://10.2.18.31:8080/shoppingCart/getCartCount?userToken=null

  "proxy": {
	  "/mit": {
	    "target": "http://10.2.18.31:8080/",
	    "changeOrigin": true,
	    "pathRewrite": { "^/mit": "" }
	  }

**Comment by albafica2015** [comment]
有人吗？急等

**Comment by xioozq** [comment]
proxy-middleware本来就是开发环境用的，上线如果还要用，自己在服务端把这个中间件加上

**Comment by codering** [comment]
那你去掉mit，用shoppingCart就可以了

**Comment by albafica2015** [comment]
@codering 能把代码贴出来吗？谢谢

**Comment by codering** [comment]
```js
"proxy": {
   "/shoppingCart": {
   "target": "http://10.2.18.31:8080/",
   "changeOrigin": true
}
```

**Comment by codering** [comment]
还有种方式就是 利用webpack的definePlugin定义变量 API
```js
"env": {
    "development": {
      "define": {
         "API": "/mit",
      }
    },
    "production": {
      "define": {
        "API": "",
      }
    }
  }

// request.js

 export async function request(url, options = {}) {
    url = `${API}${url}`
    ...
    ...
}

```

**Comment by albafica2015** [comment]
@codering 我是用.webpackrc这个文件配置的，请问是以下配置吗？

{
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
  ],

  "proxy": {
	  "/api": {
	    "target": "http://10.0.58.91:8080/",
	    "changeOrigin": true,
	    "pathRewrite": { "^/api": "" }
	  }
	},
  "hash":true,
  "html": {
    "template": "./src/entry.ejs"
    },

  "env": {
    "development": {
      "define": {
         "api": "/api"
      }
    },
    "production": {
      "define": {
        "api": ""
      }
    }
  }
}

**Comment by codering** [comment]
是。

**Comment by albafica2015** [comment]
@codering 我刚试下了一下  build之后传到服务器上还是报

http://10.0.53.220:8080/api/member/getMemberInfo?userToken=null 404 (Not Found)

接口ip是http://10.0.58.91:8080/   为什么还是指向自己的ip 不是接口的ip

**Comment by codering** [comment]
好吧。。。。我以为你是要去除url上的“api”。

你还是老老实实的在服务器上做转发吧。

**Comment by albafica2015** [comment]
@codering 运维不想每次在手动ngxin配置，想让我们在前端解决，能解决吗？

**Comment by codering** [comment]
无解。

**Comment by albafica2015** [comment]
前端真的没有办法吗？好烦

**Comment by albafica2015** [comment]
@codering 如果不要proxy，不做代理，前端在本地做host配置，然后开发，可以吗？

**Comment by GONDON** [comment]
我看你用的是webpackrc 你就把你里面的proxy 这个打包前删掉 @albafica2015

**Comment by lijiangwei** [comment]
@sorrycc roadhog打包部署以后proxy还生效吗？

**Comment by sorrycc** [comment]
@lijiangwei 不生效。
