### ISSUE TITLE
build 提示压缩失败

### ISSUE THREAD

**Issue by Ninshar** [sorrycc/roadhog#641]
#### Environment(required) | 环境（必填）
dva 2.1.0
- roadhog version（roadhog版本）
- 2.0.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- node v8.9.1
- npm v5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）:
- macos 10.13.3
#### What happen?（发生了何种非正常现象）
 build 失败，提示Failed to minify the bundle. Error: index.js from UglifyJs

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

.webpackrc配置
{
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
   ]
}

**Comment by sorrycc** [comment]
node_modules 里有非 es5 代码的问题，可以试着定位下是哪个依赖的问题，搞不定的话把能重现的源码打个包传上来。

**Comment by Ninshar** [comment]
@sorrycc 问题已解决，谢谢
编辑的时候回车引入了import { div } from 'gl-matrix/src/gl-matrix/vec4';

**Comment by blackboyhc** [comment]
我也碰到這個問題，經排查發現`query-string` 這個包會導致這個情況

**Comment by sorrycc** [comment]
用 query-string@5 。
