### ISSUE TITLE
extraBabelPlugins如何同时import antd和antd-mobile

### ISSUE THREAD

**Issue by kairi1227** [sorrycc/roadhog#643]
升级roadhog到2.0版本后，无法同时在extraBabelPlugins在配置antd和antd-mobile.
配置成如下：
```js
  "extraBabelPlugins": [
    [
      'import',
      {
        'libraryName': 'antd',
        'style': true,
      }
    ],
    [
      'import',
      {
        'libraryName': 'antd-mobile',
        'style': true,
      }
    ],
    "lodash"
  ],
```
提示异常：
```bat
they neen separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```
如下配置：
```js
"extraBabelPlugins": [
    [
      "import",
      [{
        "libraryName": "antd",
        // "libraryName": "antd-mobile",
        "libraryDirectory": "es",
        "style": true
      },
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "es",
        "style": true
      }
      ]
    ],
    "lodash"
  ],
```
提示异常：
```bat
Module build failed: Error: .plugins[0][1] must be an object, false, or undefined
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)

```

**Comment by remotesc2** [comment]
extraBabelPlugins: [
    'transform-decorators-legacy',
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
    ['import', { libraryName: 'antd-mobile', libraryDirectory: 'es', style: true }, 'antd-mobile-import'],
  ],
类似这样，babel7 中的修改

**Comment by kairi1227** [comment]
@remotesc2 thx.

**Comment by dashengqi** [comment]
这个问题有解决方案吗？

**Comment by dashengqi** [comment]
{
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "true" }],
    ["import", { "libraryName": "antd-mobile", "libraryDirectory": "es", "style": "true" }, "antd-mobile-import"]
  ]
}

这样写可行...

**Comment by qidasheng369** [comment]
{
  "extraBabelPlugins": [
        ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }],
        ["import", { "libraryName": "antd-mobile", "libraryDirectory": "es", "style": "css" }, "antd-mobile-import"]
    ]
}

这样可行，如果是true的话，不报错，但是样式不起作用。
