### ISSUE TITLE
roadhog 2.0 ESLINT env not work 

### ISSUE THREAD

**Issue by Carrotzpc** [sorrycc/roadhog#646]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）`2.0.0`
- Nodejs and Npm version（Nodejs 和 Npm 版本）`node: v8.9.4, npm: v5.6.0`
- Operating environment (e.g. OS name) and its version（操作系统版本）:  `macOS 10.13.3`

`ESLINT` is for roadhog 2.3.0 ? `DISABLE_ESLINT` worked in  2.0.0. 

[READEME](https://github.com/sorrycc/roadhog#environment-variables) is incorrect  for roadhog 2.0.0.

**Comment by xiaolongyuan** [comment]
+1 eslint 关不掉

**Comment by Carrotzpc** [comment]
升级到最新版，按照文档中的环境变量就可以了

**Comment by xiaolongyuan** [comment]
搜了代码 直接 cross-env DISABLE_ESLINT=true 关掉的
