### ISSUE TITLE
Disconnected from the devServer 不要一直location.reload( )

### ISSUE THREAD

**Issue by sam-dingkang** [sorrycc/roadhog#654]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）v2.3.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）v8.9.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:Mac OS

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
启动charles或者 SwitchyOmega代理后，隔一段时间页面会location.reload(),
![image](https://user-images.githubusercontent.com/15643321/37897725-7532fa6a-3119-11e8-80dc-8829aaab11ae.png)

#### What do you expected?（预期的正常效果）
socket 如果连接不上不要一直reload( ),Disconnected from the devServer，不要轮询自动的reload.

#### What happen?（发生了何种非正常现象）
1. antd-pro部署到开发服务器，开启SwitchyOmega代理后，Disconnected from the devServer,页面会轮询reload。
2. 断开dev server 会一直console 错误日志。

![image](https://user-images.githubusercontent.com/15643321/37899311-c5cfffd2-311d-11e8-92ec-0521cd74541a.png)
![image](https://user-images.githubusercontent.com/15643321/37899344-de79f1e6-311d-11e8-8f9f-9365b2b77bb3.png)
希望这里能优化

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
配下 SOCKET_SERVER 能解决？connect 逻辑理是这么写的，

```
var connection = socket(
  process.env.SOCKET_SERVER
    ? `${stripLastSlash(process.env.SOCKET_SERVER)}/sockjs-node`
    : url.format({
        protocol: window.location.protocol,
        hostname: window.location.hostname,
        port: window.location.port,
        // Hardcoded in WebpackDevServer
        pathname: '/sockjs-node',
      }),
  ...
```

**Comment by sam-dingkang** [comment]
请问一下 SOCKET_SERVER怎么配置？在webpackrc.js里？可以给出例子吗，我试试。我目前是在node_module里注释的reload,因为影响到开发服务器代理，谢谢。

**Comment by sorrycc** [comment]
环境变量，比如：

```bash
$ SOCKET_SERVER=http://xxx.com:port roadhog dev
```

**Comment by sam-dingkang** [comment]
刚试了一下不行，还有一种复现方式就是：SOCKET_SERVER=http://xxx.com:port 配在 start 里，然后本地 tnpm start，可以模拟出SwitchyOmega代理页面一直location.reload( )问题;

**Comment by jiajiuxing** [comment]
我也遇到同样的问题。请问一下问题解决了吗？

**Comment by cymoft** [comment]
今天碰到了类似的问题，原因应该是devServer的websocket没有被正确的proxy。
对我来说hot reload不是很重要，干脆把webpackHotDevClient.js干掉拉倒。方法是用null-loader。
在webpack.config.js代码中
webpackConfig.module.rules.push({test: path.resolve(__dirname, 'node_modules/af-webpack/lib/webpackHotDevClient'), use: "null-loader"});

**Comment by DaviGao** [comment]
same +1

**Comment by daodangui** [comment]
+1

**Comment by zhaoyejuan** [comment]
same +1

**Comment by AntiMoron** [comment]
这个太炸了、 要知道不是所有调试都在localhost. 我们预发服务端可不像本地那样会起个ws给我连。。这给我load完了。 @sorrycc  看看8？
