### ISSUE TITLE
build 压缩后访问报错

### ISSUE THREAD

**Issue by duwei54** [sorrycc/roadhog#660]
#### Environment(required) | 环境（必填）

- roadhog version（2.3.0）
- Nodejs and Npm version（Nodejs 9.6.1 和 Npm 5.7.1）
- Operating environment (e.g. OS name) and its version（win7 64bit）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

"build": "cross-env ESLINT=none roadhog build"
结果报错:
Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings

"build-all": "cross-env ESLINT=none COMPRESS=none roadhog build"
不压缩  结果正常

#### What do you expected?（预期的正常效果）

build 压缩  结果正常

**Comment by boyongjiong** [comment]
@duwei54 你好，你解决了这个问题嘛？

**Comment by duwei54** [comment]
@boyongjiong 没有唉,不知道哪里的问题

**Comment by wyj580231** [comment]
同样的问题,请问解决了嘛

**Comment by duwei54** [comment]
@wyj580231 没有 现在仍然用未压缩的跑着

**Comment by xchunzhao** [comment]
@duwei54  我也遇到相同问题。我本地build是有`NODE_ENV`的，其他机器没有。由于在`webpackrc`中配置了`define`，所以在build的时候手动设置一次:
```
"build": "cross-env NODE_ENV=production ESLINT=none roadhog build"
```
Yet, it works.

**Comment by duwei54** [comment]
@xchunzhao 感谢提供解决思路,我之前试过显示加入NODE_ENV=production 但是还是没有作用,郁闷,可能是别的原因

**Comment by sorrycc** [comment]
更新 roadhog@2.4.2 重新 build 试试。

**Comment by LightningVII** [comment]
我目前是 2.4.2 这个问题依旧存在

**Comment by duwei54** [comment]
@LightningVII 好呢,感谢提供方案.目前项目移交了没维护了^^,先关了这个issue
