### ISSUE TITLE
2.0 roadhog ignores the file resources while compiling(打包时忽略了引入的文件资源)

### ISSUE THREAD

**Issue by liuzhenji** [sorrycc/roadhog#662]
#### Environment(required) | 环境（必填）

- roadhog version（v2.2.0）
- Nodejs and Npm version（v9.5.0 和 v5.8.0）
- Operating environment (High Sierra) and its version（v10.13.3）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
#xxx.jsx
import f from 'path.png';

npm run build

目标目录dist/static中未打包相应的图片资源

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

![image](https://user-images.githubusercontent.com/10750792/38321470-5b5fb2f6-386a-11e8-8fd3-56a6c25af966.png)

![image](https://user-images.githubusercontent.com/10750792/38321606-9c62aefc-386a-11e8-8051-637728673d12.png)

**Comment by liuzhenji** [comment]
![image](https://user-images.githubusercontent.com/10750792/38321678-d17f318c-386a-11e8-960a-16b7ab54f522.png)

**Comment by liuzhenji** [comment]
看了下af-webpack源码，url-loader?limit=10000图片小于10K，自动base64。

**Comment by xyw1005** [comment]
分享下解决方法呗
