### ISSUE TITLE
roadhog  如何配置 webpack的Module？？这个能解决就好了，就差一步

### ISSUE THREAD

**Issue by lettywiterock** [sorrycc/roadhog#666]
[https://github.com/sorrycc/roadhog/blob/1.x/README.md](url)
在官方的的文档里面，找不到Module配置方法，如果能配置此项，就可以加载第三方的模块了

**Comment by zhuaizhuaixi** [comment]
同求，不知道如何修改url-loader的配置

**Comment by YiShengEasy** [comment]
问题一样

**Comment by sorrycc** [comment]
新建 webpack.config.js，

```
export default (webpackConfig) => {
  修改后返回
}
```

**Comment by chen86860** [comment]
建议把可以 merge `webpack.config.js`的配置信息放到文档以公示，以方便开发者调整自己的配置。
