### ISSUE TITLE
extraBabelPlugins的option是数组会报错。例如 ["import", [{ "libraryName": "antd", "libraryDirectory": "es", "style": true }]]

### ISSUE THREAD

**Issue by pkl93** [sorrycc/roadhog#667]
"extraBabelPlugins": [
    [
      "import", [
        { "libraryName": "antd", "libraryDirectory": "es", "style": true }，
      ]
    ],
]
webpackrc.js中使用以上配置会报如下错误：
./src/index.js
Module build failed: Error: .plugins[0][1] must be an object, false, or undefined
    at Array.forEach (native)
    at Array.forEach (native)
应该是不支持数组了，然后试了以前版本的 roadhog（1.2.1） 这样写是没有问题的。
现在需要给antd之外的组件库加类似的配置，但因为这个错误，除了用回旧版本roadhog，不知道该怎么办。

**Comment by pkl93** [comment]
@zhongds 非常感谢，it works perfectly！

**Comment by arieslx** [comment]
今天我也遇到了这个问题，可以解决，但是不知道原理是为啥
