### ISSUE TITLE
用dva/dynamic异步加载如下报错 （roadhog 2.3.0）

### ISSUE THREAD

**Issue by pkl93** [sorrycc/roadhog#668]
Unhandled Rejection (Error): Loading chunk 11 failed.
HTMLScriptElement.onScriptComplete
internal:/webpack/bootstrap 4f0ca11eda24511288fc:756

如果在webpackrc.js里加上 "publicPath": "/"  ，组件能正常使用不会报错，但不知道原因

**Comment by sorrycc** [comment]
google 下 webpack + publicPath

**Comment by pkl93** [comment]
怪我问题没描述清楚，奇怪的地方是不加publicPath，也只是部分异步组件会出这个问题（routes文件夹下的组件全部正常）。而且在用roadhog2 之前不需要配置publicPath也不会出现这个问题。

**Comment by pkl93** [comment]
@sorrycc, 怪我问题没描述清楚，奇怪的地方是即使不加publicPath，也只是部分异步组件会出这个问题（routes/xxxx 引用的都正常， routes/xxx/mmm 这种就不行）。而且在用roadhog2 之前不需要配置publicPath也不会出现这个问题。
