### ISSUE TITLE
Failed to upload image when proxy 

### ISSUE THREAD

**Issue by zhangfu-git** [sorrycc/roadhog#669]
.roadhogrc.mock.js

#### Environment(required) | 环境（必填）

roadhog  2.3.0
node        8.10.0
Mac         10.13.4 

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
.roadhogrc.mock.js 配置
```
const noProxy = process.env.NO_PROXY === 'true';
export default noProxy ? {
  "POST /(.*)": "http://127.0.0.1:1337/",
  "PUT /(.*)": "http://127.0.0.1:1337",
  "GET /(.*)": "http://127.0.0.1:1337/",
  "DELETE /(.*)": "http://127.0.0.1:1337/"
} : delay(proxy, 1000);
```

```
npm run start:no-proxy
```
使用antd 的Upload组件上传图片
#### What do you expected?（预期的正常效果）
预期图片上传成功

#### What happen?（发生了何种非正常现象）
请求头正常，但服务端没有接收到上传的图片，打包后的代码不走代理上传图片成功。

**Comment by yuyueh** [comment]
#482 可以參考這篇最下面的回答。
在 __**.roadhogrc.mock.js**__ 裡設定307的轉發就可以讀取到檔案了。
