### ISSUE TITLE
Theme doesn't work for antd components

### ISSUE THREAD

**Issue by urrri** [sorrycc/roadhog#670]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog 2.3.0）
- Nodejs and Npm version（Nodejs 8.9.1 Npm 5.5.1）
- Operating environment (e.g. OS name) and its version（win10）:
- dva 2.2.2 
- antd 2.4.1

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
Create project with dva-cli (0.9.2)
Add support for antd
Define theme in webpackrc (e.g. change @primary-color to #f00) (I took code for changing theme from antd-admin sample)
Add antd Button to main page and change color of title to @primary-color in less
Start app.
Button remains blue as in default theme. Title takes changed primary color. 

#### What do you expected?（预期的正常效果）
Theme should be changed for both user defined and original antd components.
In the antd-admin project (roadhog 1.3.1) all works as expected

#### What happen?（发生了何种非正常现象）
antd Button remains blue as in default theme. Title takes changed primary color. 

#### Re-producible online demo (可复现的在线demo)
https://github.com/urrri/antd-theme-test

![image](https://user-images.githubusercontent.com/1422691/38627940-d15d2f58-3db8-11e8-865f-2635ea09c9c0.png)

**Comment by sorrycc** [comment]
You should set the style opts of babel-plugin-import to `true`, ref: https://github.com/ant-design/babel-plugin-import/#-libraryname-antd-style-true-

**Comment by urrri** [comment]
A lot of thanks. It works !!!!! (I would search the problem forever)

**Comment by Superman-wc** [comment]
.webpackrc.js 里设置
export default {
  "extraBabelPlugins": [
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "es",
        "style": true
      }
    ]
  ],
  "theme": {
    "@primary-color": "#1DA57A"
  }
}
 主题不起作用， 要如何解决
