### ISSUE TITLE
jest的globals配置无法生效？

### ISSUE THREAD

**Issue by mutouzdl** [sorrycc/roadhog#672]
**我的操作步骤如下：**
 
- 我希望在单元测试中使用全局变量，给package.json添加了以下配置：
`"jest": {
    "globals": {
      "__Dev__": true
    }
}`

 - 编写了一个简单的测试（demo.test.js）：
`
test('demo', () => {
  console.log('__Dev__:', __Dev__);
});
`

 - 运行命令：npm test demo.test.js

- 结果报错，__Dev__未定义：
![image](https://user-images.githubusercontent.com/3509249/38653837-36640e68-3e3f-11e8-94b8-48ab5a3831fa.png)

**请问，想要实现这个功能，在roadhog里是有其他配置方式吗？**

**Comment by xxy101** [comment]
删除当前umi-test,下载最新的umi-test
项目里添加jest.config.js
文件内增加：exports.globals = { "__Dev__": true }

**Comment by mutouzdl** [comment]
解决了，非常感谢。

**Comment by kristiankyvik** [comment]
Hi @mutouzdl, I am trying to add a jest config file to an ant-design-pro project.

```
// jest.config.js
module.exports = {
  moduleFileExtensions: ["js", "json"],
};
```
 I tried translating the comment by @xxy101, and I added the last version of the umi-test package. But I still get the following error:

```
FAIL src/e2e/login.e2e.js
  ● Test suite failed to run

    Cannot find module './types/standard' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/puppeteer/node_modules/mime/index.js:4:27)
```
I wondered if you could help me!

**Comment by kristiankyvik** [comment]
@zhangtemplar thanks, I will give it a try!
