### ISSUE TITLE
build 后报错 roadhog@1.2.2

### ISSUE THREAD

**Issue by SynChron1zed** [sorrycc/roadhog#673]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）1.2.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）
- Operating environment (e.g. OS name) and its version（操作系统版本）: mac

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/38720590-63d687a0-3f29-11e8-9391-fbb69b0edef9.png)

**Comment by SynChron1zed** [comment]
但是这里有啥问题呀 之前看到有回答是es5 转换的问题 但是这块代码应该不是呀

**Comment by sorrycc** [comment]
用了 `=>`，一样是 ES5 转换的问题。

**Comment by sorrycc** [comment]
package.json 贴上来看下。

**Comment by SynChron1zed** [comment]
{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.9.2"
  },
  "dependencies": {
    "antd": "^3.3.0",
    "babel-plugin-import": "^1.6.6",
    "babel-runtime": "^6.9.2",
    "create-react-class": "^15.6.3",
    "dva": "^2.0.0",
    "dva-react-router-3": "^0.3.0",
    "echarts": "^4.0.4",
    "prop-types": "^15.6.1",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "roadhog": "^1.2.2"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.5.2"
  }
}

**Comment by sorrycc** [comment]
报错代码是 query-string@6 的，但没在你的依赖里看到他，https://github.com/sindresorhus/query-string/blob/597f14a/index.js#L8

**Comment by SynChron1zed** [comment]
好 我自己找下

**Comment by HiMrHu** [comment]
@SynChron1zed  最简单办法 yarn add query-string@5.1.1 不要使用6版本即可

**Comment by sorrycc** [comment]
https://github.com/sorrycc/blog/issues/68

**Comment by SynChron1zed** [comment]
@HiMrHu  问题早解决了  我给他删了
