### ISSUE TITLE
model改名后项目启动不了

### ISSUE THREAD

**Issue by xaasu** [sorrycc/roadhog#675]
#### Environment(required) | 环境（必填）
- roadhog version（roadhog版本）
^1.3.4
- Nodejs and Npm version（Nodejs 和 Npm 版本）
node : 8.9.0
npm : 5.5.1
- Operating environment (e.g. OS name) and its version（操作系统版本）:
win 10

#### What happen?（发生了何种非正常现象）
models目录下一个model目录改变，index.js中app.model('xx');也改成修改后的目录。但是项目启动报错，看错误提示是app.model读取的仍然是旧的目录。
 
![tim 20180417114418](https://user-images.githubusercontent.com/24312839/38847589-0488e54a-4235-11e8-9c04-bca2340148b4.png)

#### What do you expected?（预期的正常效果）
项目正常启动

**Comment by sorrycc** [comment]
rm -rf ./node_modules/.cache 再试。
