### ISSUE TITLE
升级roadhog后访问二级页面js路径不对

### ISSUE THREAD

**Issue by HiMrHu** [sorrycc/roadhog#678]
#### Environment(required) | 环境（必填）

- roadhog version （roadhog版本）roadhog 2.3.0
- Nodejs and Npm version （Nodejs 和 Npm 版本）Nodejs 8.9.4 Npm 5.8
- Operating environment (e.g. OS name) and its version（操作系统版本）: macOS 10.13.4

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

更新roadhog后,访问二级地址,会导致js文件地址不正确.

#### What do you expected?（预期的正常效果）

例如 访问二级页页面路径例如

    www.xxxxxx.com/test/

比如这个页面可能需要第 22.async.js ,和 9.async.js 
预期正常情况

    www.xxxxxx.com/22.async.js
    www.xxxxxx.com/9.async.js

加载两个js文件

#### What happen?（发生了何种非正常现象）

    www.xxxxxx.com/test/22.async.js
    www.xxxxxx.com/test/9.async.js

目前是会这样加载两个js,然后会返回index.ejs 导致直接报错
`Uncaught SyntaxError: Unexpected token <` (因为html开头的<html)

经过手动访问

    www.xxxxxx.com/22.async.js

这样是可以访问到js文件的.

#### Re-producible online demo (可复现的在线demo)
[可复现的在线demo](https://github.com/HiMrHu/roadhogDemo)
,昨天升级roadhog1.2.1 到 2.3.0 之后发生了这个问题
经过查询记录,更新了`roadhog 2.3.0`和`babel-plugin-dva-hmr 0.4.1`这两个依赖
代码中使用了`dva 2.1.0`,并且使用了 `dva/dynamic` 做代码拆分.

恳请大大帮忙解决,配置文件我也和antd pro对过了也是差不多的,所以不知道为什么出现这个问题
<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

下面是weboackrc.js文件配置
```js
const path = require('path');
const pxtorem = require('postcss-pxtorem');


export default {
  entry: 'src/index.js',
  "theme": "./theme.config.js",
  "html": {
    "template": "./src/index.ejs"
  },
  "hash": true,
  env: {
    development: {
      extraBabelPlugins: [
        'dva-hmr',
        ['import', {'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true}],
        'emotion',
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 33,
          propWhiteList: [],
        }),
      ],
    },
    production: {
      extraBabelPlugins: [
        ['import', {'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true}],
        'emotion',
      ],
      extraPostCSSPlugins: [
        pxtorem({
          rootValue: 33,
          propWhiteList: [],
        }),
      ],
      // extraBabelIncludes:[ // 传递参数使babel额外编译第三方包含es6语法的包
      //   "node_modules/query-string/", // query-string包含es6语法(箭头函数/let/const等语法
      //   "node_modules/strict-uri-encode/", // query-string的依赖使用了箭头函数
      // ],
    }
  }
};

```

**Comment by HiMrHu** [comment]
提供一个最小可再现 demo

https://github.com/HiMrHu/roadhogDemo

**Comment by sorrycc** [comment]
得配下 publicPath 。

**Comment by HiMrHu** [comment]
搞定，以前写了，可能写错了或者其他原因没有生效，谢谢大佬，百忙之中回复提问，留下demo供后来人学习
https://github.com/HiMrHu/roadhogDemo
