### ISSUE TITLE
antd 字体本地化问题

### ISSUE THREAD

**Issue by 1cy** [sorrycc/roadhog#68]
相同问题的issue地址：https://github.com/ant-design/ant-design/issues/1615；
解决方案是修改webpack的loader，如何修改roadhog的配置？

**Comment by sorrycc** [comment]
webpack 的 loader 是怎么改的?

**Comment by 1cy** [comment]
http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts 在这里 ，麻烦看一下

**Comment by sorrycc** [comment]
那里写了两个方案：

1. publicPath，roadhog 支持配置的，看文档
2. extract-text-webpack-plugin，roadhog build 时就是用这个打包的

现在是用 roadhog 时遇到问题了吗？

**Comment by 1cy** [comment]
是的 我配置过publicPath没有生效 还报那个问题 请问还要写什么配置项么？

**Comment by sorrycc** [comment]
开发状态下?

**Comment by lxlf** [comment]
字体文件放到 public/fonts/iconfont/ 文件夹下面，放到其他的文件夹下面就会报那个错误，
在roadhog里面加这个配置
  "theme": {
    "@icon-url": "'/fonts/iconfont/iconfont'"
  },

**Comment by 1cy** [comment]
@lxlf  @sorrycc    放在public/fonts/iconfont/  下面可以了   谢谢

**Comment by oyhk** [comment]
@lxlf 你是怎么引用的 <Icon type="icon-zizhushouhuoji" />

**Comment by ShadowRambler** [comment]
@sorrycc 如果更改了publicPath，也用了本地化的icon，打包时生成的字体文件路径依然是@icon-url的设置，而实际的路径是publicPath+@icon-url的，如果修改@icon-url匹配打包的路径那开发环境下字体路径就会有问题。。。
