### ISSUE TITLE
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null

### ISSUE THREAD

**Issue by TDiDa** [sorrycc/roadhog#683]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）v2.3.0
- Nodejs and Npm version（Nodejs 和 Npm 版本）v9.11.1  v5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: Mac os

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

roadhog dev报错：
`
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)
`

**Comment by sorrycc** [comment]
删除 `.webpackrc.js` 里的 `transform-decorators-legacy`，参考 https://github.com/ant-design/ant-design-pro/pull/1345

**Comment by TDiDa** [comment]
可以了，多谢

**Comment by strangewolf** [comment]
Hi,
Even i got this same error `Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null at Array.map (<anonymous>`
after updating npm
