### ISSUE TITLE
如何配置 compression-webpack-plugin 插件

### ISSUE THREAD

**Issue by OPY-bbt** [sorrycc/roadhog#700]
webpack 中有插件可以直接输出gzip文件，而且 ngnix 中可以配置 gzip_static 直接使用build之后的 gzip 文件。 那么在 roadhog 中 如何在 build 时开启 gzip ? 或者如何配置？

**Comment by jszjgqq** [comment]
同问

**Comment by sorrycc** [comment]
gzip 不是 roadhog 的功能范围了，你可以在 roadhog build 完之后使用其他功能加一层 gzip 压缩。
