### ISSUE TITLE
roadhog(2.4.0)打包ant-design-pro .webpackrc.js中env production 配置无效

### ISSUE THREAD

**Issue by huip** [sorrycc/roadhog#715]

**Comment by vnicers** [comment]
相同的问题。
` env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
      define: {
        API_BASE_URL: "http://localhost:8811"
      }
    },
    production: {
      define: {
        API_BASE_URL: "http://10.127.161.7:8080/api/stream-catalog"
      }
    }
  },`

在npm run build 后 ReferenceError: API_BASE_URL is not defined

**Comment by vnicers** [comment]
在 package.json的启动脚本里面 加上NODE_ENV=production  就可以了，之前好像不需要的。
` "build": "cross-env NODE_ENV=production ESLINT=none roadhog build",`

**Comment by sorrycc** [comment]
Thanks for report, it's fixed via roadhog@2.4.2 .

**Comment by Zhou-Bill** [comment]
同样配置，但报undefined
![image](https://user-images.githubusercontent.com/13554001/47077128-dba4ab80-d232-11e8-9494-b847eb932680.png)
![image](https://user-images.githubusercontent.com/13554001/47077165-ecedb800-d232-11e8-86db-704e421604ef.png)
