### ISSUE TITLE
.webpackrc.js配置文件无效

### ISSUE THREAD

**Issue by Xing-He** [sorrycc/roadhog#717]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）:  1.3.4
- Nodejs and Npm version（Nodejs 和 Npm 版本）:  npm `5.6.0` ;  node `v10.0.0`
- Operating environment (e.g. OS name) and its version（操作系统版本）: Mac OS

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

根据 [参考文档](https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#%E9%85%8D%E7%BD%AE) 配置 ，我定义了如下配置：

- `.webpackrc.js`

```js
export default {
  "define": {
    "VERSION": "1.0.1"
  },
}
```

**但是配置没有效果。**

我在`.roadhogrc`中配置这段`define`代码是有效果的

**Comment by sorrycc** [comment]
roadhog@1.x 的 .roadhogrc 在 roadhog@2 改名为 .webpackrc 了。

**Comment by Xing-He** [comment]
- [`roadhog 1.x`版本](https://github.com/sorrycc/roadhog/blob/1.x/README.md) 是通过 `.roadhogrc` 或 `.roadhogrc.js` 指定启动并指定配置的；  
- 而 2.x的版本是通过 `.webpackrc` 或 `.webpackrc.js`启动并指定配置

> 因此我是应该在`.roadhogrc.js` 指定配置项
