### ISSUE TITLE
Build hangs at 91%

### ISSUE THREAD

**Issue by chillyistkult** [sorrycc/roadhog#720]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog 2.4.2）
- Nodejs and Npm version（Nodejs 10.1.0 Npm 5.6.0）
- Operating environment (e.g. OS name) and its version（OS X High Sierra 10.13.4）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

I made code additions in my ant-design-pro based project. Regulary roadhog tries to rebuild the application and hangs at 91%. When I kill roaghog, the node instance is still running in the background with around 2 gb of memory used.

#### What do you expected?（预期的正常效果）

App rebuilds without problems, no matter how frequent I change files or how big my project is.

#### What happen?（发生了何种非正常现象）

Roadhog freezes at 91% build regulary (I have the impressions that it happens when I change code very frequently). This was not happening with the last roadhog version.

#### Re-producible online demo (可复现的在线demo)

It also happens in https://github.com/ant-design/ant-design-pro

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
It's compressing, ref: https://www.google.com/search?q=uglify+webpack+91&oq=uglify+webpack+91&aqs=chrome..69i57.2663j0j7&sourceid=chrome&ie=UTF-8

**Comment by lulei90** [comment]
这个问题 我这边也经常出现。 不知道是不是依赖包出了问题？ 我们前一个项目 npm start的时候都很快，后面新开的项目 npm start的时候 在控制台就开始出现 build进度的显示，经常开发过程中就会遇到build到91%然后就卡住不动
