### ISSUE TITLE
how to change JS outputPath ?  

### ISSUE THREAD

**Issue by taoqianbao** [sorrycc/roadhog#724]
now when use roadhog to build JS,cSS, all files publish to the root directory;     
how to change to like /static/assets/js/xxxxx.js      /assets/css/xxxxx.css ? 

thank you

**Comment by tang-yue** [comment]
@taoqianbao  
I have the same problem, can you solve it?

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog#outputpath
