### ISSUE TITLE
roadhog搭建工具很多BUG，许多语法和作用域的错误要到实际用户点击了才会报错，希望能改进

### ISSUE THREAD

**Issue by LaiHuanMin** [sorrycc/roadhog#726]
我目前遇到的问题如下：

语法和作用域明显错误的情况，不能及时全屏显示错误，而是要等到执行到该代码（比如点击事件）才报错
模块更改的时候没有反应，我采用的是linux Ubuntu LTS16.04的操作系统，不知道是不是fs.watch这个问题
修改代码的时候 dynamic require的对应组件，修改居然不能对roadhog进行触发重新compile
在使用antd-pro的时候，修改src/theme.js（添加less变量）之后，无法进行重新编译
  
现在是2.3.0的roadhog版本，配合的是Ant-Design-Pro

希望能改进，谢谢！

**Comment by yoyo837** [comment]
是eslint 问题吗？建议ESLINT=true

而且vscode有部分无法正确提示，不知道是否依赖项配置或者版本问题。

Ant-Design-Pro clone过来 npm ls 是报错的

**Comment by LaiHuanMin** [comment]
恩，谢谢回复，我再进行排查问题
