### ISSUE TITLE
0.6更新到2.4版本的问题

### ISSUE THREAD

**Issue by zpzxgcr** [sorrycc/roadhog#733]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
2.4
- Nodejs and Npm version（Nodejs 和 Npm 版本）
8.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:
win7 64

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

更新到最新版之后遇到的问题都有在issue看到 最后能编译成功 项目无法运行

#### What do you expected?（预期的正常效果）

能够看到效果

#### What happen?（发生了何种非正常现象）
×
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
无法正常打开

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by zpzxgcr** [comment]
`
import { get } from '../../services/service.js'

module.exports = {
  namespace: 'home',
  state: {
    openAjax:false,
    routeUrl:'/home',
  },
  subscriptions: {
  },
  effects: {
    * openAjax({ payload: open }, { put, call,select }) {
       yield put({type: 'toggleAjax', payload: open})
    },
     * closeAjax({ payload: open }, { put, call,select }) {
       yield put({type: 'cloAjax', payload: open})
    }
  },
  reducers: {
    toggleAjax(state, { payload:openAjax }) {
       
      state.openAjax = openAjax;
      return { ...state }
    },
    cloAjax(state, { payload:open }) {
      
      state.openAjax = open;
      return { ...state }
    },
    targetUrl(state,{payload:url}){
      console.log(url,'---------------------');
      state.routeUrl = url;
      return {...state}
    },

    string(state,{payload:res}){
      console.log(res,'---------------------');

      return {...state,res}
    },
    schoolUrl(state,{payload:sUrl}){
      console.log(sUrl)
      return {...state,sUrl}
    },
  }
}
`

**Comment by sorrycc** [comment]
参考升级文档，https://github.com/sorrycc/roadhog/blob/master/migrate-from-1.x_zh-cn.md
