### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kwzm** [sorrycc/roadhog#734]
#### Environment(required) | 环境（必填）

- roadhog version 1.1.1
- Nodejs and Npm version node 10.1.0 npm 5.6.0 
- Operating environment (e.g. OS name) and its version（操作系统版本）: win7 x64

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
build 的时候报如下错误：

![default](https://user-images.githubusercontent.com/16114101/41088696-c0568b8c-6a72-11e8-8e89-1e3263a492f8.PNG)

报错文件的455行内容如下：

![2](https://user-images.githubusercontent.com/16114101/41088719-ccb7ac94-6a72-11e8-927a-f4c9493aa480.PNG)

ps：为何打开这个打包文件总是把我的ide（vscode）卡死呢，难道是文件太大了吗？

#### What do you expected?（预期的正常效果）

build 无错

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
参考 https://github.com/sorrycc/blog/issues/68

**Comment by kwzm** [comment]
@sorrycc 感谢，不过怎么看是哪个报出错了呢，我这个打包的文件在vscode里打开直接把编辑器卡死了。

**Comment by sorrycc** [comment]
`COMPRESS=none roadhog build`

**Comment by kwzm** [comment]
感谢，by the way，1.x没有`COMPRESS`参数，是通过设置`roadhog build --debug`实现的
