### ISSUE TITLE
devServer 设置 header 出错

### ISSUE THREAD

**Issue by PeterRao** [sorrycc/roadhog#735]
```
devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  },
```
封装了webpack后，如何设置 devServer 的 headers 。上面的代码会报错 `Configuration item devServer is not valid, please remove it`

**Comment by waltcow** [comment]
@PeterRao 最后问题怎样解决的？本地开发上传文件到OSS，发现遇到同样的跨域问题

**Comment by bianlin** [comment]
+1
