### ISSUE TITLE
how to async load component and commons chunk plugin is invalid .

### ISSUE THREAD

**Issue by xgj1988** [sorrycc/roadhog#745]
#### Environment(required) | 环境（必填）
- roadhog 2.1.0（roadhog版本）
- Nodejs and Npm version（Nodejs 和 Npm 版本）
  nodejs v6.11.2   npm 3.10.10
- Operating environment (e.g. OS name) and its version（操作系统版本）:
  win10  专业版本
#### What did you do? Please provide steps to re-produce your problem. 
   我用官网的commons chunk 这个配置，没反应，我现在用的是antd pro+ roadhog+ dva，打包错来的代码 有 15M。而且还是index_xxxxx.js文件。。太大了。怎么破呢？

#### What do you expected?（预期的正常效果）
如何异步加载，如何把大文件拆分。

#### What happen?（发生了何种非正常现象）

文件过大
#### Re-producible online demo (可复现的在线demo)
 无

**Comment by sorrycc** [comment]
antd pro 有文档介绍的，https://pro.ant.design/docs/deploy-cn 搜 disableDynamicImport 。

**Comment by xgj1988** [comment]
@sorrycc  现在打出来的包 是 多个了。。每个分离的小包  是必以前的15M 要小，，但是 总和加起来 比以前大很多，以前是15M，现在变成了37个文件，总和为108M了。。这个现象正常吗？

**Comment by zhang0ZGC** [comment]
@xgj1988 你这个问题解决了么？我也是发现，除非在entry上面配置vendor:['react','antd']等，才能打包到公共文件，但是在commons里面配置没有用
