### ISSUE TITLE
如何修改css module的class名

### ISSUE THREAD

**Issue by OumCc** [sorrycc/roadhog#746]
![image](https://user-images.githubusercontent.com/10840542/41763130-c8725dc8-762f-11e8-95f0-6e6711c30e74.png)

如上图，正式环境下只想保留后半部分的hash值，减少css的体积。

暂时没有找到配置的方法，所以想请教一下

**Comment by aixfox** [comment]
这个值生产环境和开发环境不同

node_modules/af-webpack/src/getConfig.js
```javascript
localIdentName: isDev
  const cssModulesConfig = {
    modules: true,
    localIdentName: isDev
      ? '[name]__[local]___[hash:base64:5]'
      : '[local]___[hash:base64:5]',
  };
```
```javascript
  {
    loader: require.resolve('css-loader'),
    options: {
      ...cssOptions,
      ...(cssModules ? cssModulesConfig : {}),
    },
  },
```

在 webpackConfig.module.rules 中只是简单判断了一下，localIdentName 并没有放出来配置

**Comment by NicholasNC** [comment]
@aixfox @sorrycc 不知道有没有计划开放：localIdentName

每次都修改node_modules不太方便

**Comment by chanyt0216** [comment]
Would you allow us to config the value since I can't trace the class name for testing?
