### ISSUE TITLE
配置环境变量无效

### ISSUE THREAD

**Issue by green-lizard** [sorrycc/roadhog#757]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）2.4.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）8.*
- Operating environment (e.g. OS name) and its version（操作系统版本）:mac os 10.12

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

![image](https://user-images.githubusercontent.com/24819514/42375411-10f52fe8-814e-11e8-8796-935a270247c8.png)

#### What do you expected?（预期的正常效果）

`process.env.API_URL` 

#### What happen?（发生了何种非正常现象）

得到了undefined

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by jayguojianhai** [comment]
为你解决了吗？

**Comment by Zhou-Bill** [comment]
请问如何解决
