### ISSUE TITLE
roadhog配置ssl(https)如何操作?

### ISSUE THREAD

**Issue by zhouhuiquan** [sorrycc/roadhog#760]
rt,
前面有个兄弟提问,但是没人解答.

**Comment by dkvirus** [comment]
roadhog 只是开发时用的吧，开发时要整 https 干嘛。一般都是开发完成，roadhog build 将静态资源扔到 nginx/tomcat，对 nginx 用 ssl 的吧~

**Comment by zhouhuiquan** [comment]
@dkvirus 没做过https的东西,完全不知道是怎么一回事.
