### ISSUE TITLE
Why is my app trying to outbound connect to alipay.com? (private-alipayobject.alipay.com)

### ISSUE THREAD

**Issue by jwmann** [sorrycc/roadhog#765]
I recently updated the environment from my old ant-design-pro to the latest.
Ever since updating the packages for specifically `roadhog`, `roadhog-api-doc` and `puppeteer` I get this outbound connection every time I start my server.
 
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）2.4.1
- Nodejs and Npm version（Nodejs 和 Npm 版本）nodejs (9.11.1) npm (5.6.0)
- Operating environment (e.g. OS name) and its version（操作系统版本）: MacOS 10.13.5

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
`npm start` (cross-env ESLINT=none roadhog dev)

#### What do you expected?（预期的正常效果）
No connections to external servers e.g.: alipay

#### What happen?（发生了何种非正常现象）
An outbound connection to `private-alipayobject.alipay.com`

https://jwm.d.pr/StvAet/oaPWfzWPPC

![image](https://cdn-sec.droplr.net/files/acc_2368/StvAet?response-content-disposition=inline%3B%20filename%3DScreen%2520Shot%2520on%25202018-07-16%2520at%252015%253A40%253A03.png&Expires=1531770397&Key-Pair-Id=APKAJTEIOJM3LSMN33SA&Signature=WJcIDQ~qxhJBhLpz7MGKLHVm4wXs1ZLzS3BJjqLXvvRJzZF3I4QdgAKVDYBdPHGaBfvA0EZ7QLc0SfyfdQ8FcplL3Sal56v33AlsZCQDBVck01YtG~-xqwCZyzyXpVDV7cWzrSuV44mAKICKdp1KFfDEyax08FcS~-bvddiCfQ0_)

**Comment by jwmann** [comment]
I see that the node module `is-ali-env` is doing this call:
```
superagent.get('https://private-alipayobjects.alipay.com/alipay-rmsdeploy-image/rmsportal/FlPJSPwhzfagtBoHKCbu.png')
```

Which is probably where it is coming from, but where is this being loaded?

**Comment by jwmann** [comment]
`is-ali-env` seems to be loaded via another node module called `atool-monitor`

And `atool-monitor` is being used by `roadhog`
_node_modules/roadhog/lib/roadhog.js_ 
```
56:    require('atool-monitor').emit();
```

**Comment by jwmann** [comment]
Yes, I'm using ant-design-pro at an enterprise level (which is what it's designed for) and I'd prefer if my build scripts didn't ping China every time it built the app. Even though I'm sure it is harmless, it still is very suspect and will cause problems for security.

I'd prefer if it was removed or at the very least, given an option to disable it or even better have it disabled by default and have an option to enable it.

Thank you~

**Comment by sorrycc** [comment]
We will add `ALI_MONITOR=none` to disable the bacon.

**Comment by jwmann** [comment]
Thank you! 😃

**Comment by dengfuping** [comment]
@jwmann atool-monitor 0.4.5 has been released. Just reinstall and you can set `ALI_MONITOR=none roadhog dev` to disable it.
