### ISSUE TITLE
npm install roadhog 报错

### ISSUE THREAD

**Issue by hearAllParties** [sorrycc/roadhog#774]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）2.4.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）9.6.1  5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: OS

#### What happen?（发生了何种非正常现象）

```
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for moo@^0.4.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'nearley'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eugene/.npm/_logs/2018-07-23T08_49_43_685Z-debug.log
```

#### Re-producible online demo (可复现的在线demo)
npm 源设置的是私有源，如果设置淘宝源则可正常install。7月20日之前，设置npm设置私有源可以正常安装私有依赖和公有依赖，之后发现除了roadhog不能install，其它依赖都能正常install。
<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by sorrycc** [comment]
私有源的问题吧，找不到 `moo@^0.4.3`。
