### ISSUE TITLE
use markdown return base64

### ISSUE THREAD

**Issue by whhlulu** [sorrycc/roadhog#777]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） 2.4.2

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
webpack.config.js
module.exports = (webpackConfig, env) => {
  webpackConfig.module.rules.push({
    test: /\.md$/,
    use: 'raw-loader',
  });
  return webpackConfig;
}
console.log(require('test.md'))===>data:text/markdown;base64,bW9kdWxlLmV4cG9ydHMgPSAiPGgyIGlkPVwiYWFcIj5hYTwvaDI+XG48aDIgaWQ9XCJhYVwiPmFhPC9oMj5cbiI7

#### What do you expected?（预期的正常效果）
console log      '## aa ## aa'

#### What happen?（发生了何种非正常现象）
输出结果被base64加密了，是af-webpack对所有l文件loader时做了操作吗？

**Comment by dalaoque** [comment]
hi，
您好，
我也遇到同样的困惑，
请问是怎么解决这个问题的？

十分感谢！

**Comment by whhlulu** [comment]
af-webpack对所有文件做了url-loader，去设置md文件不需要urlloader

**Comment by dalaoque** [comment]
Got it！

再一次感谢！

**Comment by wangchun0020** [comment]
> af-webpack对所有文件做了url-loader，去设置md文件不需要urlloader

roadhog有配置项能覆盖url-loader的参数吗？  比如改 limit ，现在只能去改af-webpack的npm包。
