### ISSUE TITLE
how to use require.context 

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [sorrycc/roadhog#787]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） ^2.4.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）v8.11.3
- Operating environment (e.g. OS name) and its version（操作系统版本）:win 10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

* webpackrc.js

```
const customProxy = require('./proxy').dafault; // 导入代理设置
```
目录
```
├─proxy
    ├─index.js
    └─proxy.dict.js
```
* index.js
```
const context = require.context('./', true, /\.js$/);
export default context; 
```

#### What happen?（发生了何种非正常现象）
>require.context is not a function
#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by yuanjie007** [comment]
@tz310200 
I also encountered the same problem, how can I solve it?
