### ISSUE TITLE
extraBabelIncludes这个配置在2.4.2是被取消了吗

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [sorrycc/roadhog#788]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本） 2.4.2
- Nodejs and Npm version（Nodejs 和 Npm 版本）node v8.11.3 npm 5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）: win 10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

完全参照的该demo https://github.com/umijs/umi-examples/tree/master/es5-imcompatible-versions

#### What happen?（发生了何种非正常现象）
```
Failed to minify the bundle. Error: index.js from UglifyJs
```

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by goodwinfame** [comment]
同样遇到这个问题，配置后不生效。

**Comment by baohouse** [comment]
It looks like support for extraBabelIncludes was removed as of version 2.0. Documentation is outdated.

**Comment by dkvirus** [comment]
我这边配置后是生效的，但是样式显示异常。

**Comment by zry754331875** [comment]
@dkvirus 遇到了同样的问题，antd的按需加载部分失效了
