### ISSUE TITLE
2.4.3 本地代理问题

### ISSUE THREAD

**Issue by yoyo837** [sorrycc/roadhog#795]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
 v2.4.3
- Nodejs and Npm version（Nodejs 和 Npm 版本）
v8.11.4 v5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:
MacOS 10.13.6
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
`yarn run dev` 后 有红字一闪而过，然后被清屏了Starting the development server...
v2.4.2没有
#### What do you expected?（预期的正常效果）
https://github.com/ant-design/ant-design-pro/issues/1577  原来的配置是如果某路径有配置mock则走mock没有配置则走代理, 现在不起作用了，都被本地开发服务器响应为index.html：
```js
import mockjs from 'mockjs';
import { getSysUserListResult } from './mock/api';
import { format, delay } from 'roadhog-api-doc';
import { baseURL } from './mock';
import { menuList, userInfo } from './mock/user';
import { messageStatusList, informMessage } from './mock/message';

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

const proxyTarget = `http://localhost:8080/cloud${baseURL}/`;

// 代码中会兼容本地 service mock 以及部署站点的静态数据
const proxy = {
  // 支持值为 Object 和 Array
  // GET POST 可省略

  /**
   * ------------------------------华丽的分割线------------------------------
   */
  // [`GET ${baseURL}/queryUserInfo.do`]: userInfo,
  // [`GET ${baseURL}/querySysMenuList.do`]: menuList,
  // [`GET ${baseURL}/commonMessage/getMessageStatusList.do`]: messageStatusList,
  // [`GET ${baseURL}/commonMessage/informMessage.do`]: informMessage,

  [`${baseURL}/(.*)`]: proxyTarget,
  [`POST ${baseURL}/(.*)`]: proxyTarget,
};

// 随机延迟1-3秒
export default (noProxy ? {} : delay(proxy, 1000 * Math.ceil(Math.random() * 3)));


```

#### What happen?（发生了何种非正常现象）
mock配置 失效了（或者原本的方式就不对？）

#### Re-producible online demo (可复现的在线demo)
如果需要可提供

**Comment by zhiyan** [comment]
同遇到此问题, mock文件报错, 不兼容以前的写法了?

mock：
```
'GET /api/*': 'http://xxx/'
```

```
Missing "target" option. Example: {target: "http://www.example.org"}
```

**Comment by lixiaolihua** [comment]
+1 
[2019](https://github.com/ant-design/ant-design-pro/issues/2019)

**Comment by imandarava** [comment]
+1

**Comment by yesmeck** [comment]
Sorry， #786 没有很好的测试。能否帮忙测试下 #796 是否有问题？

**Comment by yoyo837** [comment]
@yesmeck 要协助测试吗？需要大家怎么做？

**Comment by yesmeck** [comment]
可以把 #796 的分支拉到本地，然后 `npm run build`，把构建出来的 `lib` 目录拷贝到项目的 `node_modules/roadhog` 下。

**Comment by PeterRao** [comment]
尽快处理下，代理出目前不可用

**Comment by yoyo837** [comment]
@PeterRao 先锁旧版本用呗

**Comment by sorrycc** [comment]
+ roadhog@2.4.4

**Comment by yoyo837** [comment]
@yesmeck 刚发现 `POST` json 还有问题

**Comment by yesmeck** [comment]
@yoyo837 什么问题

**Comment by yoyo837** [comment]
后端io读取超时

**Comment by yesmeck** [comment]
@yoyo837 curl 的请求发下

**Comment by lixiaolihua** [comment]
+1

**Comment by yoyo837** [comment]
@yesmeck 8000的web dev代理到8080/cloud

![image](https://user-images.githubusercontent.com/6134547/44382896-5a3ddf00-a549-11e8-941f-5e6258db1a63.png)

**Comment by yoyo837** [comment]
对齐 curl 参数 再来一次

![image](https://user-images.githubusercontent.com/6134547/44383017-c6b8de00-a549-11e8-9057-fe96162e2457.png)

**Comment by yesmeck** [comment]
@yoyo837 试下 https://github.com/sorrycc/roadhog/pull/797

**Comment by yoyo837** [comment]
@yesmeck #797不可以哦

**Comment by yesmeck** [comment]
@yoyo837 还是超时？

**Comment by yoyo837** [comment]
@yesmeck 是的，和之前的现象一致。

**Comment by yesmeck** [comment]
奇怪，我测试是可以的

**Comment by yoyo837** [comment]
我再次测试了一遍，确实如此。

![image](https://user-images.githubusercontent.com/6134547/44447372-65147480-a61a-11e8-8765-8172c3eef07f.png)
![image](https://user-images.githubusercontent.com/6134547/44447386-73629080-a61a-11e8-9167-8ad99fef18ac.png)
![image](https://user-images.githubusercontent.com/6134547/44447404-84ab9d00-a61a-11e8-9620-338e6aeb7501.png)

**Comment by fisher-89** [comment]
我升级后也遇到了相同的问题，推测是因为循环导致body-parser在http-proxy-middleware之前执行。
在调整body-parser的位置后问题解决，但不能确定是否会影响其他功能，如果确实可用，还麻烦尽快更新一下版本。
![image](https://user-images.githubusercontent.com/19706882/45151136-18c35a00-b200-11e8-9ea9-cbef1c201871.png)

**Comment by yoyo837** [comment]
@fisher-89 的确给人的感受是卡住一段时间，然后后台报io读取超时。

**Comment by yoyo837** [comment]
我这边因为私人原因，暂时没进去调试细看，所以不清楚原因。@fisher-89  你的意思是以我的场景测试一下你的方案看能否解决是吧？

**Comment by yoyo837** [comment]
@fisher-89 是的，可以，按你的方式修改我这边post正常了。
