### ISSUE TITLE
proxy post broken

### ISSUE THREAD

**Issue by yoyo837** [sorrycc/roadhog#801]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
 v2.4.5
- Nodejs and Npm version（Nodejs 和 Npm 版本）
v8.11.4    v5.6.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:
macOS mojave public beta 8
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

Please see here and follow-up discussions: https://github.com/sorrycc/roadhog/issues/795#issuecomment-414288428

**Comment by shirleyYing** [comment]
本地代理到测试环境报错，得不到返回数据

**Comment by yoyo837** [comment]
Related: #806 #807
