### ISSUE TITLE
proxy websocket not working

### ISSUE THREAD

**Issue by AlexanderChen1989** [sorrycc/roadhog#804]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）
v2.4.5
- Nodejs and Npm version（Nodejs 和 Npm 版本）
v8.11.2  yarn
- Operating environment (e.g. OS name) and its version（操作系统版本）:
Mac OS
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

![image](https://user-images.githubusercontent.com/2957936/45007932-96d20600-b032-11e8-8de5-9f17b779eb24.png)

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by AlexanderChen1989** [comment]
配置websocket代理失效

**Comment by yoyo837** [comment]
@AlexanderChen1989 测试一下 #807
