### ISSUE TITLE
如何读取到.roadhogrc的env配置?

### ISSUE THREAD

**Issue by xttianma** [sorrycc/roadhog#81]
用于,项目的配置文件判断

**Comment by sorrycc** [comment]
在项目文件里获取？项目文件里只能获取到 [define](https://github.com/sorrycc/roadhog#define) 的配置。

**Comment by xttianma** [comment]
module.exports = (function () {
    console.log(development);
    if ( SYSTEM_ENV =='develop'){ return config.develop }
    if ( SYSTEM_ENV =='test'){ return config.test }
    if ( SYSTEM_ENV =='production'){ return config.production }    
})();

有这么一个文件, 读取外部的环境变量SYSTEM_ENV , 来判断是开发/生产环境,然后输出对应的配置. 

SYSTEM_ENV, 我写在哪里呢?或者我在开发和生产不同的环境,设置哪里来判断环境?

**Comment by sorrycc** [comment]
`process.env.SYSTEM_ENV` ?

**Comment by xttianma** [comment]
后台开发,用process对象读取,前台js不可以吧.
都是同一套代码,怎么处理不同环境变量的呢?

**Comment by codering** [comment]
@xttianma 前端也可以的，webpack内部做过处理

**Comment by sorrycc** [comment]
试一下。
