### ISSUE TITLE
2.5.0-beta.1版本在and pro v1 版本中mock切换失效

### ISSUE THREAD

**Issue by windyzoe** [sorrycc/roadhog#830]
#### Environment(required) | 环境（必填）

- roadhog version（2.5.0-beta.1）
- Nodejs and Npm version（Nodejs 8.1 和 Npm 5.1）
- Operating environment (e.g. OS name) and its version（操作系统版本）:
window 7
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
下载最新的antd pro1，注意是v1
更新roadhog到2.5 beta，用来升级babel。

.roadhogrc.mock.js添加
'GET /api/(.*)': 'http://168.61.10.224:9999/api',
'POST /api/(.*)': 'http://168.61.10.224:9999/api',

之前一直没问题，这几天好像跳转不过去了，郁闷

#### What do you expected?（预期的正常效果）
本地环境，直接切到sit环境用
'GET /api/(.*)': 'http://168.61.10.224:9999/api',  这种方式，能跳转过去

#### What happen?（发生了何种非正常现象）
cnpm npm install 都有问题

**Comment by windyzoe** [comment]
首先，谢谢 @sorrycc 。roadhog很好用。
另外，问一下啊，roadhog还维护嘛？不维护的话我转原生了啊！

**Comment by ybning** [comment]
同遇此问题：
![image](https://user-images.githubusercontent.com/3725612/44702975-6b966680-aac8-11e8-94eb-a0478617c5f3.png)

**Comment by ybning** [comment]
#807

**Comment by windyzoe** [comment]
@ybning 兄弟，我这里用beta.4 mock又挂了。你哪里怎么样？

**Comment by windyzoe** [comment]
解决了，是写法的问题  GET /api/(.)': 'http://168.61.10.224:9999/api/'
最后这个斜杠不能忘了！！！！
