### ISSUE TITLE
升级到0.5.2会出现 babel not find的错误

### ISSUE THREAD

**Issue by hellheaven** [sorrycc/roadhog#84]
错误如下。0.3.2正常

Failed to compile.

Error in multi index
Module not found: 'babel' in C:\temp\demo

 @ multi index

**Comment by sorrycc** [comment]
以 [dva-example-user-dashboard](https://github.com/dvajs/dva-example-user-dashboard) 为例，试了下没有问题。没 win 平台，你重装依赖或者自己定位试试吧。

**Comment by codering** [comment]
https://github.com/sorrycc/roadhog/issues/99

**Comment by sorrycc** [comment]
roadhog@0.5.3 已修复。
