### ISSUE TITLE
使用compass

### ISSUE THREAD

**Issue by WayneVN** [sorrycc/roadhog#842]
roadhog 中如何配置使用 ` compass ` 完全没有看到可配置的地方。。。。

**Comment by tsejx** [comment]
compass？是 compress 吧，roadhog^2.x 好像默认开启 compress，如果 build 时不压缩可以在压缩时加上 `NO_COMPRESS` 或者 `COMPRESS=none`。

**Comment by WayneVN** [comment]
@tsejx  不是compress  [compass](http://compass-style.org/)
