### ISSUE TITLE
roadhog 是3月1号要停止维护了吗

### ISSUE THREAD

**Issue by Blackgan3** [sorrycc/roadhog#855]
如题，在使用roadhog构建项目的时候，提示3月1日不再维护，目前没有在roadhog查找到任何关于停止维护的声明，是否还有其他替代方案呢

**Comment by luckly-boy** [comment]
是的，维护大佬说已停止，建议移步umi

**Comment by trexguo** [comment]
最近有想法做一个类似的工具，参考roadhog，把webpack和babel升到最新。先在公司内部使用后面开源出来回馈社区。

**Comment by Blackgan3** [comment]
> 是的，维护大佬说已停止，建议移步umi

哎，不行还是手撸webpack吧
