### ISSUE TITLE
使用roadhog引入antd，build时会有很多注释，导致发布系统报错

### ISSUE THREAD

**Issue by LighterEast** [sorrycc/roadhog#856]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）^1.2.1
- Nodejs and Npm version（Nodejs 和 Npm 版本）nodejs:v8.12.0;npm:6.5.0
- Operating environment (e.g. OS name) and its version（操作系统版本）:macos

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
使用roadhog配置了antd
![image](https://user-images.githubusercontent.com/32625695/53394505-77f96e80-39da-11e9-9af8-bdeeac1b53b7.png)

使用just run build 构建了文件，产生的css文件会有注释
![image](https://user-images.githubusercontent.com/32625695/53394616-c3ac1800-39da-11e9-8f96-4420819390df.png)

just publish -n发布日常版本时，由于注释导致报错，无法发布

#### What do you expected?（预期的正常效果）
希望能够构建时不出现这些注释，正常发布

#### What happen?（发生了何种非正常现象）
构建css时出现了注释，无法发布

#### Re-producible online demo (可复现的在线demo)
构建时的报错地址：https://work.def.alibaba-inc.com/iteration/205679/task/754534?active=gog
<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

项目代码库：http://gitlab.alibaba-inc.com/dt-fe/yunchuan-sem-bak

**Comment by ikobe** [comment]
@LighterEast 两种办法，在 package.json 中的 scripts build 后，除了跑 roadhog, 再加一段脚本做压缩，使用这个： https://cssnano.co/

另外内部使用 bigfish 好一点

**Comment by ikobe** [comment]
roadhog 1.x 不提供 css 压缩功能，2.x 也不再维护了 ~~ 内部用 bigfish 把
