### ISSUE TITLE
roadhog按需加载，出现内存溢出？

### ISSUE THREAD

**Issue by nenezsn** [sorrycc/roadhog#857]
1.在配置路由的地方，有些页面加载进来但没有使用(图中选中的地方)，导致打包的index.js很庞大，后来删除掉，结果报了内存溢出的错误，感觉很奇怪，明明是删掉无用代码，反而打包更慢了，不删除反而没问题，速度也不慢，不知道是什么原因？有大神指导一下吗？，现在增大内存可以解决，但是不明白为什么会出现我这种现象， “CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
”
![image](https://user-images.githubusercontent.com/25813931/54011299-f3160e00-41ac-11e9-884f-8c7be18408cb.png)

**Comment by nenezsn** [comment]
正常来说 我如果import 新的页面 ，然后内存溢出这还可以理解，为什么我删掉这个引进来但没有使用的代码，反而会内存溢出呢，实在不理解。

**Comment by nenezsn** [comment]
@sorrycc 麻烦大哥解释一下

**Comment by flyjer6** [comment]
请问解决了吗？
