### ISSUE TITLE
mock的自定义函数中的req获取不到body

### ISSUE THREAD

**Issue by dicklwm** [sorrycc/roadhog#86]
.roadhogrc.mock.js的配置：
```
'POST /api/login': (req, res)=> {
    //  undefined   {}   {}
    console.log(req.body,req.params,req.query);
    res.end('ok');
}
```
server/app.js中的login方法：
```
export async function login (params) {
  return request('/api/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({userName:"minlee",password:"2"})
  })
}
```
- 我用REST Client去POST访问接口也是这样
![image](https://cloud.githubusercontent.com/assets/19289258/21984253/121a0c8c-dc30-11e6-9519-ade481518b85.png)

- 结果在req中获取到的req.body是undefined，是我配置有问题还是咋的？
- 我把mock改成GET接口也是获取不到body

**Comment by sorrycc** [comment]
我忘记加相关的中间件了，比如 [busboy](https://github.com/mscdex/busboy)

**Comment by dicklwm** [comment]
好的，下个版本什么时候可以更新啊？

**Comment by DickyT** [comment]
谢谢!!!

**Comment by showonne** [comment]
Mark, 期待更新。

**Comment by yvanwangl** [comment]
@sorrycc 我安装了~0.6.0-beta1版还是获取不到body的数据呢？不是已经修复了嘛

**Comment by pkaq** [comment]
用了最新版本同样获取不到 加了body-parser也没用

**Comment by zuiidea** [comment]
修复了吗？

**Comment by sorrycc** [comment]
修复了，但还没发。

**Comment by sorrycc** [comment]
Try roadhog@0.6.0-beta.3

**Comment by sapronlee** [comment]
0.6.0-beta.3 中mock下req.body依旧拿不到，看了看代码，发现里面的确是依赖了body-parser，但是runServer里面没有使用啊

**Comment by zuiidea** [comment]
@sapronlee
`npm uninstall roadhog -g`
`npm install roadhog@0.6.0-beta.3 -g`

**Comment by sapronlee** [comment]
@zuiidea OK,谢谢，已经OK

**Comment by OptimusYang** [comment]
@zuiidea 执行后 还是拿不到，一样的报错。

**Comment by zuiidea** [comment]
@OptimusYang `roadhog -v`应该不是`0.6.0-beta.3`吧

- `C:\Users\{你的电脑名字}\AppData\Roaming\npm`下删除roadhog.cmd和roadhog，及`C:\Users\{你的电脑名字}\AppData\Roaming\npm\node_modules\roadhog`
- `npm install roadhog@0.6.0-beta.3 -g`

**Comment by OptimusYang** [comment]
@zuiidea version是0.6.0-beta.3, 同时我也执行了删除和重新安装，还是拿不到，代码版本就是4.1的branch。 挺郁闷的。

**Comment by zuiidea** [comment]
@OptimusYang  你把packge.json里的roadhog去掉，再`npm install`一下呢

**Comment by OptimusYang** [comment]
@zuiidea  更新了你最新的trunk流代码，就是你merge完之后的，是可以了，然后我打开旧的4.1的代码，移除了roadhog的依赖，手动安装roadhogbeta3，也可以了。 这是为什么呢？我看到你在最新的版本里也去掉了roadhog的依赖转为自己手动安装。

**Comment by OptimusYang** [comment]
@zuiidea 发现写在依赖里，重新安装后，拿到的是beta2版本，这是怎么回事？

**Comment by zuiidea** [comment]
@OptimusYang我也发现了，所以才让你删了装的，也许是cnpm的原因吧

**Comment by ScottYan** [comment]
被这个问题折腾了一天, 还以为是我写错了...

**Comment by LaiHuanMin** [comment]
关注关注！现在还是不行

**Comment by suiyi8760** [comment]
@LaiHuanMin 注意post的话要用request-payload传递data，form-data好像接收不了

**Comment by dyf19118** [comment]
关注
