### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by cuongtk8** [sorrycc/roadhog#872]
I am using Ant Design Pro v1. I have a problem with `babel-runtime` when install new package. Have a solution? Thanks!

![1](https://user-images.githubusercontent.com/34389409/60416715-aeedc400-9c08-11e9-8fef-b97e17bfdcbf.png)

**Comment by cuongtk8** [comment]
I close this issue! I upgraded `roadhog` version to handle it.
```
"roadhog": "^2.5.0-beta.4"
```

**Comment by dengtingsheng** [comment]
nice
