### ISSUE TITLE
升级2.0以后，libraryTarget没有了，怎么做组件了？在线等

### ISSUE THREAD

**Issue by Jackyhe** [sorrycc/roadhog#879]
大侠们，能帮忙国；回答下不

**Comment by Jackyhe** [comment]
现在2.x的版本，没有了libraryTarget， 没办法使用module.export, 请问，这个问题怎么解决呢

**Comment by sorrycc** [comment]
可以在配置里通过 chainWebpack 配，但组件开发不推荐用基于 webpack 的 roadhog ，改用基于 rollup 的 father 吧。

**Comment by Jackyhe** [comment]
好的，感谢，问题已解决
