### ISSUE TITLE
打包图片路径正常，但服务器域名访问，所有图片不显示

### ISSUE THREAD

**Issue by 520Yanxiaofei** [sorrycc/roadhog#91]
npm run build编译打包，访问dist下的页面，图片路径显示都正常

还有一点，到了服务器，访问域名时，图片都不显示了，也就是static前面加个./就能显示图片了
![image](https://cloud.githubusercontent.com/assets/16931900/22016188/43f72248-dce0-11e6-8e12-49db44c1b6d5.png)
加了./static后显示正常了
![image](https://cloud.githubusercontent.com/assets/16931900/22016214/693401ca-dce0-11e6-82fd-72126894279a.png)

期望结果
能保证服务器发布时，访问域名，所有图片都能正常显示

麻烦云谦兄了！

**Comment by sorrycc** [comment]
需要配 [publicPath](https://github.com/sorrycc/roadhog#publicpath)。

**Comment by 520Yanxiaofei** [comment]
@sorrycc 谢谢您，问题已解决了！祝云谦兄，鸡年大吉，哈哈

**Comment by xaviertung** [comment]
@520Yanxiaofei Hi，你怎么配置的publicPath，require的哪个路径？谢谢〜
