### ISSUE TITLE
核实一个 fsevents 相关的性能问题

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/roadhog#93]
https://github.com/dvajs/dva/issues/509

* fsevents 是否存在于依赖链
* 没有 fsevents 是否会走 poll 方式的文件监听
* 在 roadhog 里显式依赖 fsevents 是否能解决问题

**Comment by DickyT** [comment]
1. fsevents是存在于dva依赖链的, dva cli创建完会有
2. fsevents不存在roadhog的package.json里面
3. 我试过在我本机环境里面 在node_modules/roadhog目录下`npm i --save fsevents`可以解决问题
