### ISSUE TITLE
我很想知道roadhog和dva是什么关系？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [sorrycc/roadhog#95]
roadhog和dva是什么关系？

**Comment by dicklwm** [comment]
dva是基于redux，redux-saga，react-route的框架，roadhog是基于create-react-app脚手架优化简便的脚手架，简单的说就约等于dva是react+redux，roadhog是webpack

**Comment by liuhuapiaoyuan** [comment]
非常感谢。已经用起来了，太爽了！！！！！
