### ISSUE TITLE
请谨慎配置outputPath

### ISSUE THREAD

**Issue by liekkas** [sorrycc/roadhog#96]
昨天脑子一热想把输出文件直接输出到当前目录下，配置outputPath："./"，结果你懂得，代码全无。还未提交git的代码就这样say goodbye了。
建议文档里着重强调一下，**build时会对outputPath指定目录先删为敬**。避免其它吃瓜群众重蹈覆辙。

**Comment by sorrycc** [comment]
感谢建议，是得提醒下。。

**Comment by miaojiuchen** [comment]
好惨

**Comment by junmaqiang** [comment]
好惨

**Comment by varrant** [comment]
好惨
