### ISSUE TITLE
刚用，请问如何像webpack那样，配置目录的alias，这样写起来比较方便

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [sorrycc/roadhog#97]
刚用，请问如何像webpack那样，配置目录的alias，这样写起来比较方便

**Comment by sorrycc** [comment]
没有内置  alias，可以通过 `webpack.config.js` 扩展 webpack 配置。https://github.com/sorrycc/roadhog#配置

**Comment by liuhuapiaoyuan** [comment]
额 好吧..其实我觉得这个alias很好用 可以考虑一下

**Comment by chenchensdo** [comment]
添加webpack.config.js会报“require(...) is not a function”这个错误
