### ISSUE TITLE
window下，SET HOST 貌似无效

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [sorrycc/roadhog#98]
The app is running at:

  http://192.168.31.248:8000/

已经有这样的提示了，但是依然无法访问。
这样局域网下就无法用手机联调了，有点尴尬

**Comment by sorrycc** [comment]
本地能用 http://192.168.31.248:8000/ 访问到吗? 能的话就不是 roadhog 的问题，而是防火墙或者本地网络的问题了。

**Comment by liuhuapiaoyuan** [comment]
本机也不行，自己另外跑了一个webpack  是没任何问题的，改了一下roadhog  的listen 源码，现在可以了。

**Comment by sorrycc** [comment]
怎么改的?

**Comment by pvtyuan** [comment]
runServer.js 162行 devServer.listen()没加host参数

**Comment by sorrycc** [comment]
谁有兴趣提个 pr 吗?

**Comment by pvtyuan** [comment]
有兴趣，但还不太会，待我多折腾下

**Comment by pvtyuan** [comment]
我测试了下，win10 x64，node 7.3.0，没能复现

**Comment by liuhuapiaoyuan** [comment]
runServer.js 162行 devServer.listen()没加host参数
是的 我是改这个的。。
