### ISSUE TITLE
Module not found: 'babel' @ multi index

### ISSUE THREAD

**Issue by miaojiuchen** [sorrycc/roadhog#99]
dva new出来的项目在osx上跑不起来，https://github.com/dvajs/dva-example-user-dashboard 这个例子也同样的问题

**Comment by suweya** [comment]
npm要升级到最新版的，或者npm install -g npminstall    npm install -g cnpm

**Comment by miaojiuchen** [comment]
@suweya ok 感谢

**Comment by miaojiuchen** [comment]
建议加入文档里

**Comment by sorrycc** [comment]
npm 什么版本下不行?

**Comment by miaojiuchen** [comment]
在哪可以看到前一个版本号？没太注意，更新了后就可以了

**Comment by suweya** [comment]
3.x 好像，依赖的包好像会没安装全

**Comment by ddliao** [comment]
安装最新版本npm4.1.1还是不得行，我家里的win10操作系统，node版本6.9.1,编译没有问题，公司电脑是win7的，我刚才也试了下安装node6.9.1也不行

**Comment by sorrycc** [comment]
roadhog@0.5.3 已修复。
